### PR TITLE
make debug code compile in value_set.cpp

### PR DESCRIPTION
**Pull request by polgreen**
Minor change. debug code did not compile before

### CODE REVIEW

**Review by martin-cs — APPROVED** [review]
If you felt the need to convert the #if 0 to #if SOMETHING_MEANINGFUL I would not object.

**Comment by polgreen** [comment]
Would you prefer #if DEBUG? Most of the CBMC debug code seems to be inside #if 0 statements, so this is at least consistent

**Comment by martin-cs** [comment]
#if 0 used to get used for all kinds of things, old code, dead code, debug code, "don't really know what this does but kind of don't want to delete it" code.  So it might be best if we moved away from using it.  #if DEBUG works, #if DEBUG_VALUE_SETS would work as well.

**Review by smowton — APPROVED** [review]
Not even I can contrive a nitpick for this one

**Comment by polgreen** [comment]
I've changed to DEBUG to be consistent with the include for <iostream>. I've not changed the rest of the #if 0's in the file though, because, as you pointed out, some of that code isn't actually debug code, it's mystery code.

**Review by chrisr-diffblue — APPROVED** [review]
Looks good to me too.

**Pull request merged**
