### PR TITLE
Remove void_typet

### PR DESCRIPTION
**Pull request by tautschnig**
I suggest reviewing commit-by-commit.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 75d5d289621130a265bb321437f9e147d19f24d1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99859081
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
I'm assuming the bot failure is genuine: @svorenova @thk123 whenever time permits, could you scan TG for occurrences of `void_typet` and update this as is done in the commits in this PR? That should be safe to do without depending on the changes in this PR.

**Review by kroening — APPROVED** [review]

**Comment by kroening** [comment]
You could also change `typet void_type();` in `c_types.h` to return `empty_typet`.

**Comment by majakusber** [comment]
@tautschnig I made the companion PR here: https://github.com/diffblue/test-gen/pull/2999 Note that I would like to merge my PR before this one, to avoid clash.

**Comment by tautschnig** [comment]
@svorenova Thank you very much - yes, please do let me know when it's merged, I'd like to keep the bot (and thus TG) happy at all times to avoid spurious messages being posted.

**Comment by tautschnig** [comment]
> You could also change `typet void_type();` in `c_types.h` to return `empty_typet`.

Done, which made some further room for improvement apparent. I hope the additional 5 commits are ok to be in this PR.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 8a28d163b08a491cac2b06b3545c9f59b16f208c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99961187
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by majakusber** [comment]
I updated the companion PR https://github.com/diffblue/test-gen/pull/2999

**Comment by majakusber** [comment]
@tautschnig The companion PR is merged now, you can merge this :+1:

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 32f4aa50a0a99309a31186a84bd288b73a982a4f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100076282

**Comment by NlightNFotis** [comment]
Now this has been merged, but I have a question: Wouldn't it be better instead of completely removing `void_typet` to instead alias it to `empty_typet`? 

That would make the API better and the semantics of some code much closer to the semantics of the languages they supposedly model (like C code). Because as far I understand the `empty type` is a concept present on functional languages. C descendants use `void` for the the same thing?

**Comment by tautschnig** [comment]
I had pondered to introduce a typedef, but my main concern was that there was no consistent use of one or the other. I have tried to clean this up, and now ended up (trying to) make consistent use of `java_void_type()` in the Java front-end, and `void_type()` in the C and C++ front-ends. I think that's fairly clean within the language front-ends now. That leaves as concern that those still return an `empty_typet`, but I think that's actually good, because we are converting towards goto programs, not either of the languages. If anything, we've probably been too close to C in the middle-end I think.

**Pull request merged**
