### PR TITLE
test for function pointer removal

### PR DESCRIPTION
**Pull request by kroening**
This tests the interplay between the analysis in get_called_functions and remove_function_pointers.

### CODE REVIEW

**Comment by martin-cs** [comment]
@thk123 You know how you're a bit of an expert on function pointer removal, right...

**Review by thk123 — COMMENTED** [review]
I don't really know what this is testing. 

Not clear to me why `my_f` assigns `my_ptr` to itself, or why there is an asm instruction, is it relevant to the test? 

Perhaps a more descriptive name or comment in test.desc would help? 

Also, depending on what this is supposed to test, it might be trivially true as `my_f` is not referenced by anything from `main`. See [regression/goto-analyzer/precise-const-fp-const-fp/main.c](https://github.com/diffblue/cbmc/blob/develop/regression/goto-analyzer/precise-const-fp-const-fp/main.c) for how I have ensured the functions aren't eliminated by simple reachable analysis.

**Review by peterschrammel — COMMENTED** [review]
Currently fails: https://travis-ci.org/diffblue/cbmc/jobs/275407122#L2337 
Set to KNOWNBUG if fixed in a separated PR

**Comment by NlightNFotis** [comment]
I am closing this PR, as it appears to be in a stale state, with CI failing and concerns about the value added.

Please, feel free to reopen the PR if you believe this is adding value and would like to rebase it on develop and get it merged.

**Pull request closed without merging**
