### PR TITLE
the jbmc tests now work on Windows

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 6b0d2455d9a3b51f203d3321cc01f46f15201b5a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77773071

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: feb6c7d6229e8976379db26cae8b70994a05cee2).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77774589

**Review by smowton — APPROVED** [review]
Change seems fine (though CI disagrees :))

**Review by tautschnig — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: b3002fa17406929dc7fc448a13007d474a454057).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78123379

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 119883d06ec1da5b90c28cb84af5e85010748947).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79209137

**Review by peterschrammel — APPROVED** [review]

**Comment by tautschnig** [comment]
@kroening @peterschrammel Any idea why none of the Windows builds (neither codebuild nor appveyor) is being run? Leaving the do-not-merge label in place until that's resolved.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: f795ef9bac74276fb58615613237a56ba5fbc01b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79244510

**Comment by peterschrammel** [comment]
> Any idea why none of the Windows builds (neither codebuild nor appveyor) is being run?

Mysterious. I've just rebased https://github.com/diffblue/cbmc/pull/2576 and triggered the windows CodeBuild there. (Appveyor is currently turned off)

**Pull request merged**
