### PR TITLE
Add storage of final modifier status of java classes in `java_class_typet`.

### PR DESCRIPTION
**Pull request by thomasspriggs**
Add storage of final modifier status of java classes in `java_class_typet`.

### CODE REVIEW

**Review by mgudemann — APPROVED** [review]
LGTM, unit test would be nice, but not really necessary here

**Review by thk123 — CHANGES_REQUESTED** [review]
This does need a unit test as I believe you have missed updating the (annoying) `java_bytecode_parsetree::classt::swap` method and this flag will get lost. 

Why do we need this btw? Personally don't have an issue with our `classt` more closely mirroring the bytecode but I assume this isn't the only missing field?

**Comment by thomasspriggs** [comment]
The work in this PR is a prerequisite for fixing [TG-1960]. Yes, I agree that it needs a unit test.

**Comment by peterschrammel** [comment]
@thomasspriggs, can you please finish this up?

**Comment by kroening** [comment]
This is ready to go once the swap() is fixed. We could also evaluate whether the swap is still needed, given that rvalue references now exist.

**Comment by thomasspriggs** [comment]
I have added the fix to the `swap` method, but this is still missing a unit test.

**Review by thk123 — APPROVED** [review]
Raised a ticket to add the unit tests when we have time: TG-3535

**Comment by thomasspriggs** [comment]
I have raised https://github.com/diffblue/cbmc/pull/2178 for the removal of the `swap` method.

**Pull request merged**
