### PR TITLE
[CI] Remove codebuild configuration.

### PR DESCRIPTION
**Pull request by NlightNFotis**
Since we have now implemented most jobs on github
actions, it makes sense to depend on that and remove
codebuild, as this has multiple benefits:

1) It makes it easier for project contributors to
   see the result of the builds of their PRs (in
   codebuild, it was very complicated to access
   the build results, and as a matter of fact we
   had special instructions for accessing them).
2) It removes the maintenance burden from us to maintain
   multiple CI systems, especially since there are not
   obvious benefits to doing so.
3) We no longer need to have so many jobs needed for one
   PR, which used to create multiple problems, as it was
   the case that some jobs would always fail in some way
   (like fail to be initialised).

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by martin-cs — APPROVED** [review]
Assuming that we have all of the same platform / configurations for building in the github CI as codebuild -- sure!  I know this wasn't the case when moving from Travis to codebuild.

**Comment by martin-cs** [comment]
That said -- why is codebuild being run on this PR?

**Comment by NlightNFotis** [comment]
@martin-cs It's not being run - it's being triggered because it's hooked into the repository's settings, but because of the config being removed, it's hanged.

I have asked @peterschrammel to review it, and if he thinks it's good, to review the required status from these checks, so they are no longer there.

This isn't new - same thing happened when we removed travis :)

**Review by peterschrammel — COMMENTED** [review]
Which are the mandatory jobs now?

**Comment by thomasspriggs** [comment]
The codebuild jobs include a Linux + clang compiler build, which as far as I can see hasn't been ported to git hub actions yet. I think there may be value in porting this over, before we abolish code build. A Linux + clang compiler job may be useful for isolating whether build failures on mac are due to using the Clang compiler or due to the standard library versions they use. In addition, the error messages from Clang can sometimes be easier to read than the ones from gcc.

**Comment by NlightNFotis** [comment]
Okay, #5559 was now created to introduce the missing build to github actions, so we now all previous codebuild jobs should be ported to github actions.

**Review by tautschnig — CHANGES_REQUESTED** [review]
Maybe I'm completely wrong here, but wouldn't we lose the Codecov integration? I'm not sure which of the two buildspec-linux-*-gcc-cov.yml is currently taking care of this, but they might still be needed?

**Comment by NlightNFotis** [comment]
@tautschnig Hi Michael, can you take another look at this?

We have ported almost all of the jobs to GitHub Actions now (the ones missing are ones based on outdated configuration, like clang-3.8, and some windows setups like building under `msbuild`) and we have coverage and extra macOS jobs now.

Does this look more fit for purpose now?

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
