### PR TITLE
Cleanup the API of bv_utilst::adder

### PR DESCRIPTION
**Pull request by tautschnig**
Don't make every caller create an uninitialised literal.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
There should be two APIs:
1) One that just adds the constraints; the operands are created by the caller.
2) One that creates new literals for the sum and the carry out. Ideally, these ought to be returned as a pair.

**Comment by kroening** [comment]
As a side note, the second API should be able to constant-propagate.

**Comment by martin-cs** [comment]
Agree with @kroening , we need both the functional (create new literals) and the relational (just the constraints) encodings.

**Comment by tautschnig** [comment]
> There should be two APIs:
> 
>     1. One that just adds the constraints; the operands are created by the caller.
> 
>     2. One that creates new literals for the sum and the carry out. Ideally, these ought to be returned as a pair.

I have now implemented the second API, but found no need for the first one.

**Review by martin-cs — APPROVED** [review]

**Pull request merged**
