### PR TITLE
Proposal: introduce a goto-checker module [blocks: #2212, #3268]

### PR DESCRIPTION
**Pull request by peterschrammel**
This module will contain the interfaces for all our engines that can check assertions
so that they can be used interchangeably in driver programs.

Next steps:
1. Refactor property_checker and safety_checker to provide the interfaces that I need.
2. Split bmct into the 9 different functionalities that it currently provides.
3. Refactor TG's bmc_cover to be able to use different engines
4. Refactor the incremental BMC patch

Relates to #15.

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
This may be a great idea, but it's finally time to add comments to those interfaces. We've now got a directory with files void of comments. This is unusable by anyone other than those who conceived it.

**Comment by smowton** [comment]
Assigning @tautschnig as I think this wants re-review from him

**Comment by peterschrammel** [comment]
The actual PR stack is coming in stacking onto https://github.com/diffblue/cbmc/pull/3557.

I'll close this PR (2883) when then entire stack has been PRed.

**Comment by tautschnig** [comment]
@peterschrammel Has the time come to close this PR?

**Pull request closed without merging**
