### PR TITLE
Revert the change to the use of unbounded arrays

### PR DESCRIPTION
**Pull request by martin-cs**
This was introduced in #6194 but reported as breaking in #6230.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by martin-cs** [comment]
@SaswatPadhi it would be great if you could let me know if this fixes your issue.

**Review by TGWDB — APPROVED** [review]
Happy to approve (specially for faster turn around). Any chance of a regression test?

**Comment by martin-cs** [comment]
@TGWDB I would *love* a regression test and was hoping that @SaswatPadhi might be able to provide one.

**Comment by SaswatPadhi** [comment]
Thanks for the fix, @martin-cs.

We noticed this on a large s2n proof harness, but let me try to reduce it to a small regression test. I would look into large / dynamically allocated arrays, as you suggested.

**Comment by martin-cs** [comment]
Thanks @SaswatPadhi

**Comment by SaswatPadhi** [comment]
This is the most I could shrink it to:

```c
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>

static const uint16_t extensions[] = { 0, 1, 2, 3, 4, 5 };

#define COUNT (sizeof(extensions) / sizeof(extensions[0]))

typedef struct {
  uint8_t *data;
  uint32_t size;
  uint32_t allocated;
  unsigned growable :1;
} ext;

struct context {
  ext exts[COUNT];
};

struct conn {
  void *test;
  struct context ctx;
};

int main() {
  struct conn *s = malloc(sizeof(*s));
  if(s != NULL) s->test = NULL;
}
```

If I shrink the `ext` struct further, the invariant violation disappears, so may be there is some issue with alignment? Not sure ...

**Comment by martin-cs** [comment]
I have tried this example with the latest develop (  06c563a76589ed00cc372d68e2819880537977b2 ) and it doesn't crash.  Can you double check and say something about the environment?

**Comment by TGWDB** [comment]
I also tested the example on `cbmc` release `5.33.0`, `5.34.0`, and a branch with the fix and had no crashes for any of them (on Ubuntu 20.04 LTS). That said, when I was working on original PR that had this error, there were some behaviours that appeared to be system specific w.r.t. array sizes.

**Comment by SaswatPadhi** [comment]
Sorry, I should have mentioned the full commandline:

```
cbmc --malloc-may-fail --malloc-fail-null --pointer-check test.c
```

**Comment by martin-cs** [comment]
Ah, yes, that does it! Thanks @SaswatPadhi

**Comment by feliperodri** [comment]
Any updates on that PR? @martin-cs @kroening

**Comment by martin-cs** [comment]
@feliperodri I am working on the test case that @SaswatPadhi sent and will add it ASAP.

**Review by kroening — APPROVED** [review]

**Pull request merged**
