### PR TITLE
Use nullptr to represent null pointers

### PR DESCRIPTION
**Pull request by reuk**

### CODE REVIEW

**Comment by peterschrammel** [comment]
LGTM, @reuk, but I'd prefer to merge this clean-up into master first and then clean up what remains to be done in test-gen-support.

**Comment by peterschrammel** [comment]
@reuk, please rebase

**Comment by reuk** [comment]
Should I rebase this, or should I close this and redo the work on master?

**Comment by tautschnig** [comment]
Can this please re-target master? I don't think pull requests that are purely cleanup do need fast-tracking via test-gen-support.

**Comment by kroening** [comment]
Yes, agree with Michael, please rebase to master.

**Comment by reuk** [comment]
Closing in favour of #1159

**Pull request closed without merging**
