### PR TITLE
[TG-3368] Make annotations comments in irep_idt

### PR DESCRIPTION
**Pull request by romainbrenguier**
This avoids failing type comparison when one contains annotations and not
the other.

### CODE REVIEW

**Comment by NathanJPhillips** [comment]
Can you link the TG bump?

**Comment by romainbrenguier** [comment]
@NathanJPhillips unfortunately we can't bump at the moment because the current cbmc/develop breaks some tests, but I will do a TG bump PR when this is fixed.

**Comment by thk123** [comment]
I agree the PR does what is says - could you provide a reason why? Annotations are potentially available at run time so arguably two types are different if they have different annotations. I also can't imagine a correct scenario when two types differ only by annotation so this looks like it might hide an underlying bug.

**Comment by romainbrenguier** [comment]
@thk123 
the example I have is a class with a field like:
```
  @NotEmpty
  private double price;
```
then assigning `price` to a `double` variable causes the solver to abort because of different types.
Yes this can hide bugs in annotation but since they haven't been much tested (I only see one test for annotations) it's better than breaking things that were working before.
I think @NathanJPhillips is going to do some deeper corrections on annotations.

**Comment by tautschnig** [comment]
@romainbrenguier Could you please add that test? To me, not being a Java expert, it seems perfectly legitimate that the right-hand side would not carry any annotations in the example that you presented.

**Comment by thk123** [comment]
@romainbrenguier Ah of course yes that makes sense. A test demonstrating that would of course be great.

**Comment by romainbrenguier** [comment]
@tautschnig @thk123 I added a test for which jbmc currently has a failed invariant check, but works correctly with this fix.

**Review by thk123 — APPROVED** [review]

**Comment by romainbrenguier** [comment]
@NathanJPhillips TG bump https://github.com/diffblue/test-gen/pull/1775

**Review by LAJW — APPROVED** [review]
LGTM

**Pull request merged**
