### PR TITLE
[TG-5206] Parse ACC_VARARGS method flag from bytecode

### PR DESCRIPTION
**Pull request by majakusber**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

Up until now we have not been parsing the flag of methods that take variadic arguments. This PR saves the flag in the method symbol in the symbol table.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 1a00d90a9866ee446a4783280ddaacfcf0dce16c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85591513

**Comment by allredj** [comment]
Add unit test as in /home/joel/test-gen/lib/cbmc/jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_method.cpp

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 1d993d25b39b6a8a819c665f61701673a049deee).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85885426

**Comment by antlechner** [comment]
@allredj Unit tests added, can you please re-review?

**Review by allredj — APPROVED** [review]
LGTM

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: bc91b8cbb50cfc0e5a57bb85a1f8760d2e3179b8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85899555
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: bed77fd247e2a3b516433a635d792e351a99a960).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85902066

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: b6589dd54b888cd3724d8c0c0d077a00642a6163).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85991941

**Pull request merged**
