### PR TITLE
Object factory: ensure generated assignments are exactly type-consistent [blocks: #3966]

### PR DESCRIPTION
**Pull request by smowton**

### CODE REVIEW

**Comment by tautschnig** [comment]
Just asking before embarking on the review: does this supersede one or both of #3743, #3744?

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
Just noting here that these fixes are actually required to make #3966 mergeable (as otherwise a test fails).

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 814426b97f3518f4608be49f8a8d3896136a5622).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100219870

**Review by kroening — APPROVED** [review]

**Comment by smowton** [comment]
@tautschnig looks like neither one is superseded, they do independent cleanups around the same area.

**Comment by tautschnig** [comment]
Thanks @smowton - @kroening, maybe now is a good time to revive them?

**Review by thk123 — COMMENTED** [review]
Changes LGTM - could it get a very quick manual TG bump (I'm assuming @smowton will take care of this, or will let me know if not)

**Comment by thk123** [comment]
Manual bump: diffblue/test-gen#3027 (awaiting CI)

**Review by thk123 — APPROVED** [review]
Manual bump passed with no changes as Chris promised, so this is good to go :+1:

**Pull request merged**
