### PR TITLE
switch codebuild from clang 7 to clang 8

### PR DESCRIPTION
**Pull request by kroening**
This is to catch problems as in #4744.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- n/a Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- n/a My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
As noted on #4744, the Clang 8 build appears to be passing without changes. @kroening can you confirm that Clang 8 is genuinely being used in the build (I don't have access to the Clang 8 build log).

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4a83428676e082348093eeb2977ea41e1f77f90d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114238943

**Comment by kroening** [comment]
Yes, confirmed, cbmc-linux-clang builds with clang 8!

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 720e783a1748db08055e3369f0eb7878952a0c32).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114384475
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: d8cb021689b1845ab0cbaf9e930566618df3590f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114386110
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c3f264622d810cc18ea695d808813869e65cebf7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114388107

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f4451b50a9e386e60e1e376a24c9ef01604bbece).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114459416

**Review by peterschrammel — APPROVED** [review]
CI passed

**Pull request merged**
