### PR TITLE
Do not use base_type_eq with non-code types [blocks: #4056]

### PR DESCRIPTION
**Pull request by tautschnig**
We consistently use tag types, and two expressions are now base_type_eq if, and
only if, they have types that compare equal.

This PR should unblock various PRs building on #4056 by skipping the breaking changes that relate to linking.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by kroening — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 91ce31440a1033530ea442b230f3b0441b4d755c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102973206
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by smowton — APPROVED** [review]
Note however that in order not to have terrible performance consequences for Java we must first merge simplify-after-deref or equivalent code, because this exposes the difference between e.g. `List`, `List<T>` and `List<Integer>`, which value-set-deref will express using a byte-extract op, and which the simplifier can remove.

**Comment by tautschnig** [comment]
@smowton Would you be able to contribute some performance comparison data that shows how important simplify-after-deref is?

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 1f3d104c13d18a2b7d28260c2dafcdb04164f125).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103074413
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Comment by smowton** [comment]
Benchmarks posted at #3725

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: cb67b9b4da678fd9775a206fb2772febf13185d1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103460609

**Pull request merged**
