### PR TITLE
TG-977 Assert denominator non-zero when Java runtime exceptions are disabled

### PR DESCRIPTION
**Pull request by smowton**
All the other Java-instrument checks are presented as exceptions when enabled or
as assertions when exceptions are disabled; ArithmeticException is uniquely not checked.
This adds an assertion to match the other cases.

### CODE REVIEW

**Review by mgudemann — APPROVED** [review]
LGTM, any idea why this was not done in the first place when `--java-throw-runtime-exceptions` is not set?

**Comment by smowton** [comment]
No idea

**Review by thk123 — COMMENTED** [review]
Change looks good - I think a submodule bump would be a good idea on this if you've got a min.

**Comment by smowton** [comment]
Done: https://github.com/diffblue/test-gen/pull/1174

**Review by peterschrammel — APPROVED** [review]
Ok to get this fixed. On a side note: I think that --java-runtime-exceptions should be the default behaviour for JBMC because the thrown exceptions are part of the java behaviour. Using CPROVER assertions instead of throwing exceptions is only useful to detect primary causes of runtime exceptions. The exceptions, however, might be caught. In my opinion only throwables that escape the entry point should be considered property violations by default.

**Comment by thk123** [comment]
@peterschrammel (I agree exceptions should be on, but) My understanding is @jgwilson42 doesn't want it on by default due to limitations in the platform but perhaps James you'd like to weigh in?

**Comment by jgwilson42** [comment]
@thk123 @peterschrammel I will reply via slack.

**Comment by smowton** [comment]
It could be on-by-default in jbmc / test-gen if platform had an option to turn it *off*?

**Comment by smowton** [comment]
Ignore the `/push` build, accidental push to diffblue/cbmc instead of smowton/cbmc

**Review by thk123 — APPROVED** [review]

**Pull request merged**
