### PR TITLE
Move --cover tests to cbmc-cover

### PR DESCRIPTION
**Pull request by peterschrammel**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d8430b84e0ccf016968d201fe6e1492754dd4596).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97472270

**Comment by tautschnig** [comment]
Why?

**Comment by peterschrammel** [comment]
Because there is no point having a `cbmc-cover` directory if cover tests are scattered in other directories as well.

**Review by tautschnig — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 8c4e097bbb0e8b98fbbc9b17c7747c167a1a6d11).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97527772

**Pull request merged**
