### PR TITLE
can_cast_expr<is_dynamic_object_exprt>: fix copy&paste error

### PR DESCRIPTION
**Pull request by tautschnig**
This needs to check for the correct id.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
@thomasspriggs FYI

**Review by kroening — APPROVED** [review]

**Comment by thomasspriggs** [comment]
> @thomasspriggs FYI

Thanks for letting me know. I should really write unit tests for these when I add them.

**Comment by tautschnig** [comment]
> > @thomasspriggs FYI
> 
> Thanks for letting me know. I should really write unit tests for these when I add them.

There seems to be code using it in the SMT back-end, so I'm actually more worried about test coverage for those bits.

**Comment by thomasspriggs** [comment]
> > > @thomasspriggs FYI
> > 
> > 
> > Thanks for letting me know. I should really write unit tests for these when I add them.
> 
> There seems to be code using it in the SMT back-end, so I'm actually more worried about test coverage for those bits.


The single usage of it in `src/solvers/smt2_incremental/convert_expr_to_smt.cpp` will route to an `UNIMPLEMENTED_FEATURE` macro. Currently the difference with / without the fix in this PR is which `UNIMPLEMENTED_FEATURE` macro this routes to. So the fix in this PR has saved us some time when it comes to implementing / debugging / testing the conversion of this type of expression. Thanks again.

**Pull request merged**
