### PR TITLE
Fix broken links in contract documentation

### PR DESCRIPTION
**Pull request by monal**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by feliperodri — APPROVED** [review]

**Review by tautschnig — CHANGES_REQUESTED** [review]
No, this isn't the right approach (at the moment) I'm afraid. It might make things work when looking at the source code in github.com, but the CPROVER Manual lives at https://www.cprover.org/cprover-manual/, and the URLs are written in a way to make this render on that page.

That said, there are some issues that needed addressing by @kroening , but over the next hours this should be fixed.

**Comment by feliperodri** [comment]
@tautschnig @kroening are there any pending issues on the [CPROVER website](https://www.cprover.org/cprover-manual/) that block us from using this PR? I still find a few broken links in the Function Contracts section, but it's unclear whether the the problem is on the README files or on the URLs side.

**Comment by jimgrundy** [comment]
I think we should move away from the [CPROVER website](https://www.cprover.org/cprover-manual/) for the CBMC documentation hosting and follow something closer to the Kani model of github hosted documentation: https://model-checking.github.io/kani/

**Comment by feliperodri** [comment]
Closing this for now, as we are working on a more general solution for documentation. See https://github.com/diffblue/cbmc/issues/7006 for more details.

**Pull request closed without merging**
