### PR TITLE
[TG-1938] CI lazy methods: re-explore array types with different element types

### PR DESCRIPTION
**Pull request by smowton**
Previously upon encountering a second array this would truncate the search for
available types, but since they may have different element types this could lead
to missing the availability of one or more of the element classes. Now we search
array::reference every time we encounter it.

Would someone (@antlechner?) mind adding a test case for this?

### CODE REVIEW

**Review by thk123 — COMMENTED** [review]
Change looks good, of course needs a test, if @antlechner already has one ready to go that'd be great.

**Comment by antlechner** [comment]
Test is in the folder `cbmc/regression/cbmc-java/lazyloading_multiple_array_types` on this branch: https://github.com/antlechner/cbmc/tree/antonia/tests-for-TG1938
The test fails on cbmc/develop and passes after applying the changes from this PR.
@smowton Can you add the test to this PR, or would it be easier if I made a separate PR that depends on this one (not quite sure what the policy is on that)?

**Comment by smowton** [comment]
@thk123 tests added per @antlechner above!

**Review by thk123 — APPROVED** [review]

**Comment by smowton** [comment]
@mgudemann could you provide the second review here?

**Review by mgudemann — APPROVED** [review]
LGTM, should the comment read "different arrays _can_ have different element types" ?

**Comment by smowton** [comment]
Yes, fixed and also made a TG bump; https://github.com/diffblue/test-gen/pull/1424

**Pull request merged**
