### PR TITLE
[TG-9218] Fix parsing of escaped characters in json

### PR DESCRIPTION
**Pull request by owen-mc-diffblue**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by romainbrenguier — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c5008b10c63fb88cc0d3a5ab71b4932da5c36e0c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125778100

**Comment by owen-mc-diffblue** [comment]
This needs a code owner review - @peterschrammel can you review it?

It also needs QA approval, so I've marked it "Do not merge" until it has that.

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 69aaaf079c08061d8c1c9565199f4f4b9bf3248e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/126043912

**Comment by yumibagge** [comment]
QA review [Passed]

https://diffblue.atlassian.net/browse/TG-9218?focusedCommentId=24268&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24268

Added unit / regression tests looks sufficient and pass :slightly_smiling_face:

**Pull request merged**
