### PR TITLE
Normalize whitespace

### PR DESCRIPTION
**Pull request by rjmunro**
* Remove trailing whitespace from all lines in .c, .cpp, and .h files
* Ensure all files end with a single newline, no more

Merging this may be a bad idea as it could cause lots of conflicts with other open branches, but it needs thinking about. Inspired by @tautschnig.

### CODE REVIEW

**Comment by kroening** [comment]
This appears to be breaking the minisat patch.

**Comment by tautschnig** [comment]
@rjmunro @kroening The change should be safe for all files except those in scripts, which need extra care.

**Comment by kroening** [comment]
@rjmunro Specifically, please remove the changes to scripts/glucose-syrup-patch and scripts/minisat-2.2.1-patch; I'll then merge this.

**Comment by rjmunro** [comment]
I've taken those patch files out. I only intended to to c, cpp and h files, but it looks like I didn't filter correctly as below are the numbers of files changed by extension:
```
 715 .c
   2 .cc
 694 .cpp
  18 .desc
 353 .h
   4 .inc
   7 .sh
```

**Comment by rjmunro** [comment]
If we merge this, we shoudl advise people to use `-Xignore-space-change` when merging or rebasing if they experience conflicts caused by it.

**Pull request merged**
