### PR TITLE
Add merge driver

### PR DESCRIPTION
**Pull request by reuk**
Adds a merge driver to facilitate doxygen conversions.

### CODE REVIEW

**Comment by reuk** [comment]
Info can be found [here](https://svn.cprover.org/wiki/doku.php?id=doxygen) - should I add this link to the file?

**Comment by tautschnig** [comment]
Thanks for the pointer, I was completely unaware this existed. Yes, please do add information so that even a year from now people can figure out what this is good for.

**Comment by reuk** [comment]
Added a small explanatory comment to the merge driver.

**Comment by martin-cs** [comment]
This looks good to me.

@tautschnig : for context, I asked @reuk / @thk123 to make a version of this public as I've had a number of complaints from external users and partners about the difficulty of updating branches.  The documentation for it is here : https://svn.cprover.org/wiki/doku.php?id=doxygen (as I think @reuk said) and it would be good if:

1. This could be merged before 5.8.
2. The link could be included in the release e-mail / notes.

@kroening please can you make this happen?

**Comment by tautschnig** [comment]
Thanks a lot for adding comments. I would appreciate if the commit message could be made meaningful as well.

**Pull request merged**
