### PR TITLE
Ensure new regression folders work with Make *and* CMake

### PR DESCRIPTION
**Pull request by reuk**
`goto-cc` has a different name and different behaviour on windows. Rather than modifying the regression `chain.sh` scripts before running them, it's better to detect the platform and to use plain old conditionals to change the script behaviour. Suggest @thk123 and @peterschrammel to review.

### CODE REVIEW

**Review by thk123 — APPROVED** [review]
Sorry - thanks for cleaning this up. In general, new regression folders want to go in to that CMakeLists.txt right?

**Comment by reuk** [comment]
Yeah, that's right.

**Review by peterschrammel — APPROVED** [review]

**Comment by reuk** [comment]
@thk123 @peterschrammel Can someone merge this please?

**Comment by reuk** [comment]
Thanks

**Pull request merged**
