### PR TITLE
add documentation of default for --max-nondet-array-length, see #8428

### PR DESCRIPTION
**Pull request by lks9**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- (only documentation is changed)
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Comment by lks9** [comment]
Thanks for approving the changes but apparently someone still needs to approve the workflow to get this merged. Would be great!
Fixes #8428

**Comment by peterschrammel** [comment]
@lks9, I think this needs a rebase.

**Comment by peterschrammel** [comment]
Oups, this was on auto-merge. @lks9, next time for rebasing please use `git pull --rebase` to get rid of the merge commit.

**Comment by lks9** [comment]
Sorry, I will do it with rebase next time!

**Pull request merged**
