### PR TITLE
Remove function from source_locationt [depends-on: #4131]

### PR DESCRIPTION
**Pull request by tautschnig**
A source location is a place in a text file, it does not have syntactic
information.

This is work in progress, known to require quite a bit more work to re-introduce the information about functions where needed. The current state also includes some additional hacks to detect where problems will arise.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by smowton** [comment]
Personally this seems like a step backwards -- a source location doesn't need to be a (row, col) coordinate, it seems appropriate for it to identify other source-code-level properties of a piece of `codet` or goto_programt::instructiont` data. What's the motivation for this?

**Comment by tautschnig** [comment]
We should discuss this with @kroening. Certainly it seems that at the moment there is considerable abuse of this information in the code base: anything stored in the source location should only be used for the purpose of reporting back to the user, and not affect program semantics. So maybe we keep it, but just clean up all usage.

**Comment by chrisr-diffblue** [comment]
Is there scope to just modify the API (and then hence, the corresponding cleanup) so that it's API becomes 'store or output' only ?

**Comment by tautschnig** [comment]
> Is there scope to just modify the API (and then hence, the corresponding cleanup) so that it's API becomes 'store or output' only ?

Sounds like a good idea to me. Yet I don't recall whether in a discussion with @kroening we had more reasons for the change, it's a while ago. So, @kroening, input much appreciated.

**Comment by TGWDB** [comment]
Closing due to age (no further comment on PR content), please reopen with rebase on develop if you intent to continue this work.

**Pull request closed without merging**
