### PR TITLE
Avoid default no-ops, force derived classes to override [blocks: #2310]

### PR DESCRIPTION
**Pull request by tautschnig**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by kroening — APPROVED** [review]

**Comment by smowton** [comment]
This seems worse, what is the warning you're working around?

**Comment by tautschnig** [comment]
This was triggered by warnings about unused parameters, where in this case I though it would be more consistent to enforce overrides (as is already done for some of the other variants of `print`). So arguably I think it's better/more consistent as proposed, but indeed it might just be a matter of taste rather than well-grounded facts.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 6461481002197d4d54a6bdcd6a30f5c400e942ad).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90993958

**Review by owen-mc-diffblue — APPROVED** [review]

**Comment by smowton** [comment]
Personally I'd favour `(void)param1` etc in an intentional stub, or just remove the names of the args

**Comment by tautschnig** [comment]
Merging as we mainly seem to disagree on matters of taste. I surely won't block a later revert should we come up with facts backing up doing it in a different way.

**Pull request merged**
