### PR TITLE
Remove unused exception name from catch statement

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Review by chrisr-diffblue — APPROVED** [review]
I have the same general comment regarding the coding standard as I made on #2468 :-) But otherwise happy with the change.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: d140fd3bb42f1fa8ad4114d2155a46ac97b3d0d4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77251801
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Comment by tautschnig** [comment]
We should first get #2568 merged to have best practice codified.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: aa743b30160586e3c453632cecd3afbc39739fa9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78559447
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
