### PR TITLE
remove lhs_object from goto_trace_stept

### PR DESCRIPTION
**Pull request by kroening**
Not done yet; in particular, it's unclear to me how these GraphML witnesses look like.

### CODE REVIEW

**Comment by martin-cs** [comment]
FWIW I remember @tautschnig expressing ... disappointment ... with the GraphML witnesses.

**Comment by kroening** [comment]
The way the assignment is generated in error traces is now much simpler -- but it's non-obvious whether that simpler way is right or wrong.

**Comment by kroening** [comment]
Depends on #2824, which should get tweaked/reviewed/merged first.

**Comment by tautschnig** [comment]
Reading the code changes I'm finding it near impossible to assess whether what's happening is right or wrong (except that the graphml bit is now missing one sanity check). Can we have tests that actually inspect contents of the trace output, please?

**Comment by kroening** [comment]
Now added a test that checks the cases I could think of for console traces.
The output for graphml on that test is identical, and so is the output for the JSON UI.

The XML output changes as the 'value' elements are removed. I'll make that a separate commit.

**Review by tautschnig — APPROVED** [review]
I'll just trust that this test serves as specification of what we expect to find in a trace, and will therefore detect if something breaks. It may need to be extended over time, but it's a good start to have one.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 844a34c6b9740c98fb5937866f46f68d7f532c50).
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: df868b808f3598fe9f18b9b52489730c482f9999).
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Pull request merged**
