### PR TITLE
Use is_not_zero in simplifier

### PR DESCRIPTION
**Pull request by tautschnig**
Avoid duplicating its implementation to reduce code size and improve
maintainability.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: b98e818ccb952041020f501bcea97f7b7fb020c1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87949806

**Review by martin-cs — APPROVED** [review]
is_not_zero does do the right thing with floats, right?

**Comment by tautschnig** [comment]
> is_not_zero does do the right thing with floats, right?

It does have dedicated handling for that case, which amounts to the same that the code removed here was doing. But then I need to to defer back to you to determine whether that is the _right_ thing...

**Comment by martin-cs** [comment]
ISO 9899:2011, 6.3.1.2/1:

"When any scalar value is converted to _Bool, the result is 0 if the
value compares equal to 0; otherwise, the result is 1."

**Review by kroening — APPROVED** [review]

**Pull request merged**
