### PR TITLE
Remove java dependency in string solver

### PR DESCRIPTION
**Pull request by romainbrenguier**
This removes the dependencies on java_bytecode from the solver (see https://github.com/diffblue/cbmc/issues/1869)

### CODE REVIEW

**Review by peterschrammel — COMMENTED** [review]
Thanks. That's a good start!
What about the following:
* https://github.com/diffblue/cbmc/blob/develop/src/solvers/refinement/string_constraint_generator.h#L391
* https://github.com/diffblue/cbmc/blob/develop/src/solvers/refinement/string_constraint_generator_format.cpp#L421
* https://github.com/diffblue/cbmc/blob/develop/src/solvers/refinement/string_refinement.cpp#L1126

Are they generic enough to remove the word "java"?

**Comment by tautschnig** [comment]
The CMake failure highlights that there is a problem in `unit/CMakeLists.txt` that now needs to be addressed: because of the way the Linux linker works, `target_link_libraries` now needs to list `goto-programs` above `java_bytecode`. Though maybe the problem can also be solved differently:

```
$ git grep java_lang_object_type
goto-programs/remove_instanceof.cpp:  symbol_typet jlo=to_symbol_type(java_lang_object_type().subtype());
java_bytecode/java_types.cpp:reference_typet java_lang_object_type()
java_bytecode/java_types.h:reference_typet java_lang_object_type();
```
Having a single user of `java_lang_object_type()`, which in turn only picks out the `subtype()` is weird. Add to that that the single user is outside the `java_bytecode` folder.

**Review by martin-cs — APPROVED** [review]
Fine once the other issues have been addressed.

**Comment by kroening** [comment]
Cherry-picked two commits to make this move.

**Comment by peterschrammel** [comment]
@kroening, the develop build is broken now. 
I'm working on the java deps issue in https://github.com/diffblue/cbmc/pull/1935 / https://github.com/diffblue/cbmc/issues/1869. 
Cherry-picking without waiting for CI is not the way forward.

**Comment by romainbrenguier** [comment]
closing as the changes are in develop now

**Pull request closed without merging**
