### PR TITLE
Add CI compilation with clang++-3.8

### PR DESCRIPTION
**Pull request by romainbrenguier**
This is to check that changes do not break compilation using
clang++-3.8, as happened with
https://github.com/diffblue/cbmc/issues/4699

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [na] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [na] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
@kroening @romainbrenguier @peterschrammel Could this be moved into a new CodeBuild job instead to be properly run in parallel?

**Comment by peterschrammel** [comment]
> @kroening @romainbrenguier @peterschrammel Could this be moved into a new CodeBuild job instead to be properly run in parallel?

Yes, please move that into a new `buildspec-linux-clang-3.8.yml` file.

**Comment by romainbrenguier** [comment]
@peterschrammel @tautschnig I added a new buildspec-linux-clang-3.8.yml file but it looks like only buildspec.yml and buildspec-windows.yml are run on CI

**Comment by peterschrammel** [comment]
> only buildspec.yml and buildspec-windows.yml are run on CI

I'll add that to codebuild

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 7b1280fa77a8b42a9634b0488c3c6f73ca8028f1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/113845577

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 872198f021b0d88a21fa75c49b7a9b68ee534b22).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/113875367
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 88abf606020c89ba345d4635788b314d12f9114e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/113876083

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 7ef487a7f00ab8becec2ad2a8caa9bd04e51ee19).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114072123

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 45fc62161c276121b087497c1f0e6f1ee7a468a1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114079433

**Review by kroening — APPROVED** [review]

**Pull request merged**
