### PR TITLE
Use using instead of typedef

### PR DESCRIPTION
**Pull request by reuk**

### CODE REVIEW

**Comment by tautschnig** [comment]
Why?

**Comment by reuk** [comment]
Greater uniformity (works for template types) and more readable (result on lhs like everywhere else in the language).

**Comment by tautschnig** [comment]
In future, please do consider https://chris.beams.io/posts/git-commit/ to avoid this "Why" question.

**Review by owen-mc-diffblue — CHANGES_REQUESTED** [review]
You should update the coding standards as well - it currently says to prefer `typedef` over `using`

**Review by tautschnig — CHANGES_REQUESTED** [review]
In line with some recent discussions: can we please just refrain from doing this altogether? Thanks. @kroening @peterschrammel please override if you think I'm overreacting here.

**Comment by reuk** [comment]
Fair enough, but could we amend the coding standard to move towards using `using` in future patches?

**Comment by tautschnig** [comment]
> Fair enough, but could we amend the coding standard to move towards using `using` in future patches?

Sounds reasonable to me based on your earlier explanation, although I have no particularly strong opinion either way.

**Comment by tautschnig** [comment]
If we go the proposed route, would you mind not only adding this to the coding standard, but also contributing a simple check in `cpplint` that alarms on any newly introduced/not updated `typedef`?

**Pull request closed without merging**
