### PR TITLE
introduce INCOMPLETE_GOTO and turn guarded goto into a stateless pass

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Comment by smowton** [comment]
Why a new instruction type instead of just defining "GOTO with zero targets" as the incomplete GOTO?

**Comment by kroening** [comment]
This way, we can have the invariant that GOTOs have one target always. This is assumed very broadly, and we got precondition failures as a result of that getting violated.

**Comment by smowton** [comment]
Hmmm! All that makes me wonder is it's not really an instruction -- it doesn't really have semantics ("jumps to anywhere"?) I don't claim to have a cleaner solution though; list iterators are tricky things to manipulate. If the GOTO edges were plain old pointers then we could just allocate a labelled SKIP to be the target if it doesn't exist yet (and bring it in when we encounter the label); I guess it's impractical to do that with goto_programt::targett though?

**Comment by kroening** [comment]
"labeled skip" is what I had done earlier, but got reverted.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: e440a25e86eae469a1b421a07a0b09d24ce9fdd9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/76574789

**Comment by peterschrammel** [comment]
TG bump created.

**Review by peterschrammel — APPROVED** [review]
TG bump is passing. The AWS failure seems spurious.

**Pull request merged**
