### PR TITLE
Refactor graphml witnesses

### PR DESCRIPTION
**Pull request by peterschrammel**
This refactors the graphml witness generation to facilitate the generation of correctness witnesses (another PR will follow)

### CODE REVIEW

**Comment by tautschnig** [comment]
Looks good to me. I've added a test case as a pull request in your repository - you may want to add that to this pull request.

**Comment by peterschrammel** [comment]
Rebased. It can be merged now.

**Comment by kroening** [comment]
Lots of trailing whitespace?

**Comment by peterschrammel** [comment]
Whitespace cleaned up.

**Pull request merged**
