### PR TITLE
Fix help output of --generate-function-body-options

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by peterschrammel — COMMENTED** [review]
Better remove the trailing spaces and use `clang-format on/off`?

**Comment by tautschnig** [comment]
@peterschrammel Using `clang-format off/on` is certainly an idea, but only solves half of the problem: those lines would also be too long, hence require silencing the linter as well. Let me know if you think that would be better (I'm myself not entirely confident about the readability of the code right now).

**Comment by peterschrammel** [comment]
I'm suggesting this for uniformity reasons mainly. This solution has been applied in all other places where the same issue occurs. I'm not claiming it is the _ideal_ way of doing it.

**Comment by tautschnig** [comment]
@peterschrammel Formatting updated.

**Comment by peterschrammel** [comment]
Nitpick: remove all but one whitespaces before backslash

**Comment by tautschnig** [comment]
> Nitpick: remove all but one whitespaces before backslash

Done, in a second commit (as that's all those lines that I hadn't touched in my earlier commit).

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
