### PR TITLE
coding guidelines: prefer using instead of typedef

### PR DESCRIPTION
**Pull request by kroening**
Functionally equivalent, but more modern.  This is also what Google's C++
Style Guide says.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
I am ok with this as long as we introduce it gradually rather than doing some rewrite of the codebase.

**Review by chrisr-diffblue — APPROVED** [review]
Happy with the update to the coding standard, and also echo Michaels comment that hopefully this won't encourage someone to do a giant re-rewrite PR :-) 
Question: Should we update any clang-format/lint configs to match?

**Comment by tautschnig** [comment]
cpplint has a `CheckNamespaceOrUsing` rule, but it doesn't seem to be triggering much (we already have instances of `using` in the code base).

**Review by owen-mc-diffblue — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f2e8918810286c27d63db2e2a992a34749356d43).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90286010

**Pull request merged**
