### PR TITLE
Add `cmake` to the title of the VS with `cmake` CI job

### PR DESCRIPTION
**Pull request by thomasspriggs**
So that it is clearer when looking at the list of jobs that the difference between them is `cmake` versus `make`.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] ~~Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).~~ N/A
- [ ] ~~My commit message includes data points confirming performance improvements (if claimed).~~ None claimed
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by TGWDB — APPROVED** [review]

**Review by NlightNFotis — APPROVED** [review]

**Review by martin-cs — APPROVED** [review]

**Comment by TGWDB** [comment]
Did something go wrong with CI here?

**Comment by tautschnig** [comment]
> Did something go wrong with CI here?

I believe branch protection settings need amending. So whoever has access to those settings will need to take care of this.

**Comment by thomasspriggs** [comment]
@peterschrammel Could you look at the protection settings?

**Comment by peterschrammel** [comment]
Fixed

**Comment by peterschrammel** [comment]
Once it is merged I can cmake it required.

**Comment by tautschnig** [comment]
@peterschrammel Can you please update the configuration?

**Pull request merged**
