### PR TITLE
 Remove preprocessing that was using ID_cprover_string_concat_bool_func

### PR DESCRIPTION
**Pull request by romainbrenguier**
This builtin function is not handled by the solver, so preprocessing functions
and producing ID_cprover_string_concat_bool_func could only lead to
errors.
Instead we use models of these functions given in the java-models-library (updated with this PR to include these models).

3719036

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 371903697da18b01fae601e1cda288ada349ba6c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92000703

**Comment by romainbrenguier** [comment]
this was merged a bit too quickly because the corresponding submodule is not merged on master yet https://github.com/diffblue/java-models-library/pull/14 ; I should have added a "do not merge" label...

**Comment by allredj** [comment]
DO NOT DELETE THE REMAINING BRANCH!

**Comment by tautschnig** [comment]
Apologies for the overly eager merge. But also there is a problem with the workflow here. If all tests pass, including the TG bot, but still a merge is not indicated, then there isn't sufficient testing in place.

**Comment by romainbrenguier** [comment]
Here a new PR to update to the merge on master https://github.com/diffblue/cbmc/pull/3449

**Comment by tautschnig** [comment]
So the rules should be:
1) Don't create a PR if the submodule has not been merged yet or
2) If you want a PR, e.g., for testing purposes, mark it as "do not merge" until the submodule pointer is to a commit in master?

**Comment by romainbrenguier** [comment]
@tautschnig we do want PRs for the submodule to make sure we are not breaking CI on cbmc, so we should go for option 2

**Comment by romainbrenguier** [comment]
anyway, as long as the java-models-library branch is not deleted, nothing bad should happen

**Pull request merged**
