### PR TITLE
smt2_convt still assumes binary encoding

### PR DESCRIPTION
**Pull request by tautschnig**
Mark several cases as UNREACHABLE as apparently we either don't test or don't
use this code.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
Careful -- this is actually the other side: This code parses the response from the solver; it is unrelated to our IR. The question whether it gets exercised or not is primarily a function of what the solver we use generates. The solver is free to generate a response in any encoding.

**Comment by tautschnig** [comment]
> Careful -- this is actually the other side: This code parses the response from the solver; it is unrelated to our IR.

But this parser uses `from_integer` in those cases, which will generate hexadecimal strings. Passing those to `binary2integer` will not yield the expected result.

(The failing CI confirms that it isn't dead code.)

**Comment by kroening** [comment]
Yes; you mean "this should use `numeric_cast_v` instead of `binary2integer`.

**Comment by tautschnig** [comment]
Closing as #4074 patches these bits.

**Pull request closed without merging**
