### PR TITLE
Introduce String type for java when string-refinement is activated

### PR DESCRIPTION
**Pull request by romainbrenguier**
When string-refinement is enabled, we define what java.lang.String objects are supposed to contains, and we affect this kind of objects for string literals.
This requires the unicode PR #372 to be merged before.

### CODE REVIEW

**Comment by peterschrammel** [comment]
@romainbrenguier, is #372 made obsolete by the recent changes?

**Comment by romainbrenguier** [comment]
@peterschrammel https://github.com/diffblue/cbmc/pull/429 is still dependent on #372 as there are other functions implemented in #372 but I will try to make #429 independent of it  in case we decide it's better not to merge #372

**Comment by romainbrenguier** [comment]
This now depends on #541

**Comment by smowton** [comment]
Created replacement https://github.com/diffblue/cbmc/pull/559 per @forejtv's request in the meeting this morning.

**Pull request closed without merging**
