### PR TITLE
Byte update lowering: never create extractbits over unbounded arrays

### PR DESCRIPTION
**Pull request by tautschnig**
With nondet pointers we may end up doing byte updates of weird
combinations, including doing byte updates of an unbounded array using a
value the size of which is not a multiple of byte widths. This resulted
in extractbits expressions trying to extract bits from an unbounded
array, which bitvector flattening does not support.

This commit puts a byte extract layer in between, which will then take
the right approach to ultimately enable the extractbits to succeed.

Also, put PRECONDITIONs in place to ensure we don't create such
extractbits expressions in any other place in byte-operator lowering.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
I am not sure we want to give semantics to pointers to 1-bit bitvectors. Is there any variant of this that's more conventional?

**Comment by tautschnig** [comment]
> I am not sure we want to give semantics to pointers to 1-bit bitvectors. Is there any variant of this that's more conventional?

Any object the size of which is not a multiple of 8 will do. Would a 12-bit bitvector seem reasonable for a test?

**Comment by kroening** [comment]
> Any object the size of which is not a multiple of 8 will do. Would a 12-bit bitvector seem reasonable for a test?

Uh, no -- are we certain we want pointers like that?

**Comment by tautschnig** [comment]
> > Any object the size of which is not a multiple of 8 will do. Would a 12-bit bitvector seem reasonable for a test?
> 
> Uh, no -- are we certain we want pointers like that?

I don't know, so I've now changed the regression test to avoid any use of pointers or non-GCC C. It's now using a union.

**Comment by kroening** [comment]
> I don't know, so I've now changed the regression test to avoid any use of pointers or non-GCC C. It's now using a union.

Ok, looks more legit.

**Comment by tautschnig** [comment]
I am hoping that #6957 will address the CI failure.

**Review by peterschrammel — APPROVED** [review]
lgtm

**Pull request merged**
