### PR TITLE
Test to demonstate assert bug on alpine

### PR DESCRIPTION
**Pull request by thk123**
The user added assert in this test does not get coverage under alpine linux.

I can make this a KNOWNBUG but I thought it would be useful for it to run on CI so everyone can see the problem. The problem seems to be to do with how the assert is handled (possibly caused by musl having a different assert.h when compared to glibc).

**GOTO on Ubuntu Linux**

```
main /* main */
        // 0 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 7 function main
        signed int x;
        // 1 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 7 function main
        x = 0;
        // 2 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 8 function main
        ASSERT x == 0 // assertion x==0
        // 3 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 8 function main
        IF !(x == 0) THEN GOTO 1
        // 4 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 8 function main
        (void)0;
        // 5 no location
     1: SKIP
        // 6 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 9 function main
        main#return_value = 0;
        // 7 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 9 function main
        dead x;
        // 8 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 9 function main
        GOTO 2
        // 9 file regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 10 function main
     2: END_FUNCTION
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**GOTO on Alpine Linux**

```
main /* main */
        // 0 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 7 function main
        signed int x;
        // 1 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 7 function main
        x = 0;
        // 2 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 8 function main
        IF !(x == 0) THEN GOTO 1
        // 3 no location
        TRUE;
        // 4 no location
        GOTO 4
        // 5 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 8 function main
     1: ASSERT FALSE // assertion x==0
        // 6 no location
        IF !(0 != 0) THEN GOTO 2
        // 7 no location
        TRUE;
        // 8 no location
        GOTO 3
        // 9 no location
     2: FALSE;
        // 10 no location
     3: SKIP
        // 11 no location
     4: SKIP
        // 12 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 9 function main
        main#return_value = 0;
        // 13 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 9 function main
        dead x;
        // 14 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 9 function main
        GOTO 5
        // 15 file /cbmc/regression/goto-analyzer/sensitivity-test-constants-int/../sensitivity-test-common-files/int_sensitivity_tests.c line 10 function main
     5: END_FUNCTION
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by thk123** [comment]
This is also failing on Windows...

**Comment by tautschnig** [comment]
Could anyone post the pre-processing result obtained on Alpine Linux?

**Comment by thk123** [comment]
Sure, one moment. A quick discussion with @martin-cs suggested that replace `assert` with `__CPROVER_assert` since this will be transformed uniformly.

**Comment by thk123** [comment]
Here is the output for doing the following:

**test.c**

```C
#include <assert.h>
```

**Command on Alpine**

```bash
$ gcc -E test.c -o test_output.c
```

**test_output.c**

```C
# 1 "test.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "test.c"
# 1 "/usr/include/assert.h" 1 3 4
# 1 "/usr/include/features.h" 1 3 4
# 2 "/usr/include/assert.h" 2 3 4
# 19 "/usr/include/assert.h" 3 4

# 19 "/usr/include/assert.h" 3 4
_Noreturn void __assert_fail (const char *, const char *, int, const char *);
# 1 "test.c" 2
```

**Comment by tautschnig** [comment]
Would you mind extending your test.c to have some code using the `assert` macro? I think that is the culprit, rather than the function declarations. Thanks!

**Comment by thk123** [comment]
@tautschnig D'oh sorry, I've updated the comment with the information.

**Comment by tautschnig** [comment]
Thanks a lot for the preprocessing, this is very insightful.
See #755 for a related issue where I'd claim the code generated on Ubuntu is strange/has a redundant if. With Alpine Linux the use of `||` instead of `?:` appears to be causing coverage problems.

**Comment by tautschnig** [comment]
I have cherry-picked this test into #755.

**Comment by peterschrammel** [comment]
@thk123, I think we can close this one as it will be dealt with as part of #755.

**Comment by thk123** [comment]
Included in #974

**Comment by thk123** [comment]
Included in #974

**Pull request closed without merging**
