### PR TITLE
Make array element type be not a comment

### PR DESCRIPTION
**Pull request by thk123**
@smowton so amazingly - this hypothetical bug I mentioned, has in fact appeared a few days later. Do you think there are complications with this change (e.g. equals types being treated non-equally). I think not, an array of Foo is run time type incompatible with an an array of Bar. 

TG bump: diffblue/test-gen#2110

### CODE REVIEW

**Comment by smowton** [comment]
I think the problem will be unannotated arrays -- things where we know it's an array[reference] but not the specific type. I suspect we'll need to add some explicit typecasts for this (but perhaps we'll get lucky)

**Review by majakusber — APPROVED** [review]
This would be nice, I think it makes sense. I'm curious what CI will say. For unannotated types, can they really appear in goto/tests or is it that we should at all times know the runtime type and the fact that we do not sometimes is because of missing features/bugs?

**Comment by thk123** [comment]
@smowton you think that could arise from this change? Surely wouldn't have worked before either?

**Comment by smowton** [comment]
If there was a cast-less transition from array[ref] to array[String] (say) then before symex (and anything else caring to check) would have noted their types as equal -- now they might object. On the other hand any code using `==` to selectively apply a `typecast_exprt` will now start doing that, so the two may balance out.

**Comment by thk123** [comment]
Only CMake builds are failing, and specifically are failing on java-unit which _probably_ means java-unit aren't being run on Make builds.

**Comment by thk123** [comment]
@smowton Not entirely sure what you mean by "balance out" - if you can give me a java code example that shows what you mean I'm happy to bung in a regression test to verify. However, would quite like to get this merged ASAP so hypothetical I think are lower priority than the real one I have a test for in the TG bump. 

I will try and create a regression that exhibits this problem in cbmc - but would prefer to get this merged first.

**Comment by peterschrammel** [comment]
@thk123, java unit tests are run: https://github.com/diffblue/cbmc/blob/develop/.travis.yml#L365
https://github.com/diffblue/cbmc/blob/develop/buildspec.yml#L27

**Review by peterschrammel — APPROVED** [review]

**Comment by thk123** [comment]
@peterschrammel Interesting dunno then why only cmake builds were failing, but I think I've fixed the real problem anyway.

**Review by smowton — APPROVED** [review]
Happy enough to go for this and fix problems as we find them

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: b827ea4a945cbf9821a9201894720f2f646b67d8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/80527787
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Pull request merged**
