### PR TITLE
Regression test for remove_virtual_functions [TG-1404]

### PR DESCRIPTION
**Pull request by romainbrenguier**
This is based on https://github.com/diffblue/cbmc/pull/1731 to check that it fixes coverage issues with virtual functions TG-1404.

### CODE REVIEW

**Review by thk123 — COMMENTED** [review]
This looks fine, though I'm not sure what it tests that the test Matthias added doesn't. I think a more useful test would be a unit that explicitly checks the goto program after removing virtual functions to check the appropriate virtual functions are called in the appropriate contexts.

**Comment by martin-cs** [comment]
I'm not quite sure why I've got this as a "code owner" but ... yeah, adding regression tests is a good idea.

**Comment by romainbrenguier** [comment]
@martin-cs my PR was originally based on a PR by Matthias, when his PR got merged and I rebased mine on develop several commits appeared here marking you code owner, these commits disappeared when I changed the base branch to develop, but for some reason I still cannot remove the review requests.

**Review by martin-cs — APPROVED** [review]
Fine by me.

**Comment by romainbrenguier** [comment]
Unit tests were added with the PR that fixed this issue. And they check the problem is solved in a more reliable way than this test. So I'm going to close this PR.

**Pull request closed without merging**
