### PR TITLE
Remove base_type_eq

### PR DESCRIPTION
**Pull request by kroening**
These are no longer needed, as symbol_type is no longer in use.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
I'm worried that this will break linking, where semantic equality still matters as tag names can reasonably differ.

Also, I think it is necessary to implement this change as a collection of smaller commits to aid (very likely) future debugging. With a change this size it will be very difficult to revert, and bisecting to identify which of the hunks caused trouble is difficult. Furthermore we'd in the current set-up be completely blocked on the known issues in the Java front-end, even though in theory it ought to be possible to remove any use of (base_)type_eq from C/C++ front-ends.

**Comment by kroening** [comment]
Will do C/C++ first; the rest will need to sit for a few months.

**Comment by smowton** [comment]
@kroening @tautschnig I tried to rebase #4021 yesterday, but found that it continued to stumble on cases where `base_type_eq` and `operator==` disagreed about when types matched.

I took a look at why we can't merge this yet, and found the following fixups:
#4170: simple tag-vs-followed bug in `is_not_zero`
#4171: string preprocessor using expanded types
#4172: generic tests rely on `base_type_eq` to strip generic info or array member types

I also made #4173 with a value-set fix and some cosmetic / comment improvements that I think should be picked into this PR.

**Comment by smowton** [comment]
Status with all four of those merged: Java tests all pass, C tests all pass apart from `Float-div2`, `Float-div3`, `noop1`, all of which fail due to a disagreement between a stub symbol being of type `f(void)` vs. `f()`, aka `f(...)` (manifesting as `ellipsis: 1`). Would appreciate someone with more familiarity with the C front-end taking a look at how that ought to work.

**Comment by smowton** [comment]
Finished testing this with test-gen, successfully. Results:

Required CBMC PRs:
* https://github.com/diffblue/cbmc/pull/4183
* https://github.com/diffblue/cbmc/pull/4184
* https://github.com/diffblue/cbmc/pull/3725
  * https://github.com/diffblue/cbmc/pull/4185

Test-gen demonstration bump: https://github.com/diffblue/test-gen/pull/3049
Part of which can be merged without the bump: https://github.com/diffblue/test-gen/pull/3048

**Comment by smowton** [comment]
The most significant requirement is simplify-after-symex-dereference. This is needed because now that decorated types are correctly distinguished it is common to see e.g. `byte_extract A<B> some_A<C>_expression`, i.e. a whole-struct cast, and the simplifier can forward member expressions appropriately across the "cast". Without that test-gen fails because it can't handle byte-extract in various places, and even if those are repaired performance is significantly degraded. With it the impact appears to be marginal, though more thorough testing is needed.

**Comment by tautschnig** [comment]
I'm worried that we might still need the type comparison facility in linking, so it may actually be necessary to move the `base_type_eq` code to `src/linking/` rather than removing it completely. This may or may not overlap with the problems that @smowton noticed. Assigning to myself for further debugging.

**Review by tautschnig — APPROVED** [review]
Approving ~, but @kroening: please double-check as I've added two commits of my own to make yours work.~ (Edit: those commits were moved to PRs of there own and have since been merged.)

**Comment by tautschnig** [comment]
#6989 now takes care of most of the uses, with only three uses remaining thereafter.

**Comment by tautschnig** [comment]
Closing as this was now completed in #6989.

**Pull request closed without merging**
