### PR TITLE
SMT2 back-end: make declare-datatypes standards compatible

### PR DESCRIPTION
**Pull request by tautschnig**
The standards-compatible syntax is understood by both Z3 (which also accepted the previous one) as well as CVC5 (which only accepts the new one).

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
Do you happen to know which version of Z3 added support for the new one?
We should communicate a set of supported solver versions.

**Comment by tautschnig** [comment]
> Do you happen to know which version of Z3 added support for the new one? We should communicate a set of supported solver versions.

I have only tested with version 4.8.7 (has been released 2019-11-19) on my system, I wasn't aware that support for this varied over time.

**Review by martin-cs — APPROVED** [review]
Useful; thank you.

**Comment by martin-cs** [comment]
> > Do you happen to know which version of Z3 added support for the new one? We should communicate a set of supported solver versions.
> 
> I have only tested with version 4.8.7 (has been released 2019-11-19) on my system, I wasn't aware that support for this varied over time.

Datatypes were only added to the standard SMT-LIB in 2.6, so July 2017.  They were supported by a number of solvers long before that but with varying syntax.

**Comment by martin-cs** [comment]
This fails the coverage test but I think that is more due to limitations of our testing of the SMT-LIB back-end than anything to do with this patch so I am merging it.

**Pull request merged**
