### PR TITLE
Update Doxygen version

### PR DESCRIPTION
**Pull request by owen-mc-diffblue**
The old version is no longer available from this host

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by thk123 — APPROVED** [review]
Can't imagine point releases mattering. 

Is wget-ing from this serve the best option?

**Review by chrisr-diffblue — APPROVED** [review]
Assuming that a minor point release update doesn't break CI doxygen, approved. Depending on how much we want to tie ourselves to a specific Doxygen version it might be better to host the chosen version ourselves - but I don't think the download links have broken very often, so might not be worth the extra management.

**Review by chrisr-diffblue — APPROVED** [review]
Assuming that a minor point release update doesn't break CI doxygen, approved. Depending on how much we want to tie ourselves to a specific Doxygen version it might be better to host the chosen version ourselves - but I don't think the download links have broken very often, so might not be worth the extra management.

**Review by smowton — APPROVED** [review]

**Comment by owen-mc-diffblue** [comment]
I'm having problems with multi-line doxygen warnings. They seemed to work before.

**Comment by thk123** [comment]
Replaced by #5058

**Pull request closed without merging**
