### PR TITLE
Move {json,xml}_expr.{h,cpp} to goto-programs [blocks: #3734, #3736]

### PR DESCRIPTION
**Pull request by tautschnig**
This prepares the move of {json,xml}_expr.{h,cpp} to goto-programs to remove the
dependency of util on langapi.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: e6d5e212295e915f76541f3dd174e1e0f0cac81a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96535289

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: bf25f8df993d937de5bf55fc4e1f2646baaaffe8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96539054
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by smowton — APPROVED** [review]

**Review by chrisr-diffblue — APPROVED** [review]

**Comment by tautschnig** [comment]
I suspect this requires a genuine update in TG as quite possibly it uses `util/json_expr.h` (which should now be `goto-programs/json_expr.h`. Could a bump please be created @allredj @peterschrammel @thk123?

**Comment by antlechner** [comment]
@tautschnig It does look like this needs a TG update, I'm working on it and I'll keep you updated.

**Comment by tautschnig** [comment]
Thank you @antlechner! I have rebased this PR to hopefully simplify the TG work.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 833721daf5c29b7ccac6546a9b8515d55d97ae07).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96755542
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: d8b511fa236b33fb137721761eb5c37374e949f5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96772500
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by antlechner** [comment]
@tautschnig We have a TG pointer bump that passes now, so feel free to merge this PR. Thanks for notifying us that an update was needed. :slightly_smiling_face:

**Comment by tautschnig** [comment]
Thanks @antlechner! Re-assigning to @kroening and @peterschrammel for review.

**Review by kroening — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
