### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by rjmunro**
First stab at editorconfig file. Matches most of the files in src, but might need slight customisation for certain file types.

### CODE REVIEW

**Comment by rjmunro** [comment]
There were some file-specific overrides that were generated by the tool I used; Some Makefiles use tabs for indenting, some header files seem to use more than 2 spaces.

I don't think it's worth including these overrides in the editorconfig file, because I don't think they are deliberately styled differently, and you can do, e.g. 4 space indenting with the editor in 2 space mode by pressing tab twice.

```
[{src/assembler/Makefile,src/big-int/makefile,src/jsil/Makefile,src/json/Makefile,src/langapi/Makefile,src/xmllang/Makefile}]
indent_style: tab

[{src/util/hash_cont.h}]
indent_style = space
indent_size = 4

[{src/aa-path-symex/Makefile,src/analyses/Makefile,src/cpp/Makefile,src/goto-programs/Makefile,src/goto-symex/Makefile,src/linking/Makefile,src/path-symex/Makefile,src/pointer-analysis/Makefile,src/util/rename.h}]
indent_style = space
indent_size = 6

[{src/goto-programs/remove_asm.h}]
indent_style = space
indent_size = 8

[{src/goto-programs/basic_blocks.h}]
indent_style = space
indent_size = 18

[{src/util/file_util.h}]
indent_style = space
indent_size = 28
```

**Comment by kroening** [comment]
The tabs in the makefiles unfortunately carry semantics, i.e., can't be avoided. All makefiles need to keep their tabs as is.

Why does src/util/rename.h/remove_asm.h/basic_blocks.h/file_util.h get special treatment?

**Comment by tautschnig** [comment]
Those header files seem to be using
```
void foo(int arg,
               int other_arg);
```
instead of
```
void foo(
  int arg,
  int other_arg);
```
That should be fixed, but certainly does not deserve special treatment in the editor configuration.

**Comment by kroening** [comment]
@rjmunro May I ask for a pull request that removes those extra spaces, please?

**Comment by tautschnig** [comment]
There could be some funny ones, though: src/goto-programs/remove_asm.h seems to have that extra space in the comments at the top...

**Comment by rjmunro** [comment]
@kroening So this .editorconfig file just gives hints to supported editors (which may require a plugin) on how they should format the text by default. It doesn't validate or force styles. This can be merged without needing to change the other files first. I'll take a look at those other .h files.

**Pull request merged**
