### PR TITLE
Tests for SMT2 strings with nondet arguments

### PR DESCRIPTION
**Pull request by allredj**
Tests are all marked `FUTURE` because of CBMC's lacking support, but the test suite can be run against third-party SMT2 solvers (Z3, CVC4). Instructions are in https://github.com/diffblue/cbmc/blob/develop/regression/smt2_strings/README.md.

Since it is not practical to check the satisfied model (due to solver outputs not being standard), tests are of the traditional SAT/UNSAT form, which check that the string operations are neither *trivially* over-constrained nor *trivially* under-constrained, respectively.

The already existing tests for constant arguments ensure that the string operations are correct for at least one input.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by allredj** [comment]
As a next step (follow-up PR), I will mark those tests that are known bugs for Z3 and CVC4.

**Comment by martin-cs** [comment]
On Fri, 2019-03-22 at 09:16 -0700, Joel Allred wrote:
> As a next step (follow-up PR), I will mark those tests that are known
> bugs for Z3 and CVC4.

I would also strongly suggest that you submit them to the Z3 and CVC4
dev teams as SMT-COMP is coming up so people are in 'fixing bugs' mode.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 5d44cf20b1e35c8f61dad64ed2266d1227b61769).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105476383
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: f863ae56b3a5fbb578fb1eb3f30cdae757e54603).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105482656
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Comment by allredj** [comment]
@martin-cs noted! :-)

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: a4ed13b13ddd35e8f73cd0b3439505e51851fd2c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105485099
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: e4e21085922f931e520a4aef5d8e21053b3b7773).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105489439

**Review by romainbrenguier — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
