### PR TITLE
boolbvt: convert_with now does struct_tag and union_tag types

### PR DESCRIPTION
**Pull request by kroening**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
Ok, but how did you notice? Do we know this is the last one?

**Comment by kroening** [comment]
@tautschnig There are currently a lot of bugs like this one hidden behind the fact that symbol types and struct and union tags are expanded during symbolic simulation.

Once we stop that expansion we should see these.

**Comment by tautschnig** [comment]
I was guessing as much; as a reviewer, it's would be nice to have some info like "fixes N tests when not expanding tags during symex." (And maybe "Y tests remaining to be debugged.")

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: dbec31138be5931d3b40e09cf9908430899a7b86).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86674798

**Pull request merged**
