### PR TITLE
Use model for String.hashCode

### PR DESCRIPTION
**Pull request by romainbrenguier**
The version in the solver is incomplete (under-constrained) and it is not possible to have a complete version which would be really language independent, so it is better to implement these in models, like we do in https://github.com/diffblue/java-models-library/pull/10 for Java

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 56e097e610e9613ebe3c36c85e029ec64c4d9eb3).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/108816446
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: b6c30ba4b9f7f896e52a526fb9ba3f1e8c835f89).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/108857635
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by peterschrammel — APPROVED** [review]

**Comment by tautschnig** [comment]
@romainbrenguier What's the state of this?

**Comment by romainbrenguier** [comment]
@tautschnig 
> @romainbrenguier What's the state of this?

I'm waiting on a test-gen pull request to confirm this is safe to merge, but it doesn't compile with the current version of cbmc at the moment.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 7353640b5a2837657091df067966efda34ff3ab1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/111548598

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 18d1a00e693369d9bb2a22d96c10dcc04b8d217e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/111562482
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Pull request merged**
