### PR TITLE
split out goto_functiont from goto_functions.h into separate file

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
Note to self: there are a number of places that include `goto_functions.h` when now they could happily use `goto_function.h`.

**Comment by tautschnig** [comment]
Thank you for the additional work! The commit message is a bit misleading, though.

**Review by chrisr-diffblue — APPROVED** [review]
LGTM

**Comment by thk123** [comment]
test gen bump: diffblue/test-gen#1801

**Pull request merged**
