### PR TITLE
Real support in SMT2

### PR DESCRIPTION
**Pull request by pkesseli**
Added Real sort to SMT2 solver and appropriate casts to/from Real.

### CODE REVIEW

**Comment by tautschnig** [comment]
This looks like a very nice piece of work! I think it would be nice if the language front-end fixes were put in a separate commit as those would be equally useful with, e.g., the SMT1 back-end.

**Comment by pkesseli** [comment]
Thanks! Are you referring to the changes in `ansi-c/*` and `util/*`?

**Comment by tautschnig** [comment]
> Are you referring to the changes in ansi-c/* and util/*?

Yes, I'd say it's exactly those. Maybe you can just split up your commit in two (it appears to require a rebase anyway)?

**Comment by martin-cs** [comment]
@pkesseli Is that review request an actual request from you or just automated?  As CEGIS is gone this will require rework.

**Comment by thomasspriggs** [comment]
This looks like useful work. But a substantial rebase is required due to the removal of cegis and the need to write new tests, to test without cegis. I am going to close this out for the moment, given the extended period of time since this was last worked on. However it would be good to reopen this PR or an equivalent new PR once someone can spare the time to rebase and address any other reviewer comments.

**Pull request closed without merging**
