### PR TITLE
fix type inconsistency during dereferencing

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 329d0742914607eb84ca0117041f10980839dbdf).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77797319

**Review by smowton — COMMENTED** [review]
Test plz ;)

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: e73bf07242c474cabb610aaea1a9064f523d2097).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85622356

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 0ed966ad66d7ba15fc1a857cad933d2856348dbf).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86396813

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 7dac722ad22645a124fee759f82a08479b2e20a0).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86669611

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: faeffb2e621f0cf7de973a837c8bfb527f04039d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87886156

**Comment by martin-cs** [comment]
+1 what @smowton said.  If this has an external effect we should be able to test for it.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: dbb855754268d76749e5bc6c2c725556247c8626).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93224434

**Comment by TGWDB** [comment]
Closing since this code appears to be no longer around.

If you believe this is erroneous please reopen (and maybe indicate where this should be fixed in the current codebase).

**Pull request closed without merging**
