### PR TITLE
Make declarations in switch body reachable

### PR DESCRIPTION
**Pull request by tautschnig**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
BTW, is there a similar problem with gotos?

**Comment by tautschnig** [comment]
> BTW, is there a similar problem with gotos?

Are you thinking about a `goto` statement jumping into the middle of a block, skipping declarations? We would indeed generate goto programs where declarations are unreachable, but the fix doesn't seem as obvious to me. Any ideas?

**Comment by smowton** [comment]
Nitpick: this feels like a C language oddity, so I'd expect the frontend to deal with it -- something like

```
switch {
  decls;
  cases;
}
```
-->
```
{
  decls;
  switch {
    cases;
  }
}
```

On the GOTO front, goto_convert knows when we're entering a block (and this does occasionally happen with the Java frontend), but ignores it: https://github.com/diffblue/cbmc/blob/develop/src/goto-programs/goto_convert.cpp#L160

**Comment by tautschnig** [comment]
I've now moved the implementation to the C/C++ front-end as suggested by @smowton.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3940be89f73bec8e152d115c14e979905e8cd842).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100229360

**Review by smowton — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 80fb55898a2b9f6bef279300a30270d5c1d98441).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103466441

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: a55a4498a71f2c9f56cd469d4418705aecf130f4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/104506925
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by kroening — APPROVED** [review]

**Pull request merged**
