### PR TITLE
Remove deprecated constructors

### PR DESCRIPTION
**Pull request by tautschnig**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by martin-cs** [comment]
Are reviews still required / desired for this?

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 608f3ed736de47b8fe912ac1ba218a1d05fe30cb).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98857812
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: b853b76c4641789854ca1ff1e53cdb287f7e398c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99579170
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
@allredj @svorenova @peterschrammel @thk123  If and when time permits, could you please look into what it takes to make TG work with this? With a single exception all the necessary cleanup to get rid of users of deprecated *exprt constructors has been merged in the CBMC code base, but given that the bot isn't happy this doesn't seem to be true of TG. This PR really just removes deprecated functions, there are no changes to non-deprecated ones.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 1b516038d1c504a8e02a538693fe539dbc30f46b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99842644
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by thk123** [comment]
@tautschnig Just to say we're aware of this and it has a ticket (TG-6051 to ease your tracking) - we're hoping to get to it in then next two weeks, please lmk if that time is inconvenient and I'll see if we can bump it up :) (there are unfortunately quite a lot... :slightly_frowning_face: )

**Comment by tautschnig** [comment]
@thk123 Nah, no rush, if we can get it done some time over the next months that would be nice.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 06ffaa002d3b7862768fbea149c13834546696de).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105558030
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 45d950efcb3255fab19a839800b168e026c3c284).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105559944
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by martin-cs — APPROVED** [review]

**Review by smowton — APPROVED** [review]

**Comment by thk123** [comment]
Updated TG - rebasing this should get the Joel bot to pass

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 370ec818ec6d313e1fd6432d9574141bfca45de2).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105883753
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Pull request merged**
