### PR TITLE
Remove the string-non-empty function which had no effect 

### PR DESCRIPTION
**Pull request by romainbrenguier**

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Comment by tautschnig** [comment]
Is there a particular reason this is split into two commits?

**Comment by romainbrenguier** [comment]
@tautschnig 
> Is there a particular reason this is split into two commits?

It's just that the changes can be done independently, so I thought it would make it easier to revert part of them for instance if needed. But I can squash the commits if preferred.

**Comment by tautschnig** [comment]
> It's just that the changes can be done independently, so I thought it would make it easier to revert part of them for instance if needed. [...]

Ok, thanks for clarifying! It just seemed that only the second commit explained the "Why?" a bit, so I was wondering.

**Review by martin-cs — APPROVED** [review]
Fine.  FWIW I quite like the "remove the option setting, then remove the functionality" split.

**Pull request merged**
