### PR TITLE
Delete unused pre/postcondition.h/cpp [DOC-143]

### PR DESCRIPTION
**Pull request by romainbrenguier**
These files are unused within CBMC, there is no point in continuing to maintain them.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [na] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by LAJW — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 6465dfc7ea345ce2a2b69cf36fb07dd93401a8a7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99802915

**Comment by peterschrammel** [comment]
@kroening, is this still in use in a dependent repository?

**Comment by TGWDB** [comment]
@kroening Are these files still needed? I rebased and ran without them locally and had no failures in regression, so this PR could be rebased/merged if there are no dependencies.

**Comment by TGWDB** [comment]
Closing as deprecated, see #7052

**Pull request closed without merging**
