### PR TITLE
simplify_function_application: do not assume that a symbol always has a value

### PR DESCRIPTION
**Pull request by tautschnig**
The possible arrays we might see include dynamic objects, which are symbols, but
need not have an initial value. While at it, actually implement a proper prefix
check rather than limiting this to the same length. And then do take into
account the offset, which was previously missing as well.

This is exercised by several `startsWith` regression tests, but the initial problem was only triggered when enabling further constant propagation.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — APPROVED** [review]
Could you add `0 conditions remaining` or whatever it is we say when symex has solved the problem to those startsWith tests?

**Comment by tautschnig** [comment]
> Could you add `0 conditions remaining` or whatever it is we say when symex has solved the problem to those startsWith tests?

All of them seem to be crafted such that there is at least one failing assertion, which does require the use of SAT solver. I have now extended the test that @JohnDumbell had added for this initial version of this simplifier pass.

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 00f9de32ba9dc4eb08d27e8670749943722bfa6f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99643033
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 79c76a7c5fe51d2f9db1993447e34cee3de8b103).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99646614

**Pull request merged**
