### PR TITLE
remove AIGs

### PR DESCRIPTION
**Pull request by kroening**
I no longer know about any sensible use for AIGs in any cbmc-related context.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 5172be3c193cbb9b27e8a6f555f5de5e4fd9f4b1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/80940474
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: c11c716733ed368148ebfd96fdffb90e8831073f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/80940658

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 0efb169b74c699c5978aa92006b9cb1387bfc901).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/80945413

**Comment by tautschnig** [comment]
I have to admit I have no idea in what way this back-end may have been used. I'd ask @martin-cs for his opinion.

**Comment by martin-cs** [comment]
@tautschnig : This is an alternative representation of propositional gates.  It was created at a time when using AIGs and various circuit optimisation / simplification techniques (think ABC) was popular among people writing BV SMT solvers.  It was originally written for a customer to explore whether this would give a performance improvement.  It kind of does but it is incompatible with various other low-level optimisations (the optimal full-adder and various other CNF / non-circuit optimisations), so it depends a bit on what you are comparing against.  One key optimisation you need is when you lower from AIG to CNF, you need to locate and handle XORs; that was one of the key optimisations we needed IIRC.  So, really an XAIG format would be better.

Is it worth having?  Maybe.  It depends on the direction we are doing with the back-end.  There is a school of thought in the SAT world that says things like blocked-clause elimination and various other modern SAT preprocessing (and inprocessing) techniques subsume most, if not all, of the things you can do with AIGs.  So...

A. If we think that the solver back-end should be basically just a compatibility layer for connecting to SAT solvers and we're moving to something more modern than MiniSAT, then we don't need it.

B. If we are planning on doing anything hardware related, it is probably worth keeping to simply avoid needing to rewrite it as various intermediate languages (i.e. AIGER) there are AIG.

C. If we're interested in maintaining an actual SMT solver, then I'd say keep it as the prevalent SMT view seems to be that they are worth using.

**Review by martin-cs — CHANGES_REQUESTED** [review]
If we are going to remove it, we should remove the --aig option from CBMC as well.

**Comment by kroening** [comment]
BTW, I'll move this to the ebmc repo. AIGs still seem relevant in hardware.
For SMT, I expect that the CNF-level preprocessing/inprocessing mentioned by Martin will eventually 
win.

**Review by martin-cs — APPROVED** [review]
Approve in the sense that the option has been removed.  I'll leave it to others to decide on which of A/B/C are relevant.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: d42020ba42a6f8c4e72869cf0c727ddfb325841b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/81023051

**Pull request merged**
