### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by NathanJPhillips**
Added IDE files to .gitignore
Remove unnecessary casts from json.h
Added comment on hard to track potential error (it causes very cryptic messages) caused by #define in irep_hash to save external users time (internal users shouldn't encounter this as we don't use Boost)

### CODE REVIEW

**Comment by tautschnig** [comment]
It would be nice if those edits could be committed as 3 commits as the cleanups seem rather unrelated.

**Comment by NathanJPhillips** [comment]
Can do, they're only related by the fact that I found them all while doing another piece of work. Want me to close this PR and start again?

**Comment by peterschrammel** [comment]
@NathanJPhillips, no, just split your commit into three and force push.

**Comment by NathanJPhillips** [comment]
OK, done.

**Pull request merged**
