### PR TITLE
klaas' Contracts work

### PR DESCRIPTION
**Pull request by karkhaz**
This is a squash of the memory predicate patch (#2706) and the code contracts patch (#2677) by Klaas. Klaas has agreed for me to take ownership of these patches and work to get them merged.

At the moment, I haven't made many changes. I plan to clean them up over the next few weeks, but please chime in: I would be grateful for any guidance on what changes need to be made in order to get these patches merged. I'll be reading the comments on the old PRs, but please let's continue the discussion here.

### CODE REVIEW

**Comment by kroening** [comment]
A quick question: is the new __CPROVER_points_to_valid_memory() basically the same as __CPROVER_r_ok()?

**Comment by kroening** [comment]
Another small one: The tweak to .gitignore should be a separate PR, it's very unrelated.

**Comment by kroening** [comment]
The tests go into three different directories -- focus on regression/contracts?

**Comment by kroening** [comment]
Commits such as 724ed52 could also be separate PRs.

**Comment by karkhaz** [comment]
Closing, but please don't delete. I'm going to post separate and more manageable PRs for this a little at a time.

**Pull request closed without merging**
