### PR TITLE
Build fail clang 12

### LINKED ISSUE #5501: Build fails with Apple Clang 12 (clang-1200.0.32.2) due to use of reference types
Clang build fails due to the -WError flag, resulting in -Wrange-loop-analysis warnings being shown as errors. 
The issue arises in multiple files due to the use of `auto` instead of `auto&` since the compiler expects a non reference type for places where one iterates over a loop in such a way that creates a proxy/copy of the elements instead of a reference to the elements themselves.
e.g.

`
src/util/graph.h:635:20: error: loop variable 'succ' of type 'const std::__1::pair<const unsigned long, empty_edget>' creates a
      copy from type 'const std::__1::pair<const unsigned long, empty_edget>' [-Werror,-Wrange-loop-analysis]
    for(const auto succ : succs)`

CBMC version: 5.14.1 (cbmc-5.14.1-dirty)
Operating system: MacOS Catalina 10.15.6
Exact command line resulting in the issue: cmake --build build
What behaviour did you expect: building without errors
What happened instead: build fails

### PR DESCRIPTION
**Pull request by mina1604**
fix issue #5501

### CODE REVIEW

**Review by martin-cs — APPROVED** [review]
Looks like the kind of patch we should have regardless of the clang issue, even better if it fixes the thing.

**Review by NlightNFotis — APPROVED** [review]

**Comment by NlightNFotis** [comment]
Thanks for your contribution.

Can I ask that the last commit is removed, and the `clang-format` changes be squashed into the previous commit? LGTM otherwise.

**Comment by martin-cs** [comment]
Yes; good catch @NlightNFotis : @mina1604 we normally work by rebasing branches and then merging into `develop` rather than merging `develop` into the branches.

**Review by hannes-steffenhagen-diffblue — APPROVED** [review]
LGTM modulo previous comments (i.e. rebase instead of merge, would be better if clang-format changes were done in the same commit as the code changes).

**Comment by mina1604** [comment]
Should be one commit now.

**Comment by NlightNFotis** [comment]
Thanks for the prompt change.

We'll take it from here - we'll chase reviews internally and merge it once it has an adequate number of reviews.

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
