### PR TITLE
Evaluate __builtin_ffs{,l,ll} over constants at compile time

### PR DESCRIPTION
**Pull request by tautschnig**
GCC evaluates this built-in at compile time, and the Linux kernel
assumes this is the case.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by martin-cs — APPROVED** [review]
Yes but...

1. Do we have any tests for what happens when it is not a compile-time constant?
2. Given that this has quite a few a few friends that need to be (partially, constant only, etc.) evaluated before / during type checking, is it time to start thinking about an abstraction / pass / organisation of these?

**Comment by tautschnig** [comment]
> Yes but...
> 
> 1. Do we have any tests for what happens when it is not a compile-time constant?

We do - the existing regression test (in which the constant cases have now been turned into `_Static_assert`s) already included that case.

> 2. Given that this has quite a few a few friends that need to be (partially, constant only, etc.) evaluated before / during type checking, is it time to start thinking about an abstraction / pass / organisation of these?

Fair point. One way of doing this is introducing `exprt`s for each of those functions (like we already have for `popcount`) and have the simplifier do all this work.

**Comment by martin-cs** [comment]
I like the idea of the simplifier doing this because that way it can be used elsewhere, constant folded during symex, checked during trace construction, etc.  Not entirely sure each one needs an `ID`, but, then again, what would be better?

**Comment by tautschnig** [comment]
> I like the idea of the simplifier doing this because that way it can be used elsewhere, constant folded during symex, checked during trace construction, etc. Not entirely sure each one needs an `ID`, but, then again, what would be better?

This is now built on top of #5879, introducing a new `find_first_set_exprt`.

**Review by kroening — APPROVED** [review]

**Pull request merged**
