### PR TITLE
Fix the return type to match the class member types

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by kroening — APPROVED** [review]

**Comment by tautschnig** [comment]
Could a test-gen bump please be set up for this one? From reading the code this looks like a bug fix, but maybe 1) it does not matter and 2) the member declarations could be wrong, resulting in more bugs being introduced rather than fixed.

**Comment by peterschrammel** [comment]
TG bump created

**Review by peterschrammel — APPROVED** [review]
Has no observable impact.

**Comment by kroening** [comment]
This should be observable on classes with tables with >=256 entries.

**Pull request merged**
