### PR TITLE
move CPROVER manual source into git repo

### PR DESCRIPTION
**Pull request by kroening**
The CPROVER manual at http://www.cprover.org/cprover-manual/ is written
using markdown.  The markdown sources are translated client-side into HTML.
This PR adds the markdown sources to the repo, which enables that they are
pulled directly from the git repo.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
Approving of the overall approach. I have not actually reviewed the contents being added here, which may require some rework.

**Comment by kroening** [comment]
@tautschnig The contents will definitively need work, but that should be separate.

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 633cd2ed0706fb8f3d88355bdd12ce4425f2829b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/89525347
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 359d30e92e5ec349c700d91e03f57a97db32f170).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/89527537

**Pull request merged**
