### PR TITLE
Performance test script: speed up build, support Nitro

### PR DESCRIPTION
**Pull request by tautschnig**
The first commit might also be of interest to the CI set-up as similar changes could/should be made to the CodeBuild configuration.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
@kroening Please take a look as there is may be of interest to speed up CodeBuild jobs.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: abf72581ff54d52307bae6b22f7dd8cfb5f10b74).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95301548

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0338a1317823a23a49b3c21385c405b222b25f7f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95581623

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 24a31ade9c52319c48a299aa3e34fdc87596864e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95719983

**Comment by kroening** [comment]
@tautschnig Yes, I will give that a try.

**Review by kroening — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c37290f8e4c53694610c0bbf9a93b08012d6597f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95863273

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
