### PR TITLE
Migrate all uses of message_streamt to messaget

### PR DESCRIPTION
**Pull request by tautschnig**
Includes cleanup of messaging APIs and diagnostic output.

### CODE REVIEW

**Comment by kroening** [comment]
A large fraction of this is now merged -- may I ask for a rebase?

**Comment by tautschnig** [comment]
The requested rebase is now done; cherry-picking patches from this pull request instead of manual merges would help a lot to avoid having to spend a lot of time on fixing ensuing conflicts.

**Comment by kroening** [comment]
Did cherry-pick for most of these!

**Comment by forejtv** [comment]
@tautschnig @kroening What is the status of this, is it still relevant? If yes, should it be rebased, reviewed and merged? Most of the changes seem non-controversial.

**Comment by tautschnig** [comment]
Working on the rebase.

**Comment by tautschnig** [comment]
I have opened #563 for the linter failure. I'll now look into the regression test failures.

**Comment by tautschnig** [comment]
Has the Travis configuration been removed? The other checks appear to be passing.

**Comment by forejtv** [comment]
No idea why Travis was not showing up, it was running. The tests pass, so I think this should be good to go. @kroening, your turn.

**Comment by tautschnig** [comment]
@kroening Could this please be considered for the upcoming release? It will (among lots of other cleanup) get the goto-cc output back to a sane state.

**Comment by kroening** [comment]
I have cherry-picked the obvious bits. What's the idea of using those counters?

**Comment by tautschnig** [comment]
I have rebased the patch set to current master; the message counters allow selective treatment of warnings as errors (just like compilers can be told to do).

**Comment by tautschnig** [comment]
I have now also added that patch that makes use of message counters (to support -Werror and its equivalents).

**Comment by forejtv** [comment]
@tautschnig this now needs a rebase due to an earlier error in master that got propagated to this branch.

**Comment by tautschnig** [comment]
Rebase done.

**Comment by tautschnig** [comment]
It should be noted that 51a1b1b handles Wno-error together with Werror for GCC, but does not necessarily cope with conflicting error-configuration parameters for other platforms as I don't have access to those.

**Pull request merged**
