### PR TITLE
switch all Linux/clang jobs to Clang 6.0

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by tautschnig — COMMENTED** [review]
Could the commit message please include information on the "WHY?" - the changes look ok, but also very random.

**Comment by kroening** [comment]
clang 3.7 has stopped working on Travis; the reason isn't really known.

**Comment by owen-mc-diffblue** [comment]
I've looked into the reason and I've fixed it in a different repo. It's because Travis have removed `llvm-toolchain-precise-3.7` from their list of whitelisted sources for `apt`. Here's the commit: https://github.com/travis-ci/apt-source-safelist/commit/e9d632eb79c7b733b3bfe722356e892ab8e06059 . The workaround is to manually add the source and install `clang-3.7`.

**Comment by tautschnig** [comment]
> clang 3.7 has stopped working on Travis

That at least seems like a good "WHY" justifying the change. And then it should likely say "switch all Linux/clang jobs to Clang 6.0?"

**Review by tautschnig — APPROVED** [review]
Approving with the assumption that the commit message will be fixed up to include the results of @owen-jones-diffblue's findings.

**Comment by owen-mc-diffblue** [comment]
I'm happy to make an alternative PR to keep `clang-3.7` if you want, @kroening.

**Comment by kroening** [comment]
@owen-jones-diffblue Yes, please do; we do want to retain the ability to build with 3.7 for at least some time.

**Comment by thk123** [comment]
I would like to swap TG to use clang-6.0 at the same time, can I recommend we go with Owens fix to unblock CI on CBMC, I'll look into clang-6 on TG tomorrow (can't think of any reason why it would be a problem).

**Comment by owen-mc-diffblue** [comment]
I have created https://github.com/diffblue/cbmc/pull/2862

**Comment by tautschnig** [comment]
@kroening Can this be closed with #2862 having been merged?

**Pull request closed without merging**
