### PR TITLE
Fixes of __attribute__((always_inline)) type checking

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 02a4c40877bf68572d148737630eeba8460f5bfc).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77349966

**Comment by tautschnig** [comment]
Marking work-in-progress as I have received further problem reports of related issues that aren't yet addressed.

**Comment by NlightNFotis** [comment]
Hi @tautschnig, is this still relevant?

If yes, can we get it rebased on `develop`?

**Comment by thomasspriggs** [comment]
I am going to close this out due to a lack of response from the author. Please reopen it if you still think it is worthwhile and you have time to rebase.

**Pull request closed without merging**
