### PR TITLE
Use CL version to determine target

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Comment by kroening** [comment]
Needs #2849.
For testing, I'll add something that asserts that the parsing doesn't fail.

**Comment by tautschnig** [comment]
#2849 has been merged, tests can now be added.

**Review by tautschnig — APPROVED** [review]
Test added.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 44fe41912cbe3d0c02180ba8ce0b79926e588c28).
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 27b4806a206c0f7bf5891383009a435e96038722).
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Pull request merged**
