### PR TITLE
Move convert_nondet to java_bytecode

### PR DESCRIPTION
**Pull request by peterschrammel**

### CODE REVIEW

**Comment by mgudemann** [comment]
@peterschrammel needs TG-bump

**Review by mgudemann — APPROVED** [review]
LGTM

**Review by tautschnig — APPROVED** [review]
It's a shame, because it would be really useful to have this for other languages, but unfortunately it has been implemented in a Java-only way and thus this PR is the right thing to do...

**Comment by kroening** [comment]
If this is java-specific, may I suggest to name the file and the function convert_java_nodet.

**Comment by peterschrammel** [comment]
TG bump is coming. Requires some further TG fixes to be merged first.

**Comment by peterschrammel** [comment]
Ignore the AWS failure - it spuriously aborted during the 'provisioning' phase.

**Comment by peterschrammel** [comment]
AWS succeeded after restarting, but that doesn't show up in github.

**Pull request merged**
