### PR TITLE
Restore returns fix

### PR DESCRIPTION
**Pull request by danpoe**

### CODE REVIEW

**Comment by kroening** [comment]
Do you happen to have a test?

**Comment by tautschnig** [comment]
Just to say that I've run into the same problem, I'll try to provide an example.

**Comment by tautschnig** [comment]
Here's an example:
```
$ cat ret.c
int foo()
{
  int x;
  return x;
}

int main()
{
  foo();
  return 0;
}
```
Compile it and then run it past dump-c (to trigger restore-returns) with remove-returns having been done, as is the case in the escape analysis:
```
$ goto-cc/goto-cc ret.c
$ goto-instrument/goto-instrument --escape-analysis --dump-c a.out
Reading GOTO program from `a.out'
Function Pointer Removal
Partial Inlining
Removing returns
Escape Analysis
goto-instrument: remove_returns.cpp:336: bool remove_returnst::restore_returns(std::map<dstring, goto_function_templatet<goto_programt>, std::less<dstring>, std::allocator<std::pair<const dstring, goto_function_templatet<goto_programt> > > >::iterator): Assertion `next->is_goto()' failed.
Aborted
```

**Comment by danpoe** [comment]
Thanks Michael. I've added this as a regression test.

**Pull request merged**
