### PR TITLE
Move all the various id_sett typedefs into irep.h

### PR DESCRIPTION
**Pull request by NathanJPhillips**
Call them unordered_id_sett to reflect the fact that these are unordered sets
Add matching id_sett for signed sets of identifiers.

### CODE REVIEW

**Comment by NathanJPhillips** [comment]
Test-gen bump: https://github.com/diffblue/test-gen/pull/1714

**Review by tautschnig — COMMENTED** [review]
1) The cleanup seems like a good idea.
2) I don't think `id_usett` is a great name - can we use `unordered_id_sett` instead?
3) Any use of `id_sett` should be audited: it's useful for doing set intersection/set union, but not for much else, because it won't provide the performance of a hash container and doesn't provide lexicographic ordering either (unless `irep_idt == std::string`).

**Comment by smowton** [comment]
Agreed re: `unordered_id_sett`. I wouldn't wade into `set` -> `unordered_set` replacements in this PR, since each case requires some searching to check if anything cares about reproducible ordering and/or stable iterators.

**Comment by kroening** [comment]
This only needs the commit messages reworded, then seems fine.

**Review by kroening — APPROVED** [review]

**Comment by kroening** [comment]
Considering #2082, I am wondering whether this actually improves readability.

**Comment by tautschnig** [comment]
I would prefer: merge #2082 and then make good use of the commits in this PR and do `sed -i 's/unordered_id_sett/std::unordered_set<irep_idt>/g'` (which now actually is possible thanks to all the consistency cleanup done by @NathanJPhillips.

**Pull request closed without merging**
