### PR TITLE
Show variables that are not used in the whole program

### PR DESCRIPTION
**Pull request by nmanthey**

### CODE REVIEW

**Comment by kroening** [comment]
This is basically a proper "analysis", i.e, perhaps should be promoted to live in goto-analyzer?

Also, there is ambiguity about what it means to "read" vs. "use" a variable. The PR makes "x" used when &x is encountered. One could take a view that taking the address isn't "reading" but is just "using". rw_sets could be parameterised for the two cases.

**Comment by nmanthey** [comment]
I can move this into the analyzer, but as the code relies on rw_set, it would be dependent on the goto-instrument object files. This looks like a heavy change to me.

To me it is not clear how I could parameterise rw_sets for the two different cases. Michael suggested to use dirty symbols. If the name is misleading, I am happy to use "unused" consistently everywhere.

**Comment by NlightNFotis** [comment]
Hi @nmanthey, if you want this to be merged, could this please be rebased on top of current `develop` please? CI is stale (the configuration has changed a lot since then) and there are Merge conflicts.

If not, can we have this closed please?

**Comment by thomasspriggs** [comment]
I am going to close this out due to a lack of response from the author. Please reopen it if you still think it is worthwhile and you have time to rebase and address reviewer comments.

**Pull request closed without merging**
