### PR TITLE
Add missing swap instruction

### PR DESCRIPTION
**Pull request by pkesseli**
Fixes issue https://github.com/diffblue/test-gen/issues/103. Swap
instruction was not handled in convert_instructions. Includes the
original Groovy regression test which sparked the issue ("swap2") and a
simpler unit test ("swap1") which was created using ASM.

### CODE REVIEW

**Comment by tautschnig** [comment]
How does one build the class file from the groovy code?

**Comment by mgudemann** [comment]
shouldn't this be in CBMC/master ?

**Comment by pkesseli** [comment]
@tautschnig The original Gradle project can be found here: https://github.com/spring-projects/spring-framework.

**Comment by tautschnig** [comment]
@pkesseli Ok, but there should be sufficient information in the repository here to rebuild the binary files. Distributing binary files without instructions on how to re-generate them is going to cause trouble eventually, and legal questions may arise.

**Pull request merged**
