### PR TITLE
Inline copy_to_operands

### PR DESCRIPTION
**Pull request by kroening**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — COMMENTED** [review]
I have "requested changes" on #3073 so cannot yet approve this one I guess ;-) - but it looks ok except for what I said in #3073, which is the first commit of this one.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 5b26875dbaea15604c08322f005711136b63af91).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86462274

**Comment by kroening** [comment]
@tautschnig I've dropped the first commit off this one, then you don't need to feel conflicted.

**Review by tautschnig — APPROVED** [review]

**Review by smowton — APPROVED** [review]

**Review by allredj — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: d17832761db3c214e22f37deab637e45b9142dac).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86484902

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: d17832761db3c214e22f37deab637e45b9142dac).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86497015

**Pull request merged**
