### PR TITLE
Move remaining java tests to jbmc/regression

### PR DESCRIPTION
**Pull request by peterschrammel**

### CODE REVIEW

**Comment by kroening** [comment]
Should these be run, i.e., added to a Makefile?

**Comment by peterschrammel** [comment]
They are run: https://github.com/diffblue/cbmc/blob/develop/jbmc/regression/Makefile#L4

**Review by tautschnig — APPROVED** [review]
Looks good to me, although I'm not sure why they had been left behind?

**Comment by peterschrammel** [comment]
> Looks good to me, although I'm not sure why they had been left behind?

A couple of tests were part of PRs that have been merged after the move (tests were not moved to the correct directory when rebasing them); a few other tests were not part of the initial move (don't know why).

**Pull request merged**
