### PR TITLE
Add z3 package installation to CI pull request checks

### PR DESCRIPTION
**Pull request by thomasspriggs**
Add z3 package installation to CI pull request checks. This will enable subsequent PRs to add tests which require the z3 solver.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by NlightNFotis — COMMENTED** [review]
We probably also need `z3` for the coverage job as well.

**Comment by SaswatPadhi** [comment]
The test case that I had added in #5904 seems to succeed now -- see: https://github.com/diffblue/cbmc/pull/5944/checks?check_run_id=2124973614#step:11:2064.

But the loop acceleration tests seem to be failing now. Checking if my PR caused this ...

**Comment by SaswatPadhi** [comment]
Okay I just tried this on the `develop` branch -- ignoring the changes here (and in #5904). This is what I see:

- If z3 is installed on the system, these tests fail.
- If z3 is not installed, they pass -- they're not skipped.

This makes me think there's some code in the `acceleration` regression tests that "prefers" z3 and uses it when available (and fails because of some bug), but doesn't really "need" it because it runs fine without z3?

**Comment by thomasspriggs** [comment]
> Okay I just tried this on the `develop` branch -- ignoring the changes here (and in #5904). This is what I see:
> 
> * If z3 is installed on the system, these tests fail.
> * If z3 is not installed, they pass -- they're not skipped.
> 
> This makes me think there's some code in the `acceleration` regression tests that "prefers" z3 and uses it when available (and fails because of some bug), but doesn't really "need" it because it runs fine without z3?

There is at least one bug in the implementation of `acceleration` which was causing failures when `z3` is available. I have pushed an additional commit to this branch to fix that issue.

**Comment by thomasspriggs** [comment]
> We probably also need `z3` for the coverage job as well.

Added.

**Comment by thomasspriggs** [comment]
I have raised a separate draft PR to run CI with the combination of installing z3 in CI + the fix from https://github.com/diffblue/cbmc/pull/5904. This CI running PR is here - https://github.com/diffblue/cbmc/pull/5949

**Review by chrisr-diffblue — APPROVED** [review]

**Review by NlightNFotis — APPROVED** [review]
LGTM

**Pull request merged**
