### PR TITLE
fix memcpy overlap check

### PR DESCRIPTION
**Pull request by kroening**
Reported by @danielsn

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4ceba2be1205e882cb02d989a4c3b218645c9057).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93192663

**Review by tautschnig — CHANGES_REQUESTED** [review]
Thanks a lot for the immediate action. Yet could the tests please be moved to regression/cbmc-library?

**Comment by kroening** [comment]
ok

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: e0946d17afd54a50d4e1ab9f333d232ed1dce43b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93223871

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
