### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by reuk**
Several files are never mentioned in any makefiles, and therefore are not built. This patch removes these unused files.

### CODE REVIEW

**Comment by tautschnig** [comment]
@reuk Thanks a lot for this cleanup work. I believe the unit tests ought to be converted to Catch-based ones and it may thus be worth holding off on their removal. See #921. For various other files @kroening's opinion is essential.

**Comment by reuk** [comment]
Modified to keep unit tests.

**Comment by kroening** [comment]
We'll want to keep
src/solvers/floatbv/float_approximation.cpp/.h
and the satcheck_limmat.h/.cpp
files for now; the rest can go away.

**Comment by tautschnig** [comment]
@reuk could you please add the files indicated by @kroening to the Makefiles to make intent explicit? Thank you!

**Comment by reuk** [comment]
I will if they build. If they don't I'll create an issue to fix them, but I'll leave them out of the makefiles for the time being.

**Comment by reuk** [comment]
I can get floatbv_approximation to build, but not satcheck_limmat.cpp, which depends on a header "limmat.h" which I can't find anywhere.

Ready for re-review.

**Comment by tautschnig** [comment]
Thank you!

Would you mind adding
```
ifneq ($(LIMMAT),)
  LIMMAT_SRC=sat/satcheck_limmat.cpp
  LIMMAT_INCLUDE=-I $(LIMMAT)
  LIMMAT_LIB=$(LIMMAT)/liblimmat$(LIBEXT)
  CP_CXXFLAGS += -DHAVE_LIMMAT
endif
```
and add `$(LIMMAT_SRC)` to `SRC = ...` in solvers/Makefile?

(You've already got my approval anyway.)

**Comment by reuk** [comment]
I've made the requested change

**Pull request merged**
