### PR TITLE
Remove bv_cbmct

### PR DESCRIPTION
**Pull request by peterschrammel**
The specializations there are not used anymore.
We can use bv_pointerst directly instead.

### CODE REVIEW

**Comment by kroening** [comment]
While we don't need the particular conversion that bv_cbmct does, it might still be cleaner to retain the fact that cbmc has a parametric, easy-to-replace solver -- say do 'using bv_cbmct = bv_pointerst'?

**Comment by tautschnig** [comment]
Is this possibly used in EBMC? @mgudemann?

**Review by tautschnig — APPROVED** [review]

**Comment by peterschrammel** [comment]
>  it might still be cleaner to retain the fact that cbmc has a parametric, easy-to-replace solver -- say do 'using bv_cbmct = bv_pointerst'?

The parametricity is implemented by using the cbmc_solvers factory. CBMC doesn't require any reference to a specific solver, it only has to know what it is a `prop_convt` (except for counterexample_beautification, which requires a `boolbvt`, and some operations that require an incremental solver, which is currently checked in cbmc_solvers).

**Comment by mgudemann** [comment]
@tautschnig @peterschrammel cannot find any use of `bv_cbmct` in EBMC

**Comment by tautschnig** [comment]
@mgudemann Thanks for digging! Would you mind reviewing/approving this PR?

**Review by mgudemann — APPROVED** [review]

**Pull request merged**
