### PR TITLE
Simplification of nested pointer arithmetic: do not assume same type

### PR DESCRIPTION
**Pull request by tautschnig**
Please review commit-by-commit: the first commit is a refactoring only.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
Does it make sense to tighten the typing rules for pointer arithmetic, and then to change the front-end?
The standard is vague on these, we would need to invent our own.

**Comment by tautschnig** [comment]
> Does it make sense to tighten the typing rules for pointer arithmetic, and then to change the front-end? The standard is vague on these, we would need to invent our own.

I have now extended an existing test: the C front-end already does ensure consistent typing, so I don't think we have an issue in the front-end to resolve. No other place, however, is strict about the types in pointer arithmetic. Perhaps we should be? I don't know.

**Comment by kroening** [comment]
I'd be in favour of tightening the typing; this makes every bit of code that 'reads' a lot easier. There will be more of that than code that 'writes', and that would not get much more difficult.

**Comment by tautschnig** [comment]
> I'd be in favour of tightening the typing; this makes every bit of code that 'reads' a lot easier. There will be more of that than code that 'writes', and that would not get much more difficult.

@kroening As now being discussed in #6731 making changes in Kani could well be the way to go. That said, however, this PR also fixes other issues in the offending simplifier code as indicated in the commit message, so perhaps merging these changes is a right first step?

**Review by kroening — APPROVED** [review]

**Pull request merged**
