### PR TITLE
move string solver into separate directory

### PR DESCRIPTION
**Pull request by kroening**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
This seems to be missing a `git add`, the files have just been removed, not re-added. And likely it will need a `clang-format` with results to go in a separate commit to make CI happy.

**Review by romainbrenguier — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]

**Review by martin-cs — APPROVED** [review]

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 46e21519d6a6c3054ac665a2e011b118c08a3e74).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97658054
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by majakusber** [comment]
Rebased and updated the test-gen pointer bump. Once both pass CI, I'll merge this.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3762599ebba3d032d6808366baea207e37414dbe).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98022743

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 93a0994ac585d49bbc6f75e47064f5703868bde9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98064757

**Pull request merged**
