### PR TITLE
introduce pointer_in_range predicate

### PR DESCRIPTION
**Pull request by kroening**
This adds the predicate `__CPROVER_pointer_in_range` to the C frontend.  The
expression `__CPROVER_pointer_in_range(a, b, c)` evaluates to true iff the
following conditions are met:

1) The three pointers `a`, `b`, `c` point to the same object.

2) `a <= b`

3) `b <= c`

This predicate is an invariant for the standard loop pattern in which a
pointer is used to iterate over an array object, stopping when the pointer
points one beyond the end of the sequence.

The benefit over using `a<=b && b<=c` is that ANSI-C's `<=` operator is
undefined when the two pointers related by `<=` do not point into the same
object.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [X] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by jimgrundy** [comment]
What happens if any of these are invalid pointers? Say "a" has a negative offset or "c" lies (more than one) beyond the end of the object?

**Comment by kroening** [comment]
That's orthogonal.

**Comment by jimgrundy** [comment]
Suppose instead of building a new primitive I instead wrote this function using existing primitives:
```
bool __CPROVER_pointer_in_range(const void *a, const void *b, const void *c)
{
    return __CPROVER_same_object(a, b) & 
           __CPROVER_same_object(b, c) &
           (__CPROVER_pointer_offset(a) <= __CPROVER_pointer_offset(b)) &
           (__CPROVER_pointer_offset(b) <= __CPROVER_pointer_offset(c));
}
```
What would be the difference in behavior and/or efficiency?

(Note I chose & over && here to avoid building conditionals, I think this should build a straight single bit and because I think there are some smarts in CBMC to avoid building int-width bitwise ands in this case, but  perhaps I'm wrong).

If there is no difference why would be build this in as a primitive rather than implement it like this?

**Comment by kroening** [comment]
Standardization!

**Comment by tautschnig** [comment]
A bunch of questions/comments:
- Further to Jim's comment: why would putting it in the C library not accomplish the goal of standardisation?
- Can we please have at least one test?
- Can we please have documentation, which would then need to cover the what-if-pointers-are-invalid case?
- Can support to the SMT back-end please be added as well?
- Nit pick: it would seem more consistent to use `lower()` instead  of `flatten()`.

**Comment by jimgrundy** [comment]
To be clear, I can see the argument for having this function, it's just that if a straight C implementation in the C library accomplished the same thing it would seem like the more maintainable solution.

**Comment by kroening** [comment]
> To be clear, I can see the argument for having this function, it's just that if a straight C implementation in the C library accomplished the same thing it would seem like the more maintainable solution.

It does in CBMC as is. But there's a benefit to having the expression when you do algorithmic search for invariants, say.

**Comment by kroening** [comment]
a. flatten -> lower.
b. Now includes regression test.
c. Strengthened to rule out the 'invalid pointer' case.
d. Implementation in the solvers is no longer applicable, since the 'invalid pointer' case requires lowering at the program level.

**Comment by jimgrundy** [comment]
Why would a function need to be defined as a primitive rather than defined in C in order to be used by an invariant synthesis algorithm? Folks using SyGuS, for example, work off a grammar of basic operations, but being a primitive vs defined is orthogonal to whether or not a construct is in that list of SyGuS operations.

**Comment by kroening** [comment]
> Why would a function need to be defined as a primitive rather than defined in C in order to be used by an invariant synthesis algorithm? Folks using SyGuS, for example, work off a grammar of basic operations, but being a primitive vs defined is orthogonal to whether or not a construct is in that list of SyGuS operations.

Yes. C functions aren't expressions. You won't have "call a C function" in your Sygus grammar.

**Comment by tautschnig** [comment]
Hasn't this actually been merged as part of the CHC PR?

**Comment by kroening** [comment]
Yes, closing

**Pull request closed without merging**
