### PR TITLE
move two builds from Travis to codebuild

### PR DESCRIPTION
**Pull request by kroening**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- n/a My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 0ff28c00fd744787aefa5a0658161ba0fa9405da).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99512699
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 39499cb2118f4d41adbd7a5b540cdbad97bb6935).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99512843

**Review by smowton — APPROVED** [review]

**Review by tautschnig — CHANGES_REQUESTED** [review]
I'm all for speeding up CI, but I can reconcile the changes with the claims of the commit message:
1) Both new buildspec files use `cmake`, while only one of the Travis configurations being removed had done so.
2) None of the new buildspecs use `ctest`, while the `cmake`-based Travis configuration had previously done so.

**Comment by kroening** [comment]
Tweaked to match.
Do we really need that many options and variants?

**Comment by tautschnig** [comment]
> Do we really need that many options and variants?

I think each of them relates to "we once broke the build on exactly that combination?" Yet it might be ok to get rid of some of them until a platform-form specific error comes up again.

**Review by tautschnig — APPROVED** [review]
Looks consistent to me.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: e949b3051a81a2c631b7638c61f6a5d45f738243).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99556154

**Review by forejtv — APPROVED** [review]
:+1:

**Comment by tautschnig** [comment]
@kroening What needs to happen so that these new build configurations are actually enabled?

**Comment by tautschnig** [comment]
@forejtv @kroening Still no trace of additional CodeBuild jobs?

**Comment by thk123** [comment]
Yes I note that I copied one of these to enable testing of the SMT switch (#5259) and in attempting to duplicate the job @JimmehAH discovered that the original doesn't exist...

**Comment by thk123** [comment]
@tautschnig @kroening: @JimmehAH  has just turned these two jobs on on code build and is manually triggering them on develop to see if they've broken in the mean time.

**Comment by thk123** [comment]
@tautschnig @kroening just an update @JimmehAH got these two jobs enabled on codebuild and are now running on develop and new PRs :tada: 

[cbmc-linux-clang](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects/cbmc-linux-clang/)
[cbmc-linux-cmake-gcc](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects/cbmc-linux-cmake-gcc/)

**Pull request merged**
