### PR TITLE
Make json parser unit tests independent of working directory

### PR DESCRIPTION
**Pull request by hannes-steffenhagen-diffblue**
Previous unit test read files from a relative path, this made the unit tests fail or succeed depending on where they're being run from.

This makes the test create some temporary files with the right content and have the rest of the test read those instead.

### CODE REVIEW

**Review by NlightNFotis — APPROVED** [review]
LGTM

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: ed48122edd53a9c5b816ff74379e2861c4892f05).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79459383

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: dd63cc294a1cf7ab532d15790878aab2ea5056e7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79459770
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by sonodtt — APPROVED** [review]

**Review by apaschos — APPROVED** [review]
It looks all good.

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
