### PR TITLE
Increase AssertionError arguments allowed from 2 to 3

### PR DESCRIPTION
**Pull request by JohnDumbell**
There is a constructor for this class with 2 arguments plus implied this.

### CODE REVIEW

**Review by tautschnig — COMMENTED** [review]
Would it be possible to add a regression test, please? The commit message says "There is ..." - is this specific to certain versions of the JDK?

**Comment by JohnDumbell** [comment]
@tautschnig It's there in 1.8 at least, I'll have a quick check to see when it got put in and list the versions.

**Comment by JohnDumbell** [comment]
Looks like it's been in there since 7. What sort of regression test would you want in place for this?

**Comment by tautschnig** [comment]
I am assuming there exists an example that wasn't working as expected before, but now is working as expected? That would be good to have as a test for it would exercise the new code path.

**Comment by JohnDumbell** [comment]
Yep, got one. I'll add that in then.

**Comment by JohnDumbell** [comment]
Sorry it took so long. Added the test.

**Review by tautschnig — APPROVED** [review]
I'm not sure whether the "Update desc file to pass variables." shouldn't be squashed into the prior commit, but that's a nitpick.

**Review by smowton — APPROVED** [review]

**Pull request merged**
