### PR TITLE
Allow to use SAT Solvers with IPASIR interface

### PR DESCRIPTION
**Pull request by nmanthey**
Modern SAT solvers implement an interface for incremental SAT solving, IPASIR. To allow CPROVER tools to use more recent SAT solvers than Minisat or the installed Glucose, SAT solvers can be linked to CBMC by specifying the introduced "LIBSOLVER" make variable during build, which needs to point to a library of such a SAT solver.

### CODE REVIEW

**Comment by peterschrammel** [comment]
@nmanthey, this does not compile at the moment: https://travis-ci.org/diffblue/cbmc/jobs/202519720
Also, please rebase.

**Comment by martin-cs** [comment]
@nmanthey could you have a look at the merge conflicts on this?  It looks to be mostly Makefiles so should be pretty straight forward.

**Comment by nmanthey** [comment]
at least one of the checks fails because the glucose variant of CBMC does not compile. I believe this should still be in the CI checks. I will not fix the glucose based build.

**Comment by mgudemann** [comment]
@nmanthey I started fixing the bugs, there's a bit more to do, the glucose bug was due to us using Alpine Linux with musl, while `fpu_control.h` is glibc. I adapted some parts of your script, current problem is `picosat`, feel free to cheery pick my commits if you are interested

**Comment by nmanthey** [comment]
Closed as PR 884 has been accepted.

**Pull request closed without merging**
