### PR TITLE
Cleanup of uses of get_new_name

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Comment by tautschnig** [comment]
@smowton or someone else with those powers: could a TG bump be set up for this one? I want to make sure there is no subtle breakage, especially with some closely related PRs getting ready for merge (#2252 in particular).

**Review by peterschrammel — APPROVED** [review]

**Review by chrisr-diffblue — APPROVED** [review]
Looks good. @thk123 might want to check the TG bump?

**Comment by smowton** [comment]
https://github.com/diffblue/test-gen/pull/1864

**Comment by smowton** [comment]
Bump status: not good. Guessing some particular name was wanted in trace generation. I'll take a look tomorrow morning and see if I can unstick some of your PRs blocked on test-gen bumps.

**Comment by tautschnig** [comment]
I believe there are cases where previously a `foo$0` was generated when now it might be just `foo`. If that's a problem I can try to restore it, but also I might question whether the test has sound expectations. Or maybe I have introduced some bigger mistake...

**Comment by smowton** [comment]
Looks like it needed a rebase against a recent test-gen change, re-testing now...

**Comment by peterschrammel** [comment]
Bump looks good. I perform some more checks for goto-diff now.

**Comment by peterschrammel** [comment]
No observed change wrt goto-diff. We can go ahead with that.

**Pull request merged**
