### PR TITLE
Adds get_predecessors() to grapht

### PR DESCRIPTION
**Pull request by johnfxgalea**
grapht already has get_successors(). This PR adds get_predecessors().

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by johnfxgalea** [comment]
@martin-cs PTAL

**Review by martin-cs — APPROVED** [review]
Looks good.

**Review by tautschnig — APPROVED** [review]
Looks good to me, but it would be nice to have a test or some other actual use in the code base. Otherwise, the code might not ever get compiled and may silently stop working (for it's templated).

**Comment by johnfxgalea** [comment]
Done. PTAL

**Comment by tautschnig** [comment]
> Done. PTAL

Thank you for adding the test! Can I be a pain and ask for the formatting commit to be squashed into the commit introducing the test? Well, and perhaps also craft a slightly more unambiguous commit message for that one?

**Comment by johnfxgalea** [comment]
> > Done. PTAL
> 
> Thank you for adding the test! Can I be a pain and ask for the formatting commit to be squashed into the commit introducing the test? Well, and perhaps also craft a slightly more unambiguous commit message for that one?

Sorry, I thought you were going to squash and merge via the Github button.

Done.

**Pull request merged**
