### PR TITLE
Visual Studio 2013 -> 2015

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 01a7cdf8e2665632769876effa3c80d96adc31ec).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78902247
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by smowton — APPROVED** [review]

**Review by chrisr-diffblue — COMMENTED** [review]
Looks good. A couple of other places to also consider cleaning up....

doc/cbmc-user-manual.md line 120, should probably drop '2013' (URL now points at 2017)

src/goto-programs/goto_program.h has some preprocessor #if #else #endif to handle Visual Studio <= 2013 - so might be nice to remove that at the same time? Actually, there's a number of places in the code base with macros to handle < 2013...

**Comment by tautschnig** [comment]
In line with what @chrisr-diffblue said: almost all matches of `git grep -w '\(1900\|Ommit\|2013\)'` (sic!) should be considered.

**Comment by peterschrammel** [comment]
We have migrated all Windows builds to AWS CodeBuild now. I've removed the appveyor integration and added a commit here to remove the config as well.

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 70443eae95207833a7688b6410a691d3dce7fd05).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79106783
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Comment by tautschnig** [comment]
> We have migrated all Windows builds to AWS CodeBuild now.

Is it possible to access the logs of those in some way? As is, this seems like a rather contributor-unfriendly step to me.

**Comment by kroening** [comment]
Will squash and merge.

**Comment by peterschrammel** [comment]
> Is it possible to access the logs of those in some way? As is, this seems like a rather contributor-unfriendly step to me.

I'm sure there's a way to set public ro permissions on codebuild...

**Comment by tautschnig** [comment]
> I'm sure there's a way to set public ro permissions on codebuild...

Not that I'm aware of. Or at least: not yet. You'd have to copy the build log to an S3 bucket.

**Review by tautschnig — DISMISSED** [review]
There are couple of items that have been discussed but have not actually happened yet:
1) Public access to codebuild logs.
2) Further cleanup if genuinely moving to VS 2015.
3) A statement of the reason for these changes.

**Comment by peterschrammel** [comment]
> 1. Public access to codebuild logs.

Ok. I'll check with Subin Mathew.

**Comment by tautschnig** [comment]
Furthermore #2495 strictly must be fixed and merged before this one, otherwise we are simply lying to ourselves (cf. `exit 0`).

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 3193d20cfa7becfec557c0632e7c7342f86e8b31).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79186322
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: c4217b47d592d6a5ec8233464cda4974cc121d01).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79207404

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: a41356b6626d875de0174e9e8bfbb037d87220e2).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79271014

**Comment by kroening** [comment]
This is now documentation only.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: bedaa247fb4823b9e35b613293b3598588cac98f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79439716
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 07645543e939322a8a6b8055d9a221b93e817f1a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79440188

**Comment by tautschnig** [comment]
I'd suggest to put this PR on hold until the continuous integration story has been sorted out. While I accept that it is "documentation only", it documents a state that is neither reflected in CI nor in the code base, both of which are geared towards VS 2013. Once CI is sorted out, I would suggest to add the changes that clean up the code base (cf. https://github.com/diffblue/cbmc/pull/2576#issuecomment-404830121) and merge the combined work.

**Comment by peterschrammel** [comment]
>  it documents a state that is neither reflected in CI 

CodeBuild runs VS 2015: https://github.com/diffblue/cbmc/blob/develop/buildspec-windows.yml#L17

**Comment by tautschnig** [comment]
Reviewer is back from holiday. And still thinks that this is incomplete and should not be merged as-is. I accept that the Windows CI may now be using Visual Studio 2015, but its output remains behind closed doors. Much more importantly, though, the code base still has code that explicitly handles the VS 2013 case. Once that's removed this PR makes much more sense.

**Comment by tautschnig** [comment]
Closing as #3894 has been merged, which is the same change.

**Pull request closed without merging**
