### PR TITLE
Fix replace_return

### PR DESCRIPTION
**Pull request by kroening**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
Looks ok, but needs a test.

**Comment by kroening** [comment]
This is hard to test -- a return will always be followed by a goto, so one could even argue that this isn't a bug.

**Comment by tautschnig** [comment]
> This is hard to test -- a return will always be followed by a goto, so one could even argue that this isn't a bug.

Then maybe we should include this in goto-program validation?

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: c6319a22472c6c5ddae00820928c4cb35236f25c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/108829548
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Comment by kroening** [comment]
No, I wouldn't want to make that a guarantee, just to make this particular piece of code work.

**Comment by tautschnig** [comment]
As none of our current front-ends constructs code with two `RETURN` instructions immediately following each other we might just need a unit test? A test constructing a goto program with two return instructions, then running `remove_returns`, and then checking that none of the instructions is a `RETURN` anymore.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 42d464dd5bc73a2cf131eb5da18f8020048eb5ea).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/113794367

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 6a056d5c41e67ad03c7f371cc9fd3c44ac53f8e7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119900991

**Comment by TGWDB** [comment]
@kroening @tautschnig  This looks like it could be merged but is blocked on lack of a test. Can we find a solution to this and merge (or close as not happening)?

**Comment by tautschnig** [comment]
> @kroening @tautschnig This looks like it could be merged but is blocked on lack of a test. Can we find a solution to this and merge (or close as not happening)?

I have added a test that does look at instructions around `return` statements, but, as @kroening said earlier, the particular code being changed does not actually impact functionality. Really, those increment statements were just useless. Or perhaps wrong, but not in any practically demonstrable way.

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
