### PR TITLE
Update test-gen-support from master

### PR DESCRIPTION
**Pull request by thk123**
This brings test gen support up to date with the current master (including, for example, unit testing). 

**Merge conflicts**

 - [`src/cegis/cegis-util/type_helper.cpp`](https://github.com/diffblue/cbmc/pull/941/commits/5c4152bcb989d7b756b36c002768f369459b2d20#diff-6184ca8cd70ae87f3be979118ee225e4) (lint fixes vs. delete)
 - [`src/goto-instrument/cover.cpp`](https://github.com/diffblue/cbmc/pull/941/commits/5c4152bcb989d7b756b36c002768f369459b2d20#diff-5c5e737bf6dd6d1aa2892f71af61a580) (changes in conditionals - needs careful review. lots of `&& !i_it- - >source_location.is_built_in()` @smowton you were last person to touch this file on both branches)
 - [`src/goto-programs/goto_trace.cpp`](https://github.com/diffblue/cbmc/pull/941/commits/5c4152bcb989d7b756b36c002768f369459b2d20#diff-195618b11a32f9b9c39880566d0f6916) (adding DEAD to the goto_trace_stept::output)
 - [`src/goto-programs/goto_trace.h`](https://github.com/diffblue/cbmc/pull/941/commits/5c4152bcb989d7b756b36c002768f369459b2d20#diff-139e50bcd06fa73360fde660539d9cf6) (just an enum specifier)
 - [`src/java_bytecode/Makefile`](https://github.com/diffblue/cbmc/pull/941/commits/5c4152bcb989d7b756b36c002768f369459b2d20#diff-1055c476f8af23237f72e3726a20d127) (just adding one file)
 - [`src/java_bytecode/java_bytecode_convert_method.cpp`](https://github.com/diffblue/cbmc/pull/941/commits/5c4152bcb989d7b756b36c002768f369459b2d20#diff-489726e05da896c8c706122383a4744e) (should just be a comment)
 - `src/java_bytecode/java_entry_point.cpp` (reset back to the test-gen-support version)
 - `src/java_bytecode/java_object_factory.cpp` (chose the version in test-gen-support since apparently all changes have been manually applied by smowton to test-gen-support @smowton is mine/Owen's understanding correct, you may want to verify this merge)

Based on the last point, I selected the test-gen-support versions of `java_object_factory.h` and `java_entry_point.cpp` (https://github.com/diffblue/cbmc/pull/941/commits/adf35dc7e0b221b4332398a24ec92463b6567282)

I also applied some fixes for the enum clean up, @reuk could you [review these](https://github.com/diffblue/cbmc/pull/941/commits/36421e041aab62396ded85714b0c50338dc72856)

Everything else applied cleanly so I assume it is fine. 

This PR is pulled into diffblue/test-gen by diffblue/test-gen#375 (both PRs should should be approved before either merged).

### CODE REVIEW

**Comment by smowton** [comment]
I recommend replacing this with https://github.com/smowton/cbmc/tree/merge-master-20170522, which is the same as yours except for the `java_object_factory.cpp` merge and its users, which favour master (compare this which favours test-gen-support). It also contains a couple of PRs that have hit test-gen-support in the meantime, neither of which introduced any conflicts.

The github compare of those two branches goes completely insane due to merge commits, but here's the diff:

`git diff thk123/update-to-master-19-05-17 smowton/merge-master-20170522`:

[diff-diff.txt](https://github.com/diffblue/cbmc/files/1019282/diff-diff.txt)

**Comment by thk123** [comment]
Taken @smowton's version of the merge due to more up-to-date and takes correct version of `java_bytecode/java_object_factory`.

**Comment by smowton** [comment]
Add a revert of https://github.com/diffblue/cbmc/commit/4c4ccc032919a94753e824c892155a8ca9d55f4a, then we'll be good to go AFAICT

**Comment by thk123** [comment]
@smowton Done - not completely trivial revert since file has changed - but the principle is to add the parameter back in and call it with `false` everywhere (hence removal in first place) then PR on test-gen non longer removes the call with it having not false. https://github.com/diffblue/cbmc/pull/941/commits/8510374598519a4defebb532d02e7a262b14cb6d If you're happ can you approve the PR.

**Pull request merged**
