### PR TITLE
Update java-models-library to diffblue/java-models-library#24

### PR DESCRIPTION
**Pull request by allredj**
Pulls in https://github.com/diffblue/java-models-library/pull/24

Prerequisite for https://github.com/diffblue/cbmc/pull/4760 (String.Format now uses dependency graph).

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by majakusber — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 132bfe09009ce5a83f710b2f72a76e51a8deb87a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114725937

**Comment by allredj** [comment]
now pointing to master

**Review by romainbrenguier — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c6ec6ac4d47132c98b06ef86f588dbb75ccd0709).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114763693

**Review by smowton — APPROVED** [review]

**Comment by smowton** [comment]
@peterschrammel has the power to override the apparent AWS outage

**Comment by allredj** [comment]
subsumed by https://github.com/diffblue/cbmc/pull/4768

**Pull request closed without merging**
