### PR TITLE
cpplint fixes

### PR DESCRIPTION
**Pull request by rjmunro**
Example run of cpp lint sed output (from #553), only on cpp files, with subfolders in their own commits.

### CODE REVIEW

**Comment by peterschrammel** [comment]
Thanks for this, @rjmunro. I suggest to merge #376 first and then run the scripts again.

**Comment by tautschnig** [comment]
I very much appreciate #553 and this one; indeed #376 already does some of the work, but explicitly left out the cegis/ folder, which would be tackled by this one as well. It would certainly make my life much easier if #376 were merged first before doing a run of this one, as @peterschrammel suggested.

**Comment by rjmunro** [comment]
I agree this shouldn't be merged - it is automatically generated, and I can do it again. It would be good if someone who knew C++ and the style guides had a quick browse through to make sure all the changes are good, though. If a change is bad, there is a bug in the sed output, which is not unlikely.

**Comment by forejtv** [comment]
@rjmunro I think you can look at the Cpp Linter output: http://cbmc-linter.diffblue.com.s3-website-us-east-1.amazonaws.com/linter-643da113cb6f91da0bca47708121ef4d4ee40bfc.txt and check if there are any errors that you do not expect.

@thk123 Can you quickly eyeball the diff if you see anything unexpected?

Afterwards this PR can be closed.

**Comment by tautschnig** [comment]
@rjmunro Would you mind re-running (and this sort-of rebasing) on current master? As #376 has kindly been merged, we should now be looking at a novel set of changes. Thanks!

**Comment by rjmunro** [comment]
@tautschnig I've added a few more rules (https://github.com/diffblue/cbmc/pull/558), and re-run the fixer on master and force-pushed the result here.

**Comment by tautschnig** [comment]
I think it would be really nice to have the newline-adding rules enabled in #558 as a huge number of the remaining warnings posted by the linter CI job is now about missing-newline-after-if.

**Comment by kroening** [comment]
Seems ready to go after rebase.

**Comment by rjmunro** [comment]
@kroening Rebased now.

**Pull request merged**
