### PR TITLE
Assignment type consistency

### PR DESCRIPTION
**Pull request by kroening**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by danpoe — APPROVED** [review]
LGTM

**Comment by smowton** [comment]
The bugfix commit suggests adding a test?

**Comment by thk123** [comment]
Just to say I've started looking at this failure and replicating Dan's fix for the Java object factory.

**Comment by smowton** [comment]
@thk123 I may have code for this already, one sec....

**Comment by smowton** [comment]
@thk123 the top 6 commits in https://github.com/smowton/cbmc/commits/smowton/wip/java-frontend-type-consistency are the Java frontend type consistency fixes I haven't had a chance to upstream yet. Mostly they relate to clashes between generic and non-generic types.

**Comment by thk123** [comment]
Superseded by the now merged #3822

**Pull request closed without merging**
