### PR TITLE
Correct can_cast_expr for quantifier_exprt

### PR DESCRIPTION
**Pull request by romainbrenguier**

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]

**Review by smowton — APPROVED** [review]

**Review by kroening — CHANGES_REQUESTED** [review]
This isn't extensible; we don't do this for the other base classes either.

**Comment by smowton** [comment]
Surely if you add a new quantifier, you add to the list?

**Comment by martin-cs** [comment]
> Surely if you add a new quantifier, you add to the list?
Ummmm... how many kinds of quantifier are we planning on...  I can think
of a few but given the underlying logic is first order I'm a little
worried...

**Comment by hannes-steffenhagen-diffblue** [comment]
Why do we even have `can_cast_expr`?  Isn't it basically the same as `dynamic_cast<derived*>(&base) != nullptr`?

**Comment by smowton** [comment]
@hannes-steffenhagen-diffblue it's used internally by the dynamic cast implementation: https://github.com/diffblue/cbmc/blob/develop/src/util/expr_cast.h#L91

Note this is a custom cast, not C++'s builtin dynamic-cast, because the exprt class hierarchy are really reinterpretations of exprt, not extensions, so the vtable pointer can't be used to distinguish different kinds of exprt. In particular, the mutable id() member means an exprt can change classes during its lifetime.

**Comment by kroening** [comment]
I suppose that once we add the lambda the list is complete.

**Review by kroening — APPROVED** [review]

**Pull request merged**
