### PR TITLE
bugfix: use symbol_type for type symbol

### PR DESCRIPTION
**Pull request by kroening**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: b06638c38323364dc094373d936576326f0af9b6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86676708

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 1186cc1b508b75827f2edef108c64e598e36d314).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86707631

**Comment by smowton** [comment]
This indicates code uncovered by our regression tests -- the `fi` family of value-set analyses are more or less dead code, so that's not surprising, but could the others be easily covered?

**Comment by kroening** [comment]
Currently can't be done, since the symbol types are expanded during symbolic simulation. This PR leads to another, which will stop that expansion.

**Review by smowton — APPROVED** [review]
Oh I see, so all these paths were currently unreachable? If so then fair enough

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
