### PR TITLE
Correct make install reference to nonexistent goto-cl->goto-cc target

### PR DESCRIPTION
**Pull request by markrtuttle**
This pull request corrects a windows cmake install command.  The src/goto-cc/CMakeLists.txt defines the goto-cc target with the output name goto-cl.  The install command there refers to the target as goto-cl.  This patch corrects the install command to refer to the target as goto-cc.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by martin-cs — COMMENTED** [review]
IIRC the `goto-cc` program has different behaviour depending on what the binary is called / which platform it is on.  `goto-cc` is the *nix version to emulate `*cc`.  I believe that `goto-cl` is the Windows version to emulate Microsoft's `cl`.  Please check the source code for references to `goto-cl` and what the Windows binary should be called.

**Comment by markrtuttle** [comment]
@martin-cs In src/goto-cc/CMakeLists.txt, the lines

```
if(WIN32)
  set_target_properties(goto-cc PROPERTIES OUTPUT_NAME goto-cl)
  install(TARGETS goto-cl DESTINATION ${CMAKE_INSTALL_BINDIR})
else()
```

specify that the target is named goto-cc but the output is written to a file named goto-cl.  My mistake in the install command was to refer to the target by the file name goto-cl and not the target name goto-cc.  That is what I'm trying to fix.

**Comment by martin-cs** [comment]
Apologies; I am an idiot who doesn't understand the CMake/Windows set up.

**Review by martin-cs — APPROVED** [review]

**Comment by markrtuttle** [comment]
@martin-cs No one working on cbmc is an idiot.

**Review by chrisr-diffblue — APPROVED** [review]
Good catch!

**Pull request merged**
