### PR TITLE
More linter fixes

### PR DESCRIPTION
**Pull request by thk123**
Fixes some more linting false positives and missed cases

- Better handling for types that don't end in t (don't get tripped up if the type is a reference for example)
- Removed false positives for  `<<`
- Fixed error message about constant sized arrays
- Added check for position of &/* on reference/pointer types (and updated the coding guidelines to make this explicit.)

### CODE REVIEW

**Comment by tautschnig** [comment]
Moving forward, are there any intentions of bringing back all those improvements to upstream (https://github.com/cpplint/cpplint) ?

**Comment by thk123** [comment]
@tautschnig Cheers for the quick merge! I don't know @peterschrammel original intention - it would obviously be nice, but I fear a lot of the changes have been made in ways to make it more bespoke to our use case rather than general improvement. What do you think Peter - is it worth trying clean up something to push back up?

**Comment by peterschrammel** [comment]
I doubt that there are much general improvements to be pushed upstream -- the changes we made are mostly adaptations to fit the idiosyncrasies of our coding standard.

**Comment by tautschnig** [comment]
Then that's fine of course - just keep this in the back of your minds as we should obviously seek to work as closely with upstream as possible so as to have the latest and greatest version at all times.

**Pull request merged**
