### PR TITLE
Use sanitizers in travis

### LINKED ISSUE #832: Use clang address sanitizer in linux/clang CI
Following on from #831:

The clang address/leak sanitizer doesn't particularly slow down execution of CBMC. Enabling it in our continuous integration might help to catch memory issues that otherwise go un-noticed and un-fixed, like #569.

### PR DESCRIPTION
**Pull request by reuk**
Fixes #832 

I don't have a way of testing this locally, please don't review until the CI is showing all green.

### CODE REVIEW

**Comment by reuk** [comment]
This works now, although it does cause some of the builds to time out. Not sure how to proceed.

**Comment by peterschrammel** [comment]
@reuk, I'd suggest to enable it only for one of the builds. All builds taking 60min doesn't look viable.

**Comment by reuk** [comment]
I think the problem is that the failing builds use both the undefined-behaviour and address sanitizers, while the succeeding builds use only the address sanitizer. Because each sanitizer slows down execution a bit, the builds with more sanitizers take longer than 50 minutes, at which point they time-out. However, it's important that we run all the tests with sanitizers on, as sanitizers only find errors in code which is actually run.

Even if all sanitizers are enabled just for a single build, that build will still time-out. Therefore, I suggest either:
- Find a way to increase the timeout, and enable all sanitizers on a single build, or
- Run the sanitizers one at a time (that is, add some extra configurations to the build matrix), or
- Use [build-stages](https://docs.travis-ci.com/user/build-stages/) to separate the build + test steps, which would hopefully give us 50 mins for each build, and an additional 50 mins for running tests.

**Comment by reuk** [comment]
Still waiting for guidance on this. I think it's really important to use the sanitizers in Travis, but I'm not sure about the best way to proceed.

**Comment by tautschnig** [comment]
I'd say build stages should be the way to go, in fact irrespective of the sanitizers. If that solves the timeout issue then that would of course be desirable, else one of the other options you proposed will need to be applied. Would you be able to invest time to implement build stages support?

**Comment by reuk** [comment]
I have this afternoon, but I don't think this will be practical to fix today because Travis is so busy, due to the bug squashing party.

**Comment by tautschnig** [comment]
This is superseded by #1624.

**Pull request closed without merging**
