### PR TITLE
Escape backslash in generated tests [Hotfix]

### PR DESCRIPTION
**Pull request by LAJW**
Test-gen PR: https://github.com/diffblue/test-gen/pull/914
Somewhat related to this issue: https://github.com/diffblue/test-gen/issues/194

### CODE REVIEW

**Comment by tautschnig** [comment]
Don't you also need to escape `\t` and a few others in this function?

**Comment by LAJW** [comment]
@tautschnig Yup, [`\t`, `\f` and `\b` remained](http://www.informit.com/articles/article.aspx?p=30241&seqNum=3). Found a connected issue. All other characters don't seem to require escaping.

**Comment by tautschnig** [comment]
You will not be surprised that I looked at `MetaChar` from `c_misc.cpp` to remind myself of what may need escaping.

I thought we had just gone through this in #1201?

**Comment by LAJW** [comment]
`MetaChar` is different in two ways: escapes characters C-style (`\v` and `\a` for example) and takes `std::string` rather than `std::wstring` as an input. I tried to swap implementation of this to_java function with `MetaChar`, but those C characters cause compilation errors in java.

It seems the only sensible way is to have two separate implementations/front-ends - one for C and one for Java.

**Comment by tautschnig** [comment]
> It seems the only sensible way is to have two separate implementations/front-ends - one for C and one for Java.

I'd strongly disagree. The fact that this piece of code you're patching here had to go through several iterations when we had a function that almost did the trick all along should suffice as argument.

1. Get rid of `c_misc` and name it sensibly, placing it in util/
2. Add an option to disable escaping for C-only characters.
3. Be happy.

**Comment by romainbrenguier** [comment]
@tautschnig you forgot about the `string` / `wstring` distinction

**Comment by tautschnig** [comment]
> @tautschnig you forgot about the `string` / `wstring` distinction

I ignored it. All cases with `ch<=255` should not differ beyond what's said above.

**Pull request merged**
