### PR TITLE
Fix for cbmc running out of memory while printing traces using json_ui

### PR DESCRIPTION
**Pull request by NlightNFotis**
There has been a bug reported to us where `cbmc` would run out of memory while creating a huge json object in memory to report the traces with. This is changing the tracing report facility to use a new json class that streams the objects immediately as created, and therefore fixes the issue.

### CODE REVIEW

**Comment by peterschrammel** [comment]
@NlightNFotis, do you have evidence that this now indeed fixes/mitigates the problem?

**Comment by peterschrammel** [comment]
As discussed directly, to avoid conflicts with the current rebasing efforts, I will not make a PR for the`json_streamt` refactoring for `develop`. It will hit `develop` through `goto-analzyer-develop` (merge expected to happen in March).

**Comment by martin-cs** [comment]
Follow-up from chatting with @peterschrammel and @NlightNFotis : goto-analyzer-develop will not be directly merged, so a PR against develop would be good as well.

**Comment by NlightNFotis** [comment]
This was the first attempt at solving the problem with `jsont` causing out of memory problems while printing some traces. It has been superseded by #1814 which is now merged, therefore this PR should now be able to be closed without any issues.

**Pull request closed without merging**
