### PR TITLE
Remove unused ID_free and related methods

### PR DESCRIPTION
**Pull request by smowton**
It appears to be impossible to create a free statement (as opposed to a call to stdlib's free); therefore this path can't be exercised. All the better, since updating everyone's pointers (rather than tracking allocated / deallocated status with the object itself) is surely a mistake in any case.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- ~Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.~
- ~Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).~
- ~My commit message includes data points confirming performance improvements (if claimed).~
- [x] My PR is restricted to a single feature or bugfix.
- ~White-space or formatting changes outside the feature-related changed lines are in commits of their own.~

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: acc15f69b5326cbf6a5323fee13938bf401473a7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87651924

**Review by martin-cs — COMMENTED** [review]
If ```ID_free``` is really unused, then can we also take it out of the list of valid irep IDs?

**Review by tautschnig — APPROVED** [review]
I'm with @martin-cs: can we please kill any use of `ID_free`? I don't mind whether done in this PR or a follow-up one and thus approving. Maybe @kroening can confirm that this is the way to go?

**Comment by smowton** [comment]
Updated; @kroening can you confirm if this is ok? Is there perhaps a secret out-of-tree user that creates a codet with statement == "free"?

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 35cfbb8004072aa2d1aba5610f687ed2ea12dd80).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87744962

**Review by owen-mc-diffblue — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]
For @kroening to confirm.

**Pull request merged**
