### PR TITLE
Silence warnings about unused parameters [blocks: #2310]

### PR DESCRIPTION
**Pull request by tautschnig**
Their names are useful to understand the purpose of the function and/or are part
of Doxygen documentation, and thus cannot be removed.

### CODE REVIEW

**Review by chrisr-diffblue — COMMENTED** [review]
I'm more ambivalent about these changes to silence Visual Studio compiler warnings that the other recent PR's on this topic. Would it be worth at least adding a ` // silence compiler warning` comment with each the new `(void)` uses that have been added in this PR?

**Review by peterschrammel — COMMENTED** [review]
I prefer this PR to #2468.

**Comment by tautschnig** [comment]
> I prefer this PR to #2468.

Note, that they are currently complementary: where I deemed the parameter named valuable I've added a `(void)parameter;` - in other cases I've just removed the named (#2468). But I'm happy to consistently do `(void)parameter` (and add the comment that @chrisr-diffblue suggested) - just let me know!

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 5cabcea4b62c47b54f41b90c4bd6167d58309e37).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77257469
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: a13922331f8ccdd0e345461b6b6840429a8c32cd).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78365264

**Comment by tautschnig** [comment]
As just said in #2468: @chrisr-diffblue, @peterschrammel  I have created #2568 as a proposed amendment to the coding standard.

**Comment by tautschnig** [comment]
Rebased, updated, comments added.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: dc2489d3e3c1cf5c43b11eddc2c71d9a1fa0dc7d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78561014
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by smowton — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]
@tautschnig, needs a rebase.

**Review by martin-cs — APPROVED** [review]
I'm not opposed but I think that changes to the linter / clang-format / CI are a better way of approaching this sort of thing.

**Comment by tautschnig** [comment]
> I'm not opposed but I think that changes to the linter / clang-format / CI are a better way of approaching this sort of thing.

I don't think it's within the capabilities of a linter or formatter to detect those problems, but compilers would. Enabling this in CI is part of #2310, which this PR is factored out from.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: ab6255b7d6dd8d80250f582086f712c8633e089b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90533681

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: ffb6f4941a0a6689f1a6f8a9d35f40d903b1cccf).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90581220
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by kroening — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:warning:
Diffblue compatibility check is currently unavailable.
Please create manual bump.
(cbmc commit: 748533aaffdcca658023af0d848bbbf9af423ef1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90847630

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 359b3b154e0a424afac38549b99c9f0a2ca5b188).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90955657

**Pull request merged**
