### PR TITLE
Remove the headers for the validity regions pointer analyses

### PR DESCRIPTION
**Pull request by martin-cs**
*. These are not built or used by the current develop.
*. pointer_analysis/*_fiv*.cpp were removed long ago so there can't be
   current out-of-tree users.
*. #5020 removed some of these with
   063db535c10d7b26fe8d40283044f8f1102f77da noting:
   "These are unused in the code base,
    and there are no plans resurrect them."

### CODE REVIEW

**Comment by martin-cs** [comment]
I have a nasty feeling that globbing in the CMake files may mean that they were built by CMake but not by Make.

**Review by tautschnig — APPROVED** [review]
Thank your for this cleanup! Yet it seems there's Doxygen doc that's still referring to these, which now also needs to be cleaned up.

**Comment by martin-cs** [comment]
Documentation updated to match the code!

**Comment by martin-cs** [comment]
@chris-ryder and @peterschrammel a third quick one if you have a moment.

**Review by chris-ryder — APPROVED** [review]

**Comment by martin-cs** [comment]
Thanks @chris-ryder .  I have rebased and will merge once CI passes.

**Pull request merged**
