### PR TITLE
Simplify codebuild build for codecov

### PR DESCRIPTION
**Pull request by danpoe**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- n/a Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 64bd1d0d6597f4a336875e5496ee5a4569d73502).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121288637

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: bfddeca6032470c9a4aefdb30da6b720b20bc0c5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121293763

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 206be76173794ff3974120d895213e3567332cf2).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121302324

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 5ff95bd27b3cbdf1ae5050402381ea06005359b7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121403086
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: fb8b230c4c21714aa8702912f5707ba630aed41a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121439311
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 1d7ede4f18303692ad5b2ceb851c58c70502f4dd).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121445216
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by yumibagge — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]
The commit message body should describe the 'why'.

**Comment by tautschnig** [comment]
@danpoe Just requires updating the commit messages as @peterschrammel said.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f94ba36daae82ada0c067ea0fd9f33b7d755a330).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/122020275

**Pull request merged**
