### PR TITLE
[REFACTOR] Move `parse_options.cpp` and `cmdline.cpp` under `src/cli_utils/`.

### PR DESCRIPTION
**Pull request by NlightNFotis**
We want to start breaking down the `src/util/` folder in a manner that makes its constituents more organised in a logical hierarchy and also to allow us to set up better boundaries between different modules (and allow the build system to evolve in a way that allows more selective inclusion of different components in a library built).

---

There's still work to be done here (we expect the `Make` builds to fail as we haven't ported the make built to the new hierarchy yet), but we want to make sure that the community aligns with our aims and process here before we commit to more (tedious) work.

### CODE REVIEW

**Comment by tautschnig** [comment]
I'm afraid that we'll end up with a very large number of folders right under `src/` if we go down this route. You might want to first explore introducing sub-folders in`src/util/`.

**Comment by tautschnig** [comment]
As a further note: can we take a first small step and move `log_version_and_architecture` to `config.cpp` so as to remove the dependency on `config.h` from `parse_options.cpp`? I suggest we eventually separate out everything that doesn't (transitively) depend on `irep.h` (and should try to make that set of files as large as possible).

**Comment by thomasspriggs** [comment]
> I'm afraid that we'll end up with a very large number of folders right under `src/` if we go down this route. You might want to first explore introducing sub-folders in`src/util/`.

@esteffin Can you explain the build-system related concerns you had about that? I guess the way `/src/util/CMakeLists.txt` is currently written using `GLOB_RECURSE` means it would automatically include the `.cpp` files in a `/src/util/cli/` directory. But could we just switch to using just `GLOB` in order to retain management of the two directories as two separate modules?

**Comment by esteffin** [comment]
@tautschnig 
The aim of this PR was to start splitting the `util` library as it is growing feeling that it has to be split in separate units such as `irept` and derivatives, global components such as `optionst` and components for executable creation such as `parse_option_baset` (that was moved here).

However the extent of the work mean that the split will happen in a number of separate PR with the outcome of having an unstabilized `util` for a while.

To avoid an organic split, that can affect the final outcome, we decided to open an RFC (soon to be created) where the fate of `util` will be detailed and discussed both in term of folder structure and in term of build system and artifact produced.

I will leave this PR open and reference it in the RFC, but it will be unlikely progressing until a more consensual decision on the structure of `util` will be taken.

**Comment by NlightNFotis** [comment]
Similar to #8110 , I don't see having the time to see this through any time soon, therefore I will close this PR in an attempt to keep the repository tidy.

If anyone wants to work on this one and get it merged, feel free to re-open this PR, or to use the branch as a basis for a separate PR. Thanks for your understanding.

**Pull request closed without merging**
