### PR TITLE
add an implementation of std::variant<...>

### PR DESCRIPTION
**Pull request by kroening**
This appears to require update 3 of MSVC 2015, which may be an issue.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
I don't usually like introducing dependencies, but this one will disappear by itself with time.

**Review by smowton — APPROVED** [review]

**Review by tautschnig — CHANGES_REQUESTED** [review]
I'm not particularly convinced we need this, but should there genuinely be a use case we need tests (cf. unit/util/optional.cpp), and possibly documentation, though tests would also serve as such. As is, we have no idea whether this passes CI.

**Review by LAJW — APPROVED** [review]
😱  👍 🥕 Let's make it happen!

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 83f53a7b650082aaa8c362c05b60032d69a2c6a4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98995273
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: b10a24eaca26a3e5578ed6eaf423e0ef92cdf96a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99566510

**Review by thomasspriggs — APPROVED** [review]
Looks really useful. I notice that the upstream repository for this includes tests. Maybe we should copy over the tests as well, so this can be tested on CI.

**Comment by thk123** [comment]
I had a quick look at the upstream tests - they are written in GTest - I think rewriting them in catch would be time consuming and error prone. Instead - I suggest including this as a submodule so we can trust that the tests are run by the upstream CI. Alternatively, we could run the tests on our CI - but would involve adding a dependency on gtest for CI. (closed by mistake!)

@tautschnig for motivation - I think if this had existed when `symbolt` or `goto_trace_stept` had existed their design would be more robust. Can encode the different types of symbol (e.g. function symbols have a `code_typet` rather than a `typet`) but keep the value semantics, don't have awkward class hierarchies.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: ffca144281299cb5f7325150da83eb87b0ae5648).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102486684

**Comment by kroening** [comment]
`goto_trace_stept` is certainly an obvious "customer"; should we use that as trial?

**Comment by thk123** [comment]
@kroening in principle yes, I worried in practise that something that central would be a very large undertaking. I proposed it as a "motivating example" to demonstrated there are use cases on the assumption that other uses cases that are less entwined was also crop up.

**Comment by thk123** [comment]
Added as a submodule in #4344 if people would like to review that as well.

**Comment by TGWDB** [comment]
This PR appears like it could be useful if rebased, any chance of this being revisited (or should we consider closing as too old and out of date)?

**Comment by TGWDB** [comment]
@tautschnig This PR now passes all CI and is waiting only on your requested change, can you please have a look?

**Comment by TGWDB** [comment]
Closing due to age (no further comment on PR content), please reopen with rebase on develop if you intent to continue this work.

**Pull request closed without merging**
