### PR TITLE
GitHub actions: Ubuntu 22.04 [depends-on: #6901]

### PR DESCRIPTION
**Pull request by tautschnig**
Use the most recent available GitHub runners (which is currently in
public beta). For Ubuntu we now have coverage of 18.04, 20.04, 22.04.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by NlightNFotis — APPROVED** [review]
I'm happy with the change to MacOS 12 (given that all my machines use that) and I can support it if need be.

But I want someone else to chime in for Ubuntu 22.04, because I don't  have easy access to an Ubuntu machine.

**Comment by tautschnig** [comment]
Thanks @NlightNFotis . I'll also need someone with sufficient admin privileges (@peterschrammel ?) adjust the set of CI checks that are marked "Required" for I have replaced (and renamed) two of the existing tests.

**Review by TGWDB — CHANGES_REQUESTED** [review]
Can you please split this to two separate PRs for the different OS's. We don't currently have a Ubuntu 22.04 environment we could ensure good development on, but we can progress on MacOS for now.

**Comment by thomasspriggs** [comment]
> But I want someone else to chime in for Ubuntu 22.04, because I don't have easy access to an Ubuntu machine.

I currently use a Ubuntu 20.04 machine and I am expecting to upgrade to 22.04 within the next 2 months. So I am not yet setup to vouch for the support level on 22.04 or to investigate any 22.04 related issues.

A a couple of other points to consider -

- How many versions of Ubuntu should we really be aiming to support? There is some overhead in making sure we have machines (or VMs) available for all 3 versions of Ubuntu which you are proposing we use for the PR checks. As well as debugging any build issues across all these versions.
- There is also the release packages to consider and we should bear in mind ensuring that we are running PR jobs for versions of Ubuntu / cmake which match the release packages. Otherwise we may risk version specific breakages being introduced which are only spotted at release time.

I would be more in favour of moving from testing / producing release packages on 18.04 and 20.04 to 20.04 and 22.04 as opposed to spreading our efforts over 3 versions. @jimgrundy Do you have any opinion on which versions of Ubuntu we should be supporting with release packages?

**Comment by tautschnig** [comment]
Ubuntu is still providing maintenance updates for 18.04 (https://ubuntu.com/about/release-cycle), so I'd rather not see us drop support for this platform. Also, the Kani team is aiming to continue to support 18.04 for the time being, so I don't think we should drop support for this platform just yet.

My main goal in adding the most recent runners was to detect problems early, even when perhaps we wouldn't have release packages for these platforms. I'd rather not be in a position where some user has to file an issue for they can't compile or can't run CBMC on their platform.

I'll create a new PR for macOS 12 only, and will leave this one to handle (and discuss) Ubuntu versions.

**Comment by TGWDB** [comment]
We're running into the problem of having a large number of OSs and build systems and needing to support them all. I appreciate that changing `20.04-make-clang` to `22.04-make.clang` is not too significant since we still have `20.04-make-clang-smt-z3` and so we should have the build covered. But in the other direction we're not significantly covering 22.04 yet (just one job).

I'm happy to approve for now, but note that this should be treated with some caution.

**Review by TGWDB — APPROVED** [review]

**Comment by thomasspriggs** [comment]
> My main goal in adding the most recent runners was to detect problems early, even when perhaps we wouldn't have release packages for these platforms. I'd rather not be in a position where some user has to file an issue for they can't compile or can't run CBMC on their platform.


The cmake build is explained in compiling.md before the make build. So users are more likely to be trying to build cbmc using cmake, than with make. I'd suggest we add a Ubuntu 22.04 + cmake + gcc job instead. We could make it a build only job, if we are concerned about CI resources.

**Comment by tautschnig** [comment]
> > My main goal in adding the most recent runners was to detect problems early, even when perhaps we wouldn't have release packages for these platforms. I'd rather not be in a position where some user has to file an issue for they can't compile or can't run CBMC on their platform.
> 
> The cmake build is explained in compiling.md before the make build. So users are more likely to be trying to build cbmc using cmake, than with make. I'd suggest we add a Ubuntu 22.04 + cmake + gcc job instead. We could make it a build only job, if we are concerned about CI resources.

Done: I've now added that additional job.

**Pull request merged**
