### PR TITLE
Enable compile command output

### PR DESCRIPTION
**Pull request by reuk**
Make CMake emit a compile-commands database which can be used in conjunction with code completion tools (YCM) and static analysers (clang-tidy).

### CODE REVIEW

**Review by LAJW — COMMENTED** [review]
I don't think that this change is necessary as it's only relevant to Vim and Emacs developers, who probably already know to run this on their own.

**Review by thk123 — COMMENTED** [review]
De ja vu? Didn't I already say this seems fine but I don't really understand what it means? Based on @LAJW comment - it seems like it maybe shouldn't be on by default but instead be configurable without editing the CMakeLists.txt. I don't know what the CMake way of doing that is, but you might consider doing that.

**Comment by LAJW** [comment]
@thk123 I posted my comment here first, then noticed that the discussion was happening on the other repository, so copy-pasted it there.

To use it without storing it inside CMakeLists.txt, one just needs to run:
 ```cmake -DCMAKE_EXPORT_COMPILE_COMMANDS```
while configuring the project. As an Emacs/Vim user I got used to running that manually. I'll approve if someone else is convinced, that it should be in the main `CMakeLists.txt`.

**Comment by reuk** [comment]
We need it once in CBMC and once in test-gen. The rationale for always generating the `compile_commands.json` file is that it doesn't slow the build down or affect those who don't need the file, but it makes life easier for people who *do* need it. It doesn't really have drawbacks, but it does have the benefit that users don't have to remember to supply the required CMake flag.

**Review by thk123 — APPROVED** [review]

**Review by LAJW — APPROVED** [review]

**Comment by reuk** [comment]
@thk123 Could you merge this please?

**Pull request merged**
