### PR TITLE
Remove exceptions pass: ensure consistency and improve exit sequence generation

### PR DESCRIPTION
**Pull request by smowton**
The remove-exceptions pass previously generated stripes of DEAD instructions whenever an exception could throw, but these were (a) redundant, in that repeated exception dispatch sequences did not share an exit sequence even when branching from the same try-block to the same catch, and (b) incomplete, in that they only killed locals belonging to the innermost try-block.

This PR amends it to share DEAD sequences when possible, and to ensure all try blocks' locals are killed as appropriate. In pathalogical cases this can reduce GOTO program size tenfold. It also fixes a couple of minor bugs exposed by the remove-exceptions rewrite: that a CATCH-POP could sometimes be omitted completely, and that CATCH-PUSH and POP instructions were not given source locations correctly.

The tests verify that on all paths in some test programs, all declared variables are killed. They do not ensure perfect balancing of DECL and DEAD instructions, because doing that correctly requires restoring the lexical block structure that is present in `codet` but absent in GOTO form -- some variables that are not currently live may be killed. This should be harmless, as no analysis to my knowledge insists that the instructions are well paired.

### CODE REVIEW

**Comment by smowton** [comment]
TG bump: https://github.com/diffblue/test-gen/pull/1560

**Comment by thk123** [comment]
@allredj should definitely look at this as the person most recently concerned with exceptions (in particular might be able to spot some bugs that this fixes we can close)

**Comment by allredj** [comment]
I will have a look, but it's @romainbrenguier who did some actual work in this field, so his opinion will have more value.

**Comment by smowton** [comment]
There is a specific test-gen test (HashMap / CustomClass / testNonDet) where this somehow doubles peak memory usage from 3GB to 6GB. Need to investigate why before merging.

**Comment by smowton** [comment]
I'm not 100% certain, but it looks like the cause is either (a) killing things that were accidentally left alive before, and/or (b) killing things that were never alive, due to the imprecise live-variable analysis described above. Both cases cause the "x$object" failed-dereference symbol to be placed in symex's value-set, which in turn may mean larger nested-if statements created when resolving dereferences.

I'll leave this alone for now, but possible things to try:
* "Proper" live-variable analysis, rather than try-block granularity analysis as at present.
* Measure more precisely what kind of ireps are being created to cause the 100% memory footprint increase we're observing
* Determine whether symex could omit the failed-object for Java allocations altogether.

**Comment by smowton** [comment]
https://github.com/diffblue/cbmc/pull/1916 fixes the memory blowup, but it still impose a ~33% running time penalty on some test cases. Will investigate the cause in a spare moment; for now this is back-burnered.

**Comment by TGWDB** [comment]
Closing as this appears to be long forgotten. Please reopen and update if you plan to continue working on this.

**Pull request closed without merging**
