### PR TITLE
Factor out charAt() and startsWith() simplification into separate functions

### PR DESCRIPTION
**Pull request by danpoe**
The diff for this PR is a bit unhelpful. The PR simply moves the code that implements simplification of `charAt()` and `startsWith()` from `simplify_function_application()` to `simplify_string_char_at()` and `simplify_string_startswith()`, respectively.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 9503c4951757db2210da232290f1cebd3541b5e8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/118970054

**Review by smowton — APPROVED** [review]

**Comment by tautschnig** [comment]
@danpoe Could you please rebase this one so that the spurious CI failure (failure to parse an APT key, should be transient) is resolved?

**Review by allredj — APPROVED** [review]
Not particularly easy to review, because the diff is so weird, but it looks basically alright.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: ca203b905e04fefaeae34c90381fff1cef9a4b27).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119392278

**Pull request merged**
