### PR TITLE
Fix simplification of logical right shift of signed bitvectors

### PR DESCRIPTION
**Pull request by tautschnig**
All language front-ends generate arithmetic shifts for signed bitvectors, but
goto-programs still support logical right shift for both signed and unsigned
bitvectors. Thus the simplifier also needs to handle them correctly.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c72c8c16feb6ae612b7a694678d10aa2d164f79b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96418866

**Comment by kroening** [comment]
BTW, Java does have a logical right shift operator (`>>>`).

**Review by kroening — APPROVED** [review]

**Comment by tautschnig** [comment]
> BTW, Java does have a logical right shift operator (`>>>`).

Oh, thanks, I have added a test to exercise that (although jbmc/iarith2 already did to an extent) and have updated the commit message.

**Comment by kroening** [comment]
Many thanks!

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: cfb691928cbea4a741d678834cd7ef3084848f16).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96463045

**Pull request merged**
