### PR TITLE
introduce ID_array_comprehension

### PR DESCRIPTION
**Pull request by kroening**
The ID is introduced to avoid an inconsistency between class name and the ID
that was introduced with 2fbe5e1e29.

This will allow the introduction of lambda expressions, to mean nameless
(mathematical) functions.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by smowton** [comment]
I didn't do this when naming `array_comprehension_exprt` because I thought it would break GOTO binaries -- should this be reserved for a major release?

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: b5ad3e432db7c944c9029efcecafb015fee07daa).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/122237743

**Review by tautschnig — CHANGES_REQUESTED** [review]
Looks good, but as @smowton said this requires a bump of the goto binary version.

**Comment by kroening** [comment]
No, there is no way to get that into a goto binary.

**Comment by tautschnig** [comment]
> No, there is no way to get that into a goto binary.

Ah, the only places that generated an `array_comprehension_exprt` were back-end components and thus it was never written to disk.

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
