### PR TITLE
taint_analysist isn't a messaget [blocks: #3800]

### PR DESCRIPTION
**Pull request by tautschnig**
Pass a message handler to the methods that use it. Also make use of
conditional_output to avoid generating a debug string (instead of just not
printing it).

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 79ccaa37d1c799e5a2b3b16daa1a2035aeb4e0fe).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99552621

**Comment by kroening** [comment]
Argument lists are getting long -- simply make that `log` a member?

**Comment by tautschnig** [comment]
> Argument lists are getting long -- simply make that `log` a member?

Done!

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 17d7dbb2b296ebdb5165dfbdf270231a0286aed4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100292616

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 38f23b028212903a4fcada7b8f1125e1d659a054).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102433787

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f8b49a0a2c276720293ac8c59790f7f35a04544f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103463260

**Pull request merged**
