### PR TITLE
Remove long deprecated methods

### PR DESCRIPTION
**Pull request by tautschnig**
The first commit is #4423, the other commits are new. This is a cleanup of all entities that have been marked deprecated for more than 6 months except for

1) Cleanup already in pull requests and
2) the procedures in the string solver - they have been marked as deprecated since 2017, but actually removing them (where this is even possible, there are still in-tree uses) causes tests to fail.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by martin-cs — APPROVED** [review]
"One of my most productive days was throwing away 1,000 lines of code."

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 9eb60159870b54cba1c4e2cb3aaf0dc395903fc9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105559553
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: b8c5745b992b6b41d135ef9203f79a00d71ff152).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105560177
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 5f332e4d9ba44026c56b12f1a4e7b5777fa1286d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105570026
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Comment by kroening** [comment]
My only problem with this is the removal of
```
side_effect_exprt(const irep_idt &statement, const typet &_type)
```
in favour of a variant with `source_locationt`. We don't do that agenda consistently for all expressions, and it's unclear why that one is singled out.

**Comment by tautschnig** [comment]
> My only problem with this is the removal of `side_effect_exprt(const irep_idt &statement, const typet &_type)` [...]

Maybe it should just never have been deprecated in the first place? I have no issue not removing that constructor, I just did a rather mechanic removal of long-deprecated constructors. Please advise.

**Review by smowton — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Comment by tautschnig** [comment]
I have now left those constructors that only differ from non-deprecated ones by a `source_locationt` parameter in the code base. Will merge once CI passes, but we still need to consider whether the deprecation markers should be removed.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 6409b21263f961074c203304449e6bc2ba7c10c4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105802020
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Comment by thk123** [comment]
Updated TG - rebasing this should get the Joel bot to pass

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: d794d17f748f3b9ac2dbbc6ecf8990043c491920).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105859717
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Pull request merged**
