### PR TITLE
Check some assumptions about goto programs before starting an analysis

### PR DESCRIPTION
**Pull request by tautschnig**
The current set of checks is certainly very incomplete, but at least provides
some entry points for adding further tests.

This is a first attempt to address #751, and mainly intended as a basis for discussion. All input and contributions very much welcome!

### CODE REVIEW

**Comment by martin-cs** [comment]
Yes; that was pretty much what I was thinking.

**Comment by tautschnig** [comment]
FWIW, the output of the failing tests is now worth looking at. I'd argue some actual cleanup in goto conversion is due.

**Comment by martin-cs** [comment]
I've got this on my "list of reviews required" and would love to see this moving.  What is the current status?  "I don't have time right now" will be the default if I don't hear from you.  Perhaps that will motivate me to make the time :-)

**Comment by tautschnig** [comment]
Status is: needs a time generator. It would be really important, but there are other tasks with an earlier deadline...

**Comment by martin-cs** [comment]
OK; ping me if you get time before I do :-)

**Comment by tautschnig** [comment]
Closing as this has now been implemented properly and is run with `--validate-goto-model`.

**Pull request closed without merging**
