### PR TITLE
Update compilation instructions to install jq

### PR DESCRIPTION
**Pull request by karkhaz**

### CODE REVIEW

**Review by kroening — APPROVED** [review]

**Comment by smowton** [comment]
I'd intended `jq` to be a soft dependency, so it didn't hobble people only interested in `cbmc` -- did that not work for you? If it did, suggest noting this is optional.

**Comment by smowton** [comment]
(for example: https://github.com/diffblue/cbmc/blob/12bce1707be235dc2f7b0f9e07f71b743015c0b4/jbmc/regression/jbmc-json-ui/Makefile)

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c37284f653e62e56d1e9cf3034643b448461fc07).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/101277070

**Comment by kroening** [comment]
@smowton Many thanks for being considerate about the dependency war!
I think @karkhaz's wording is fine.

**Comment by kroening** [comment]
https://xkcd.com/797/

**Comment by karkhaz** [comment]
I could make it even more explicit, i.e.
```
You also need jq if you wish to run the test suite.
```
instead of
```
You also need jq to run the test suite.
```
will do this soon. Currently sorting out the mother of all rebase conflicts, so can't check this branch out until I'm done...

**Comment by kroening** [comment]
@karkhaz Note that Chris' scripting even takes care of `jq` missing, i.e., you could say "You also need jq if you wish to run the entire test suite."

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 94b66d3d1f4de3f6a799cf572f4a9dabe11df90c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103086040
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Pull request merged**
