### PR TITLE
Move goto_statet and framet to their own files [blocks: #4302]

### PR DESCRIPTION
**Pull request by romainbrenguier**
No functional changes.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [na] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [na] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — COMMENTED** [review]
It's probably a good idea, but also doesn't seem particularly urgent to me. Several existing PRs conflict with the changes proposed here, and rebasing with code moving between files is really painful. I'll thus refrain from approving until those other PRs have been merged.

**Comment by romainbrenguier** [comment]
@tautschnig 
> It's probably a good idea, but also doesn't seem particularly urgent to me. Several existing PRs conflict with the changes proposed here, and rebasing with code moving between files is really painful. I'll thus refrain from approving until those other PRs have been merged.

Can we make a list of these PRs, so that we wait for them, and try to get the new coming ones rebased on this?

I only had this one https://github.com/diffblue/cbmc/pull/3986, but I prefer to delay it and wait for this change.

**Comment by tautschnig** [comment]
> Can we make a list of these PRs, so that we wait for them, and try to get the new coming ones rebased on this?

It's probably incomplete, but https://github.com/diffblue/cbmc/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen++label%3A%22Symbolic+Execution%22+ is a starting point.

**Comment by romainbrenguier** [comment]
> It's probably incomplete, but https://github.com/diffblue/cbmc/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen++label%3A%22Symbolic+Execution%22+ is a starting point.

A lot of pull request there do not touch goto_symex_state.h so are not relevant. 
A search for "goto_symex_statet" only gave 4 pull requests https://github.com/diffblue/cbmc/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+%22goto_symex_statet%22+ but I couldn't find how to make github search for file names.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 016ca577a14861af147b3b3ebfcd8d8fd9d0022e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102655038

**Comment by tautschnig** [comment]
> A lot of pull request there do not touch goto_symex_state.h so are not relevant.

Yes, but your list is definitively incomplete, so we've got an over-approximation and an under-approximation.

All I'm asking for is awareness and some care. Awareness for the impact of changes being proposed.

**Review by tautschnig — APPROVED** [review]
@romainbrenguier This can probably go in as one of the next commits, but it does need a rebase. (Any reference to `safe_pointers` needs to be removed from the new `goto_state.h`.)

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 3bce5c287fde48ce3d359731f8879698505d1c90).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103008022
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Pull request merged**
