### PR TITLE
Add dispatch loop detection analysis

### PR DESCRIPTION
**Pull request by karkhaz**
This commit adds an analysis to goto-instrument, used for detecting
so-called "event dispatch loops" in the target program. The location of
the dispatch loop can be printed out using the --dispatch-loop-show flag
to goto-instrument. Additionally, the --dispatch-loop-graph flag prints
a simplified control-flow graph of the program, showing functions and
lexically-nested blocks, as well as information pertaining to the
analysis.

This diagram is the output from running this analysis over the [dmenu application launcher](https://tools.suckless.org/dmenu): 

dmenu CFG

the diagram shows all code that exists at most two function calls away from `main()`. It is a simplified control flow diagram; it does not show instructions, but only functions and lexically-nested blocks. The **key** on the left-hand side of the diagram shows what the different node types are. The dispatch loop in this program is indicated by the dark nodes on the graph.

The following description is taken from the documentation for
dispatch_loop_detectort:

Roughly speaking, a dispatch loop is a loop that contains a conditional
statement. The loop repeatedly calls some function and uses the
conditional statement to decide what to do with the function's return
value. Examples of such a construct in real programs are:

- Servers, where requests are pulled from a queue, and dispatched based
  on the type of the request;

- Graphical user interfaces, where user input events trigger some
  computation based on what the input event is;

- Parsers and lexers, where lexemes are pulled from a queue and
  converted into tokens;

etc. Of course, there might be many conditionals-within-a-loop in a
given program, and most of them will not be such dispatch loops; so we
impose some additional constraints:

- The dispatch loop should be close to `main()`, in particular, no more than
  search_depth function calls away;

- The code transitively touched by each of the branches of the
  conditional statement must be *reasonably* disjoint. "Transitively
  touched" means all the code that could possibly be executed when
  running over a branch, including all function calls, transitively. The
  rationale is that in a dispatch loop, the conditional will be doing
  'something different' depending on the type of the event it is
  dispatching.

- The code covered by the sum of all branches of the conditional must be a
  sizeable fraction of the entire codebase.

- The conditional must be directly nested inside the loop (this may change
  in the future).

### CODE REVIEW

**Comment by karkhaz** [comment]
Ping @tautschnig. Not sure who the right person to review this would be. Further information for reviewers:

- The code currently shells out to `clang`, specifically the Clang frontend, in order to get an AST for the program. It is paramount that we have the correct lexical structure of the program for this analysis, so this patch parses the textual output of `clang -Xclang -ast-dump` to get that. I had tried using `goto-instrument/goto_program2code` before doing that, but it wasn't revealing the exact structure of the original program reliably enough.

**Review by tautschnig — COMMENTED** [review]
I think it's good to have this out for discussion, but it would be really nice to make use of the output that `cbmc --parse-tree` can produce (though arguably not necessarily invoking an external tool, but instead just use the internal API).

**Comment by karkhaz** [comment]
`cbmc --parse-tree` doesn't seem to work if the source file includes headers that CBMC cannot find, e.g. because they were pulled in from somewhere special by the build system. Would using the internal API (as opposed to just passing `--parse-tree` to CBMC) get rid of this issue? Otherwise, I don't think it's usable; we really need to be able to get the parse tree for a source file in isolation.

**Comment by karkhaz** [comment]
[This PR is not at all yet ready for review]

As a follow up to my reply to @tautschnig: I just realised that in theory, the output from `cbmc --parse-tree` could work perfectly well if the entire program to analyse was compiled from a single preprocessed C file that doesn't pull in any headers. While this is obviously unusual, it's exactly the scenario for SV-COMP, I think all files in that competition are already preprocessed. So it would be nice to have an option to use `--parse-tree` for SV-COMP, since it will probably be more accurate than parsing clang's text output...I'm very sad that I only thought of this now, I wish I had given it more thought when you suggested it.

In theory my code is modular enough that I can add both a clang parser and a `cbmc --parse-tree` walker and the code can use whichever one is more appropriate (`--parse-tree` for SV-COMP and clang in general), but since I'm not going to have this ready for SV-COMP, it's a very low priority at the moment. Maybe I can do it for SV-COMP 2020, that would be nice.

**Comment by TGWDB** [comment]
Closing due to age (no further comment on PR content), please reopen with rebase on develop if you intent to continue this work.

**Pull request closed without merging**
