### PR TITLE
 Model CProver.createArrayWithType function

### PR DESCRIPTION
**Pull request by smowton**
This introduces an all-purpose replace-intrinsics pass and uses it to replace the
CProver.createArrayWithType function, which requires us to directly access an object's
classid.

Depends on #5066, only review the last commit.

Needs tests.

### CODE REVIEW

**Comment by thk123** [comment]
Holding off on review until tests are added.

**Comment by smowton** [comment]
@thk123 now has tests, though I'm thinking this ought to go in the frontend rather than a standalone pass so that NullPointerExceptions work the same way they do for normal Java. Nontheless the concept is reviewable as is the bulk of the code, which will just move into `java_bytecode_languaget` somewhere.

**Comment by smowton** [comment]
Needs #5070 to avoid CI failures

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 67c06fd010afce1b08ca210abe4fe628cd88b4e0).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125315951

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 8f9eb63c3c577fdd2429afbb216fd48a490b13ca).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125475177

**Review by peterschrammel — APPROVED** [review]
Lgtm

**Pull request merged**
