### PR TITLE
Remove unused entries from the string table

### PR DESCRIPTION
**Pull request by tautschnig**
21% of the entries do not occur in the code base (reduction from 844 to 663 entries).

I do expect that this will break dependent projects that _do_ use (some of) those entries. We should come up with a solution that enables each project to easily add entries local to its codebase.

### CODE REVIEW

**Comment by tautschnig** [comment]
Requires #2105 to be merged first.

**Comment by kroening** [comment]
Ideas on how we can extend the set of IDs without too much pain? Ideally in a modular fashion?

**Comment by kroening** [comment]
Side-remark: I don't think that symbolt::to_irep() is still in use?

**Comment by tautschnig** [comment]
> Side-remark: I don't think that symbolt::to_irep() is still in use?

Good call! I have now added a commit to remove it.

**Comment by tautschnig** [comment]
> Ideas on how we can extend the set of IDs without too much pain? Ideally in a modular fashion?

Is there a public repository that I could look into to experiment with this? My thinking is that the respective `main` function of that project should invoke some `extend_string_container` function and obviously there needs to be an additional project-specific header much like `irep_ids.def`.

**Comment by peterschrammel** [comment]
An even simpler solution (potentially less elegant and robust, though) would be to make the build system of the dependent repository append its local defs to the irep_ids.def in its cbmc submodule. That way we could get compile-time errors when IDs get redefined in the dependent repo.

**Comment by tautschnig** [comment]
How about something close to the "append" proposal:
1. Add to `src/util/irep_ids.def`:
```
#ifdef MORE_IDS
#include MORE_IDS
#endif
```
2. Project X adds to the compiler command-line `-D'MORE_IDS=<my-project/some_file.h>'`

**Comment by tautschnig** [comment]
I have added 4bdf71a to implement the proposed extension mechanism.

**Review by peterschrammel — APPROVED** [review]
Some linter issues, otherwise looks good.

**Comment by tautschnig** [comment]
@peterschrammel @smowton @thk123 As I could merge this once CI passes here, could you please assure me that all projects you currently care about continue to build once this PR is merged?

**Comment by thk123** [comment]
Creating bump now.

**Comment by thk123** [comment]
diffblue/test-gen#1755

**Comment by kroening** [comment]
The real test of this will be when jbmc moves out. Lots of IDs are Java-specific.

**Comment by smowton** [comment]
@tautschnig can confirm this merges with the security product without doing any damage. We already declare our private identifiers using a construct like
```
irep_idt get_xyz_id() {
  static irep_idt xyz = "xyz";
  return xyz;
}
```
That achieves one hash per run (cf. zero hashes using irep_ids.def), but we figure the real point is to avoid a hash per usage like if you converted from a cstr every time.

**Comment by thk123** [comment]
TG pointer bump passes :+1:

**Comment by tautschnig** [comment]
@smowton said:
> We already declare our private identifiers using a construct like [...]

I'm merging this now and would invite you to try out the proposed define-your-local-ids approach.

**Pull request merged**
