### PR TITLE
Hide calls/returns from/to hidden functions

### PR DESCRIPTION
**Pull request by kroening**
This removes clutter in any counterexample traces; these functions have no
meaning for the user.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 66792341423b16d8dc3972b55316e145eea2137b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92413791

**Review by tautschnig — CHANGES_REQUESTED** [review]
I see two issues here (but I could be wrong about each of them):
1) This will also hide all initialisation of objects with static lifetime (as this is done in `__CPROVER_initialize).
2) We have existing code to identify internal functions and symbols, in `system_library_symbolst`.

**Comment by kroening** [comment]
1. No, this only affects function calls, not assignments.

2. is_symbol_internal_symbol goes very far, and includes e.g. all functions with prototypes in /usr/include.

**Comment by tautschnig** [comment]
> No, this only affects function calls, not assignments.

Indeed, sorry about that.

> is_symbol_internal_symbol goes very far, and includes e.g. all functions with prototypes in /usr/include.

That is true, but still I'm not convinced that yet-another-local-test is the right approach. We already have `__CPROVER_HIDE` that we interpret elsewhere, can't we at least make use of that?

**Comment by kroening** [comment]
Ok, now using existing hidden flags.

**Review by tautschnig — APPROVED** [review]
Thanks a lot for the update. CI is failing, though.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 6fd0cf35e8e0ab1f213e94590b99f458497ce479).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92928001

**Pull request merged**
