### PR TITLE
bitwise_or, _and, _xor can now do arbitrary widths

### PR DESCRIPTION
**Pull request by kroening**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [X] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
1) Why is this needed/useful?
2) Comments are incomplete.
3) Should be unit-tested.
4) CI is failing.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 6931fb7ae37aa589a85b8de804af3e0312618217).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87100767
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 7f506ef2756259f7b79f8712276a411dcd0138d5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87103227

**Review by tautschnig — APPROVED** [review]
I would still want this to be tested, but apart from that the PR looks ok to me now.

**Pull request merged**
