### PR TITLE
Make goto_symext a subtype of messaget

### PR DESCRIPTION
**Pull request by karkhaz**
to enable debug(), status() etc. output from goto_symext.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
Would appreciate input from @kroening as there may have been some design reason that kept `goto_symext` from becoming a `messaget` for such a long time.

**Comment by smowton** [comment]
One note: on new code, I recommend making `messaget` a `mutable` member rather than a superclass. That way you can log from within `const` methods, at the cost of slightly more verbose logging code.

**Comment by karkhaz** [comment]
@smowton cheers, added `mutable messaget log` as a member of `symext`

**Comment by tautschnig** [comment]
Pinging @chrisr-diffblue @martin-cs @peterschrammel for owner reviews.

**Review by smowton — APPROVED** [review]
Great! It's a shame this causes a bit of churn, but such a fundamentally important class shouldn't have been a logging vacuum to begin with.

**Review by chrisr-diffblue — APPROVED** [review]
Thanks for this cleanup, looks really good to me.

**Comment by kroening** [comment]
@smowton BTW, the idiom change (mutable log member) is potentially problematic -- if the goal is to be able to log in a const class, it would perhaps be better to do that in messaget?

**Comment by tautschnig** [comment]
It's #1142 that would make those changes in `messaget`. It may be necessary to route that PR to develop.

**Pull request merged**
