### PR TITLE
C++ front-end: Declarator to symbol conversion follows C implementation [depends-on: #4559]

### PR DESCRIPTION
**Pull request by tautschnig**
Only the last commit is new, the others are in #4559.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: c360dbe4c7ac6e6e32d9594b05e754a3aec0aa45).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/109122825
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 162c4efe43ab978fc8e50647a6ce102fe5bdeb23).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/109123781
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: fdf6d3073fd056bf23949403b1b7c7b9b41bd4e4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/109127931
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: d739d59f1f0ad4621eba23da87eaa5bcaeda950e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/109160757
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: e3ed19e4905feaa6e390902016ac766c62f1b2b4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/111921243

**Pull request merged**
