### PR TITLE
address_mapt keys are std::size_t

### PR DESCRIPTION
**Pull request by tautschnig**
... as that's the type of keys being used during lookup.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — COMMENTED** [review]
These are offsets within a Java method, which has a hard 64KB maximum. Therefore suggest the actual correct type is `uint16_t`, or perhaps `uint32_t` if you want to be safe re: casually adding two of them together without overflow, or make sure you can express UINT16_T_MAX + 1 to talk about a limit. It probably shouldn't vary in size from platform to platform like `size_t` though

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 59612347c46f95ea22d3b081e41dd4cfe7762dbe).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85743380

**Comment by tautschnig** [comment]
> These are offsets within a Java method, which has a hard 64KB maximum.

Thanks a lot for the info. I have rewritten this patch to uniformly use a typedef-name (`method_offsett`) wherever an address/method offset is used.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 46471225b57887f63cb50f0b8aa5215c95c6d2c9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85755311
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 57cd9c1bdfb2adf1a1ed26cc2ce8f1e35cb3756e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85755782

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
