### PR TITLE
Separate file for Makefile based building of smt2_incremental directory

### PR DESCRIPTION
**Pull request by thomasspriggs**
So that the `.cpp` files for incremental SMT2 solving can be
added/removed/renamed without triggering codeowner review of the
`src/solvers` directory.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by TGWDB — APPROVED** [review]

**Comment by tautschnig** [comment]
If `CODEOWNERS` is what we're worried about, can't we just amend `CODEOWNERS` instead and list `src/solvers/Makefile` in there?

**Comment by thomasspriggs** [comment]
> If `CODEOWNERS` is what we're worried about, can't we just amend `CODEOWNERS` instead and list `src/solvers/Makefile` in there?

That would also work. However it would grant code ownership to those listed against it for making build system changes for the other solvers. It would also mean keeping an additional list of people up to date in the `CODEOWNERS` file, rather than tying the list of people who can change what files are built for the `smt2_incremental` directory precisely to those who have code ownership of that directory.

**Comment by tautschnig** [comment]
> That would also work. However it would grant code ownership to those listed against it for making build system changes for the other solvers. It would also mean keeping an additional list of people up to date in the CODEOWNERS file, rather than tying the list of people who can change what files are built for the smt2_incremental directory precisely to those who have code ownership of that directory.

I accept that there's some bureaucratic overhead in this, but then at least we're doing bureaucracy where bureaucracy belongs. Working around bureaucracy via a one-off Makefile hack is, well, a workaround. (And I'm not worried about granting code ownership to too many people on this occasion.)

An alternative fix is to introduce Makefiles for each subdirectory in `solvers` instead of this single big one. But then we should do this properly for all subdirectories.

**Comment by thomasspriggs** [comment]
This has been superseded by the codeowners change PR which has been merged.

**Pull request closed without merging**
