### PR TITLE
Silence #if/#elif warnings originating from Windows header files

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 6cb461ca75259ce5cc7a486ae0b6084d108c8304).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77212176
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by smowton — APPROVED** [review]
I'm obviously surprised if windows.h triggers warnings on a Microsoft compiler, but if it's really the case then this seems like an acceptable way to deal with that. Could you provide a specific example of the kind of construct that it's complaining about in your commit message?

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 9947bfb572082f35ad7056815ae16a3bfeae0340).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78383405

**Comment by tautschnig** [comment]
I have amended the commit message as suggested.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: e3c035ddf9c2667328632252851717734e25fe4f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78385938

**Comment by smowton** [comment]
Thanks! Also whenever we eventually bump required MSVC to 2017, we can use this: https://blogs.msdn.microsoft.com/vcblog/2017/12/13/broken-warnings-theory/

**Review by kroening — APPROVED** [review]

**Comment by kroening** [comment]
Sad, but I don't have a better idea.

**Pull request merged**
