### PR TITLE
Build using C++17

### PR DESCRIPTION
**Pull request by tautschnig**
This raises the minimum GCC version supported to 7 (see https://gcc.gnu.org/projects/cxx-status.html#cxx17).

Add -Wno-register to silence warnings about the use of the `register` storage class by older flex versions (as present on macOS).

CMake doesn't know about C++ 17 until version 3.8, so we need to hard-code the necessary command-line options.

This is now the single commit from #6749 that actually switches over to C++17. All other commits in #6749 are improvements enabled by this commit, but some of them require large changes that may take a lot of time to get reviewed. The aim of this PR is to unblock use of C++17, without necessarily reaping all benefit right away.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by martin-cs — APPROVED** [review]
General "dependencies are barriers to users, especially new ones" feelings but https://github.com/diffblue/cbmc/pull/6749#issuecomment-1076971425 seems sufficiently reassuring and motivating for why this is useful.

**Comment by thomasspriggs** [comment]
Could we bump the cmake version to avoid "hard coding" the compiler flags? https://github.com/diffblue/cbmc/pull/7184

**Comment by kroening** [comment]
I would probably wait for 6.0 with this.

**Comment by thomasspriggs** [comment]
> I would probably wait for 6.0 with this.

For bumping the cmake version or for moving to C++17 or both?

**Comment by kroening** [comment]
Apologies for being unclear; I meant "moving to C++17". I'd say that bumping cmake is ok, since users who have difficulties getting a new cmake can fall back onto the Makefile build system.

So I'd merge #7184, but wait with #7172.

**Comment by thomasspriggs** [comment]
@tautschnig I have now merged the cmake version bump PR. Therefore it should no longer be necessary to "hard-code the necessary command-line options."

**Comment by tautschnig** [comment]
> @tautschnig I have now merged the cmake version bump PR. Therefore it should no longer be necessary to "hard-code the necessary command-line options."

Done.

**Comment by esteffin** [comment]
Another PR has been created for this #7989.
We agreed that that PR will be part of version 6.

Closing as duplicate

**Pull request closed without merging**
