### PR TITLE
Reduce redundancy between jbmc-string and strings-smoke-tests

### PR DESCRIPTION
**Pull request by tautschnig**
Several tests are the same or test the same functionality.

The following remain to be cleaned up. @allredj @romainbrenguier could you please contribute such cleanup?
- [ ] java_append_char
- [ ] java_append_string
- [ ] java_case
- [ ] java_char_array
- [ ] java_char_array_init
- [ ] java_char_at
- [ ] java_code_point
- [ ] java_compare
- [ ] java_concat
- [ ] java_contains
- [ ] java_delete
- [ ] java_delete_char_at
- [ ] java_empty
- [ ] java_endswith
- [ ] java_equal
- [ ] java_float
- [ ] java_hash_code
- [ ] java_index_of
- [ ] java_index_of_char
- [ ] java_insert_char
- [ ] java_insert_char_array
- [ ] java_insert_int
- [ ] java_insert_multiple
- [ ] java_insert_string

### CODE REVIEW

**Comment by peterschrammel** [comment]
@tautschnig, this conflicts with #2118. Shall we postpone this cleanup after #2118 has been merged? I'd suggest to close this PR in that case.

**Comment by tautschnig** [comment]
This PR probably just doesn't make sense in this repository anymore? My suggestion is that whoever takes ownership of the Java repository should migrate this issue and then just close it here.

**Comment by peterschrammel** [comment]
I've cherry-picked the relevant changes into #1768.

**Comment by tautschnig** [comment]
Thank you @peterschrammel!

**Pull request closed without merging**
