### PR TITLE
Corrections to the string solver - 2

### PR DESCRIPTION
**Pull request by allredj**
The code adding lemmas to the solver for each equation has been completely remastered. It has been simplified and should now cover all foreseeable cases.
We add constraints on sums for avoiding overflows in the string solver.
Many fixes have been done in the preprocessing of strings. String refinement is now more language-independent.

This replaces pull request #574.

This depends on #378 and #559.

### CODE REVIEW

**Comment by kroening** [comment]
Needs a rebase, but is otherwise ready to go.

**Comment by tautschnig** [comment]
I note that #378, which this one allegedly depends on, is still open.

**Comment by allredj** [comment]
Indeed, the present PR corrects some issues with PR #378. However the latter still hasn't been merged because we put a halt on integrating string support into the master branch of cbmc. As such, I believe it makes little sense to get these PRs ready to be merged in master, as we already know that this implementation has some problems. These problems have however been addressed in the test-gen-support branch, via a compete overhaul of the preprocessing, as well as many other corrections/improvements.
I would recommend completely dropping the outstanding string-related PRs on the master branch.
Introducing a viable string support in cbmc master could be done by merging it from the test-gen-support branch. It would not be completely straightforward, but would certainly be a more satisfactory solution, I believe.

**Comment by tautschnig** [comment]
> I would recommend completely dropping the outstanding string-related PRs on the master branch.

Marking this as do-not-merge; I'll leave it to you/others to close this PR (and related ones) entirely.

**Comment by peterschrammel** [comment]
Closing this PR for above mentioned reasons.

**Pull request closed without merging**
