### PR TITLE
set the name of bison-generated header file

### PR DESCRIPTION
**Pull request by kroening**
This avoids the need to rename the header file in the Makefile.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- n/a Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — COMMENTED** [review]
CMake too?

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 90a835513e0a5c3d9d6c017d10378ddd8ab5e3ab).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/118289031

**Comment by kroening** [comment]
It's not obvious that it's desirable to do the same with cmake -- cmake appears to determine the version number of bison, and on that basis, determines the default name of the header file that is generated.

**Review by smowton — APPROVED** [review]
Fair enough

**Review by peterschrammel — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
