### PR TITLE
C++ front-end: support =delete method declarations

### PR DESCRIPTION
**Pull request by tautschnig**
This enables us to use use cassert instead of assert.h in C++ regression tests,
as Visual Studio's header files make use of this.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Comment by kroening** [comment]
Sure this works? E.g., = delete makes any inherited method with same name/signature inaccessible.

**Comment by kroening** [comment]
I appreciate this may be a quick fix.

**Comment by tautschnig** [comment]
I am yet to figure out how access checks are implemented, I'll add a regression test using `=delete` to disable methods that will be marked as KNOWNBUG.

**Comment by kroening** [comment]
Ok

**Review by kroening — APPROVED** [review]

**Comment by tautschnig** [comment]
I have gone for a proper, access-control based implementation instead. Regression test included (as `CORE`).

**Comment by kroening** [comment]
oh, wow!

**Pull request merged**
