### PR TITLE
Replace system() by run()

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 51d130a6f292234f42eac8afc24c740449a14591).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84197393

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: b727ef4dd3623d0bad1ee473ebbad7326f7c0db0).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84205576

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 487b12222bcb1c5d976d28a6bcbe55a4ad639385).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84219947

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 27c26959fce3807a76dafa76223e61148fcb1536).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84282209

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: c57902b28a3e0c48331eb825b3466cecc1c3118c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84389057
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 3347f418e9f67b0a6557bc8992d37a42037d5923).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84391911
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 448c78055f46d8b1440593776eb12525f9ce6087).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84394747
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by peterschrammel — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
