### PR TITLE
replace_symbolt can now replace tag type symbols

### PR DESCRIPTION
**Pull request by kroening**
Obvious interaction with #2723.

### CODE REVIEW

**Comment by tautschnig** [comment]
My understanding (as implemented in #2723) was that we don't need replacement for type symbols (or, for that matter, tags) at all?

**Comment by kroening** [comment]
Yes, my suspicion is that we simply won't need this eventually.

**Comment by tautschnig** [comment]
@kroening Can this be closed?

**Comment by TGWDB** [comment]
Closing as this as long neglected and also since the mentioned PR that may also solve the same issue (#2723) has been merged. Please reopen if you believe this is erroneous or something is missing.

**Pull request closed without merging**
