### PR TITLE
Implement popcount

### PR DESCRIPTION
**Pull request by tautschnig**
~Once #1882 is merged, adjustments to this code are needed. If this one ends up being merged first, #1882 needs to be extended.~

### CODE REVIEW

**Review by smowton — COMMENTED** [review]
For ignorant people like me, perhaps define "popcount" somewhere -- at first I assumed this popped a count from some stack or another.

**Comment by tautschnig** [comment]
@smowton I've added a brief explanation to the documentation of `popcount_exprt`.

**Review by smowton — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Comment by martin-cs** [comment]
@tautschnig Is this performance critical?  I think a better, bit-level implementation is possible (it is similar to multiplication in some ways).  If you have some examples that are performance critical I could have a go at them.

**Comment by tautschnig** [comment]
I haven't yet seen this being a performance problem, but indeed there may be room for optimisation. I believe the log(bitwidth) adders would be the most costly part as the shifts and bitwise ands will all be evaluated before being passed to the SAT solver. The second regression test (gcc_popcount2) did not finish within 3 hours on my (arguably slow) machine, spending all the time in the SAT solver. Yet I did not debug whether that's caused by the simplistic `pop4a` at the C level or by the (supposedly more efficient) encoding of `pop0` in `popcount.cpp`.

**Comment by martin-cs** [comment]
On Thu, 2018-03-01 at 13:18 +0000, Michael Tautschnig wrote:
> I haven't yet seen this being a performance problem, but indeed there may be room for optimisation. I believe the log(bitwidth) adders would be the most costly part as the shifts and bitwise ands will all be evaluated before being passed to the SAT solver.
I believe this too.

My first approach would be to use full-adders as 3-bit pop-counts.
Giving ceil(wordlength/3) 2-bit numbers.  Then either tree accumulate
these or pop-count the low and high bits and so on recursively.  7 bits
requires 4 full adders, 15 bits needs 4*2 + 3 = 11, 31 bits needs 11*2 +
4 = 26, 63 bits needs 26*2 + 5 = 57.  Which should all be less than a
single adder.

>  The second regression test (gcc_popcount2) did not finish within 3 hours on my (arguably slow) machine, spending all the time in the SAT solver. Yet I did not debug whether that's caused by the simplistic `pop4a` at the C level or by the (supposedly more efficient) encoding of `pop0` in `popcount.cpp`.
My guess is that the problem is the combination of the nasty loop based
encoding ( try:

for (i = 0; i < sizeof(thing) * CHAR_BITS; ++i) {n+=(x & 0x1); x>>=1;}

) and equivalence proving.

Thanks for finding a difficult example based on optimal primitives!

**Pull request merged**
