### PR TITLE
trigger library build in top-level Makefile

### PR DESCRIPTION
**Pull request by kroening**
This matches what the cmake build does, and prevents an unnecessary ~2s
delay when 'make' is called in java_bytecode.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 7e81682cbf39708a0be7ddbef018103de23496cb).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86364872

**Review by tautschnig — CHANGES_REQUESTED** [review]
I might be wrong, but I believe those changes would cause the code in `jbmc/src/java_bytecode/library/` never to be built, even if `jbmc/lib/java-models-library` is not present.

**Comment by kroening** [comment]
@tautschnig Indeed, but I believe that code has been out of use for a while. I'll let @peterschrammel comment whether it's ok to remove.

**Comment by peterschrammel** [comment]
The `java_bytecode/library` directory is currently not used (except that the core-models.jar is copied there and referred to from regression tests, which should be changed to a reference to lib/java-models-library/target instead). The initial idea was to embed the core-models.jar into the executable, which is in a branch somewhere, but hasn't been merged. We can actually remove the entire `java_bytecode/library` directory for now and if that branch gets merged in future we can revert the commit.

**Comment by TGWDB** [comment]
Closing as discussion here concludes this PR is incorrect. If you believe this should be revisited/reopened, please provide up to date details on how the comments are addressed (or raise a new PR for removing the entire `java_bytecode/library` as per discussion above).

**Pull request closed without merging**
