### PR TITLE
smt2: let fix

### PR DESCRIPTION
**Pull request by kroening**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: b5ee26b62da167fc74801b593db527a3a61f820f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96005560

**Review by tautschnig — COMMENTED** [review]
Missing commit messages and tests?

**Comment by kroening** [comment]
@tautschnig Apologies, now both there!

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: aae639ab6bdd5341bac78711d074104e2c5f680e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96066022

**Review by allredj — APPROVED** [review]

**Pull request merged**
