### PR TITLE
Improve array bounds checks

### PR DESCRIPTION
**Pull request by smowton**
This is a recreation of an old orphaned, stalled pull request. Fixes https://github.com/diffblue/cbmc/issues/239 -- see that issue for more details.

### CODE REVIEW

**Comment by smowton** [comment]
Amended per recommendations above

**Comment by tautschnig** [comment]
@smowton Would you mind rebasing this branch and squashing those commits that I have marked as fixup?

**Comment by smowton** [comment]
Done

**Comment by smowton** [comment]
Rebased again and pushed to rerun tests (due to `KNWONBUG` typo that it looks like you fixed recently :))

**Comment by smowton** [comment]
Only remaining Travis failure stems from unrelated namespace resolution issues (`to_string` vs. `std::to_string`) in code untouched by this PR, so believe this is ready to merge.

**Comment by tautschnig** [comment]
As those `to_string` issues have been fixed I've re-started the travis build.

**Comment by smowton** [comment]
CPPLint has lots of complaints about code that is unchanged here; otherwise looks good?

**Comment by tautschnig** [comment]
Yes, goto_check.cpp obviously needs cleanup, but this is unrelated to this pull request and should be fixed independently.

**Comment by smowton** [comment]
Rebased again, should be ready to merge.

**Pull request merged**
