### PR TITLE
Check all struct members for possible need for renaming

### PR DESCRIPTION
**Pull request by tautschnig**
Follow-up to #3633. I'm not labelling this "bugfix" as I wasn't actually able to trigger a bug, even though there are changes that make it seem more correct.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — APPROVED** [review]
I think that sort of VL-struct might be a GNU extension, so wouldn't be surprised if MSVC starts cursing like a sailor

**Comment by tautschnig** [comment]
Clang does refuse to compile this, GCC is ok - I haven't actually tried MSVC.

**Comment by kroening** [comment]
You might try:
* Make first member of a pointer.
* Make second member of struct a flexible _Bool array, to avoid multiplication problem.

To make the lack of renaming actually a problem, this needs to happen in a loop, and the size needs to differ between iterations.

**Review by kroening — APPROVED** [review]

**Comment by kroening** [comment]
BTW, my plan is to add a goto-program transformation pass that compiles these away. They add a lot of grief for a feature that has very few users.

**Comment by tautschnig** [comment]
> To make the lack of renaming actually a problem, this needs to happen in a loop, and the size needs to differ between iterations.

Thanks, I have built a test that seems to fail, but actually it fails even without the recent optimisation. I'll work on it.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 51c44e6d49c634dba04964498a77a2502969effa).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98498677
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
I have added failing tests, but might actually deal with them in separate PRs.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: e98554b692e7e24fa10b9114ad7069295d029ec1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98516182
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Pull request merged**
