### PR TITLE
Update jbmc/lib/java-models-library for PR16 (getChars) and activate Tests

### PR DESCRIPTION
**Pull request by romainbrenguier**
https://github.com/diffblue/java-models-library/pull/16

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: a2f8fb3c8f6b94b96556943fc05704938a38b82b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92481187

**Review by peterschrammel — APPROVED** [review]

**Comment by peterschrammel** [comment]
Tagging `Do not merge` because the java-models-library pointer needs to be updated before merging.

**Comment by romainbrenguier** [comment]
Now pointing to master

**Comment by tautschnig** [comment]
@romainbrenguier This is now failing CI.

**Comment by romainbrenguier** [comment]
This is caused by the first commit https://github.com/diffblue/java-models-library/pull/13 (also brought with this submodule update).
I suspect the `CASE_INSENSITIVE_ORDER` field.

**Comment by romainbrenguier** [comment]
Superseded by https://github.com/diffblue/cbmc/pull/4476

**Comment by tautschnig** [comment]
Closing as #4476 has been merged.

**Pull request closed without merging**
