### PR TITLE
languaget is not a messaget [blocks: #3800]

### PR DESCRIPTION
**Pull request by tautschnig**
Pass a message handler as an argument to several of its functions, but do not
construct a messaget object without a configured message handler as that is
deprecated.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 1bd05badbea30a743d017bc478a0256937212f73).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99551095
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: ec95eba68f137972f1efca84ff9d7f34889a26a8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99552352
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 49d7c2d88f394787e4a6f81734ffc864c0b13754).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99567417
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 75c918f3da5b5fad161b68d88aed6ff5b135f67f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99782807
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by peterschrammel — APPROVED** [review]
Will break TG, but should be easy to fix.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 2451f62c76223fbbcc25c1589060ba2ff0bfa1c4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103496171
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 90626df844ccb3f80b7cd8f911620b3d69f60d20).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/104501836
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by romainbrenguier — APPROVED** [review]

**Review by martin-cs — APPROVED** [review]
Only a very small amount of this one touches my area of responsibility; the bits that do are fine though.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: f710eddd103ffd41de3e3d8a42844d4b22360930).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/108804806
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Comment by tautschnig** [comment]
@kroening If you want to experiment with constructing a `languaget` using a message handler please take a look at https://github.com/diffblue/cbmc/pull/3800/commits/c1560e8d8f643b5c54b733d3bf57c95e7cf916f3 (which I had failed to find yesterday, it's commit message isn't very intuitive :-) )

**Comment by TGWDB** [comment]
This looks like a small rebase and rerun of CI could allow merging?

**Review by feliperodri — APPROVED** [review]

**Review by TGWDB — APPROVED** [review]

**Review by kroening — APPROVED** [review]

**Review by thomasspriggs — APPROVED** [review]

**Pull request merged**
