### PR TITLE
enabled slice07 regression test

### PR DESCRIPTION
**Pull request by lucasccordeiro**
Enabled slice07 regression test since the code transformation done
around start_thread is now properly working.

### CODE REVIEW

**Comment by tautschnig** [comment]
It seems the test needs to be made compatible with Windows.

**Comment by tautschnig** [comment]
Which commit is the one that has made this work ok?

**Comment by lucasccordeiro** [comment]
I have gone back over the commits history. It seems that this regression test was already working  since its initial commit 3613ef929334f72ce322dbe541997d0a4e3cb718.

**Comment by lucasccordeiro** [comment]
Closing this PR for now since we should keep this test case as KNOWNBUG. We have a PR that prevents the user to run the slicer over multi-threaded programs (https://github.com/diffblue/cbmc/pull/692), as originally observed. Alternatively, we could check the effort to extend the dependence-graph and slicer to be thread-aware in a separate issue.

**Pull request closed without merging**
