### PR TITLE
Run CI for install z3 in CI + z3 SMT struct fix [DO NOT REVIEW]

### PR DESCRIPTION
**Pull request by thomasspriggs**
Run CI for install z3 in CI + z3 SMT struct fix [DO NOT REVIEW]

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by SaswatPadhi** [comment]
@thomasspriggs Looks like the z3 version on Windows (from chocolatey) and Ubuntu 18.04 are too old and do not handle datatypes.

I think instead of using package manager version, we should be grabbing binaries from https://github.com/Z3Prover/z3/releases/tag/z3-4.8.10.

**Comment by thomasspriggs** [comment]
The Ubuntu 18 job is just missing z3. I still need to investigate the Windows jobs.

**Comment by SaswatPadhi** [comment]
It could be that they _support_ datatype to some extent, but the version in the Ubuntu 18.04 repo for Z3 is 4.4.1 (tagged 5 years ago) and the version in Chocolatey repo is 4.3.2 (tagged 6 years ago). The latest z3 version is 4.8.10.

I think having different solver versions on different platforms is problematic.

**Comment by thomasspriggs** [comment]
The work we wanted from this PR is merged. So the PR itself is no longer needed.

**Pull request closed without merging**
