### PR TITLE
remove unused member_exprt::symbol()

### PR DESCRIPTION
**Pull request by kroening**
Reverts d47d503b66; the method isn't used.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
I'd suggest that the information included in the PR also makes it into the commit message.

**Review by peterschrammel — COMMENTED** [review]
@thk123, this requires a TG bump.

**Comment by thk123** [comment]
Done: diffblue/test-gen#2217 - awaiting CI

**Review by thk123 — DISMISSED** [review]
Yeah turns out TG is using this - will fix up.

**Comment by thk123** [comment]
What's the motivation here? Not only is it not unused (this PR removes two uses) but it is non-trivial - it loops back up the expression tree to find the root symbol. It seems your replacements won't work for: `a.b.c`, previously would get `a`, now will crash.

Edit: In these cases it doesn't do seem to do anything useful - will see if the same is true in TG. If not, will make a static function in where it is used.

**Comment by tautschnig** [comment]
> What's the motivation here?

It's just wrong. The root operand of a `member_exprt` need not be a `symbol_exprt`. (It could be a `struct_exprt`, a `dereference_exprt`, and possibly something else.)

Any current user of this method should use `object_descriptor_exprt`, use its `.build(...)`, and then `.root_object()`. When I got to review this PR there hadn't been any edits to users, so I trusted the "it's unused." Otherwise I would have added the above guidance.

**Comment by thk123** [comment]
Thanks @tautschnig for the explanation. TG updated to use `object_descriptor_exprt` - and passed tests locally - will post when CI passes.

**Comment by kroening** [comment]
Does anyone know why cmake builds are unhappy?

**Comment by tautschnig** [comment]
> Does anyone know why cmake builds are unhappy?

There are invariant failures in the unit tests. I suppose they should be rewritten in the way I described (using `object_descriptor_exprt`) rather than as currently done. I'm actually more concerned that it's only in cmake that unit tests fail...

**Comment by tautschnig** [comment]
See #2877 for the JBMC unit tests.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 0099f745281cb57b206fff408793219e5976ad43).
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Comment by thk123** [comment]
This was updated _after_ the bump passed and now causes TG to fail. Please hold off merging if you make substantial (e.g. interface) changes until the TG bump has been updated.

**Comment by tautschnig** [comment]
Hmm, sorry, I had understood https://github.com/diffblue/cbmc/pull/2860#issuecomment-417626076 as TG having been cleaned up.

**Comment by thk123** [comment]
@tautschnig Fair - it was, but CI was still failing on this PR. Then the changes to the unit test were applied (adding a `symbol_tablet` parameter to some test utilities) and this broke TG. 

Annoyingly in GH there is no way to really see the diff between incremental revisions of a rebased PR (which would have shown the diff to be substantial enough to retest on TG).

**Pull request merged**
