### PR TITLE
Clean up CODEOWNERS

### PR DESCRIPTION
**Pull request by peterschrammel**
Suggestion for clean-up

The purpose of this is to increase the recall on review requests and reduce noise for those who haven't been actively involved in CBMC for the last couple of months.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
I am trying to fix the failing GitHub actions in #5606.

**Review by chrisr-diffblue — APPROVED** [review]

**Review by NlightNFotis — APPROVED** [review]
LGTM.

**Comment by NlightNFotis** [comment]
@peterschrammel Can this be rebased on `develop` now?

**Review by martin-cs — APPROVED** [review]
I'm OK with this but I feel that the people who are actually affected should have a chance to say something.  Specifically I think this is @hannes-steffenhagen-diffblue @smowton @pkesseli @mgudemann @thk123 @cristina-david @cesaro @owen-mc-diffblue (nee @owen-jones-diffblue) @romainbrenguier @danpoe and @forejtv .   (I am leaving @peterschrammel and @tautschnig out because they have already reviewed).

**Comment by mgudemann** [comment]
@martin-cs thanks for pointing this out!
No problem to remove my name here.

**Review by cesaro — APPROVED** [review]

**Comment by martin-cs** [comment]
Adding @NathanJPhillips to the paging list.

**Review by thk123 — APPROVED** [review]
I'm quite happy to have my name removed :slightly_smiling_face:

**Pull request merged**
