### PR TITLE
[SEC-180] Overlay classes

### PR DESCRIPTION
**Pull request by NathanJPhillips**
This is the implementation of overlay classes as in https://github.com/diffblue/cbmc/pull/1816 except with a couple of issues fixed that caused problems in some dependant projects.

It allows multiple definitions of the same class to appear on the classpath, so long as all but the first definition are marked with the attribute `@java::com.diffblue.security.OverlayClassImplementation`. Overlay class definitions can contain methods with the same signature as methods in the original class, so long as these are marked with the attribute `@java::com.diffblue.security.OverlayMethodImplementation`; such overlay methods are replaced in the original file with the version found in the last overlay on the classpath. Later definitions can also contain new supporting methods and fields that are merged in.
This will allow insertion of Java methods into library classes to handle, for example, modelling dependency injection.

### CODE REVIEW

**Comment by thk123** [comment]
Can we get a TG pointer bump :innocent:?

**Comment by NathanJPhillips** [comment]
Might be worth not merging this until after Wednesday's release?

**Review by smowton — APPROVED** [review]
Conditional on TG bump of course :)

**Comment by NathanJPhillips** [comment]
Deeptest bump passes, @allredj tells me that Deeptest now includes regression tests that would catch the previously untested issues that this exposed with the models library. Are you happy for this to be merged, @thk123 ?

**Comment by allredj** [comment]
It's hard to see all the implications of that, but it doesn't seem to break anything at this point so I suppose it's good to go! It might be a useful feature for the modelling team, so thanks!

**Review by allredj — APPROVED** [review]

**Comment by allredj** [comment]
Sorry, I meant this feature is good to go in test-gen, but I haven't reviewed the code so I removed my approval here.

**Review by thk123 — COMMENTED** [review]
TG pointer bump passes :+1: 
Reviewed original code :+1: 
Reviewed diff from original code :+1: 

Could I just ask for a test for the new behaviour for when you have two class definitions on the class path, neither marked with overlay class, that the first one gets loaded and the program continues with just a warning.

**Comment by NathanJPhillips** [comment]
I believe Joel has added tests to Deeptest that exhibit this behaviour.

**Comment by allredj** [comment]
The test is here: https://github.com/diffblue/test-gen/blob/develop/regression/compile-java-tests/hash-map-simple-init-return/test2.desc
It checks that test-gen succeeds and only considers the class that comes first in the classpath sequence. It does not check for any warning message though.

**Review by thk123 — APPROVED** [review]
Fair - I thought it might be useful to have a test in CBMC but I suppose it is sort of deprecated behaviour anyway

**Pull request merged**
