### PR TITLE
[WIP] Use Visual Studio and CMake in Windows CI builds

### PR DESCRIPTION
**Pull request by tautschnig**
With CMake we can actually build natively on Windows/Visual Studio, there should
not be any need for Cygwin.

This is early testing, the PR will remain a draft until all issues are ironed out.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by karkhaz** [comment]
It looks like you're doing CI work, but please don't hesitate to ping me if there are any local things you'd like me to try out

**Comment by kroening** [comment]
Could you actually get rid of cygwin for the build?
This page may be helpful as roadmap:
https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/

**Comment by tautschnig** [comment]
> Could you actually get rid of cygwin for the build?

Given @karkhaz experience it should definitively be possible. I'm just trying to figure out how to do this in CodeBuild.

**Comment by tautschnig** [comment]
#5162 actually made this happen, closing.

**Pull request closed without merging**
