### PR TITLE
Use value_comparatort in replace() in the sharing map

### PR DESCRIPTION
**Pull request by danpoe**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]

**Review by smowton — CHANGES_REQUESTED** [review]
I didn't do this for `update` in the first place because it needlessly takes a copy of the thing you're updating, which will be pretty costly for `value_sett`, whose `mapped_type` is pretty heavy

**Comment by tautschnig** [comment]
@smowton Which operation is it that takes a copy? It seems all the operations involved in this change are constant, so really all of them should be taking const references?

**Comment by smowton** [comment]
The comparator stores a copy of its first argument. This was so we can provide an (expensive) debug mode for in-place updates, where we copy the value before the update and then check it has changed afterwards. Compare `replace`, where we have old and new values available simultaneously.

**Comment by danpoe** [comment]
@smowton I thought it didn't matter that `value_comparatort` takes an extra copy in `replace()`, since it would only happen in debug mode.

**Comment by smowton** [comment]
If you like, personally I'd prefer if even debug mode didn't crawl if it can be avoided

**Pull request closed without merging**
