### PR TITLE
Move symex-bmc and symex-coverage to goto-checker [blocks: 3583]

### PR DESCRIPTION
**Pull request by peterschrammel**
Based on #3565, review only last two commits

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [n/a] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [n/a] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [n/a] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [n/a] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 0205d09512befd879ff53cafe81d56aad36a6e60).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/94908846
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by tautschnig — APPROVED** [review]
Ok, but see also my comment on the other PR: these parts may be language-independent, but they are very much tied to bounded model checking. I'm wondering whether we need a "bmc" folder.

**Review by smowton — APPROVED** [review]

**Comment by tautschnig** [comment]
Marking do-not-merge until depended-on PRs are merged.

**Comment by peterschrammel** [comment]
> I'm wondering whether we need a "bmc" folder.

I think it's exaggerated to split out bmc into yet another module at this point. I'll put this down as an improvement suggestion for a later stage.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 7815d68ba790358360936d5da00eafbf14a99151).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96775271

**Pull request merged**
