### PR TITLE
Remove language_uit as it is no longer used

### PR DESCRIPTION
**Pull request by tautschnig**
Use initialize_goto_model to obtain goto programs, don't run parse() etc.
directly.

Only the last commit is new, the first four are #3683.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- n/a Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Review by martin-cs — APPROVED** [review]
Looks good.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: f23f5197ed89cdbd16cf4bd8c89ab88a6f97b37e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99082540
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
@allredj @peterschrammel @thk123 I suspect this needs a genuine TG bump. I'm not sure whether the solution is as simple as removing an unnecessary include or actually needs the kind of (improvement work) that was done in #3683.

**Review by peterschrammel — APPROVED** [review]
@thk123, seems the header is still included in TG, but not used.

**Comment by thomasspriggs** [comment]
I am looking into the TG fix.

**Comment by thomasspriggs** [comment]
@tautschnig Please re-base on latest CBMC develop branch. The joel-bot should then pass.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: ef193de58eceb79e9f699696d69535eedc0b12c8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99673225
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by thomasspriggs** [comment]
The joel-bot failure looks unrelated to the changes in this PR. The error is `error: ‘const class goto_programt::instructiont’ has no member named ‘function’`.

**Comment by tautschnig** [comment]
Thanks @thomasspriggs - I guess the update after #3126 isn't merged yet (or was not at the time of the bot running).

**Comment by thomasspriggs** [comment]
I have now merged the corresponding TG PR for #3126. So the joel bot should start passing again, on future runs.

**Pull request merged**
