### PR TITLE
Update brew before creating formula update PR

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

This PR update brew before bumping formula to prevent having git conflicts in homebrew-core repo. 
See  https://github.com/Homebrew/homebrew-core/pull/61260 and https://github.com/Homebrew/homebrew-core/pull/61823

### CODE REVIEW

**Review by hannes-steffenhagen-diffblue — APPROVED** [review]
Looks good to me, thank you very much!

**Review by NlightNFotis — APPROVED** [review]
LGTM, thanks for your contribution :)

**Review by chrisr-diffblue — APPROVED** [review]
Good catch! Thanks :-)

**Comment by hannes-steffenhagen-diffblue** [comment]
I'm merging despite codecov not doing anything, it's been running for 3 days and it's plainly obvious that this isn't affecting code coverage, and I'm not really willing to hold my breath for the bot to confirm this.

**Comment by bayandin** [comment]
Thanks, folks!

Looking forward to the next release, to see if it really helps 🙂

**Pull request merged**
