### PR TITLE
Remove string operations handled by models from string solver

### PR DESCRIPTION
**Pull request by danpoe**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by romainbrenguier — APPROVED** [review]

**Review by smowton — APPROVED** [review]

**Review by martin-cs — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d7963b9e6badfdbe998d19c89884951e0beed870).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125067466

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 21ee1e848d5d31c62e9651c1d0a99e1078bdbaa8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125215224

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 1000a9e1eb2835aae508c406ecb606275c54348c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/126450199
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 621478e4f24849ae9cc35ff0e1d43cfb6089ac9f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/126458601

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 48de77ef140a95a71b1e5edba3d9887566b30d15).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/126974176

**Pull request merged**
