### PR TITLE
No-assertions should not affect assertions in built-ins

### PR DESCRIPTION
**Pull request by peterschrammel**
This PR includes a clean-up of various checks whether something is a built-in.

### CODE REVIEW

**Comment by kroening** [comment]
Is there then any way at all to disable the built-in checks?

**Comment by peterschrammel** [comment]
Shall we distinguish between no-assertions at all and no-user-assertions?

**Comment by martin-cs** [comment]
On Thu, 2017-03-23 at 01:50 -0700, Peter Schrammel wrote:
> Shall we distinguish between no-assertions at all and no-user-assertions?

I can see a possible use for this in other languages which have some
assertions added as part of the semantics, but, on the other hand, I can
see that this could lead to a proliferation of flags.  What is the
original need / use case for this?

**Comment by peterschrammel** [comment]
It's a customer request who wants to disable his own assertions while keeping the checks in built-ins (Eg memory checks in free()).

**Comment by tautschnig** [comment]
I believe a users's assertions can be disabled by compiling/running with -DNDEBUG. So maybe more fine-grained control to permit disabled built-in assertions is required.

**Comment by tautschnig** [comment]
Overall, the first two commits are great, the third one seems debatable.

**Comment by peterschrammel** [comment]
The third commit was the actual reason for the PR ;)

The current description of the option --no-assertion says "ignore user assertions", which is confusing because it also disables built-in assertions. A user cannot really understand the difference between an instrumented assertion and a built-in assertion. The user only understands what her own assertions are and then sees assertions being added by CBMC.

Suggestion:
* `--no-assertions` ignores user assertions only
* Adding `--no-built-in-assertions` to disable built-in assertions

More fine-grained control over the latter can be introduced if requested.

**Comment by peterschrammel** [comment]
@tautschnig, this is green now.

**Pull request merged**
