### PR TITLE
Update java-models-library for diffblue/java-models-library#19 (getMo…

### PR DESCRIPTION
**Pull request by romainbrenguier**
…nitorCount)

https://github.com/diffblue/java-models-library/pull/19

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
Does this supersede #3464?

**Comment by tautschnig** [comment]
Also, would it be possible to include any tests that now work/produce a different result?

**Comment by peterschrammel** [comment]
https://github.com/diffblue/cbmc/tree/develop/jbmc/regression/jbmc-strings/TokenTest01 and https://github.com/diffblue/cbmc/tree/develop/jbmc/regression/jbmc-strings/TokenTest02 should work now.

**Comment by romainbrenguier** [comment]
@tautschnig 
> Does this supersede #3464?

I'm waiting for CI to see if it solves the problem of #3464 and it does, then yes it will supersede it.

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f9caf41046480e41ba8b7cfd132dd1e28f408f06).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/106541354

**Comment by romainbrenguier** [comment]
Now pointing to master and including more tests, superseeds https://github.com/diffblue/cbmc/pull/3464

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4254f76fe5005ccdc1fc8ee95c1d5b149632f79c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/106550266

**Review by allredj — APPROVED** [review]

**Pull request merged**
