### PR TITLE
rewrite_union no longer needs namespace

### PR DESCRIPTION
**Pull request by kroening**
Depends on #2697. Look at last commit only.

### CODE REVIEW

**Review by tautschnig — COMMENTED** [review]
I believe `rewrite_union` never needed a namespace in the first place, and the changes proposed here should actually be safe even without all the `ID_union_tag` work. I'd propose to rebase the new commit onto develop, making the PR truly independent.

**Comment by kroening** [comment]
Unfortunately, it does need the namespace right now, or you can't look up whether the symbol_type is a union or a struct.

**Comment by tautschnig** [comment]
> Unfortunately, it does need the namespace right now, or you can't look up whether the symbol_type is a union or a struct.

Oh yes, sorry.

Could this one be rebased onto the latest version of of #2697 or those commits be cherry-picked in here for CI to succeed?

**Review by tautschnig — APPROVED** [review]
The depended-on commit has been merged, should be ready to go once rebased.

**Comment by kroening** [comment]
Rebase done

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 7170711ac046b6d9ef98ca2941ea8c1b2fc5701b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84131501

**Pull request merged**
