### PR TITLE
Add coding standard line on member functions

### PR DESCRIPTION
**Pull request by romainbrenguier**
This is open for discussion. I think several people agree that non-member functions are clearer. 

See for example
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c4-make-a-function-a-member-only-if-it-needs-direct-access-to-the-representation-of-a-class

"Less coupling than with member functions, fewer functions that can
cause trouble by modifying object state, reduces the number of functions
that needs to be modified after a change in representation."

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [na] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [na] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by LAJW — APPROVED** [review]

**Comment by LAJW** [comment]
This stops 100-method classes from ever being conceived so I'm all for it.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 1cebdd141178023131a328cf904958877c232a71).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102346703

**Comment by tautschnig** [comment]
I certainly support the statement proposed to be added to the coding guidelines, but I'd ask people to think about the consequences.

1) We do not currently advise the use of namespaces, and thus non-member functions will pollute the global namespace, unless they can be made static (file-local).
2) When non-member functions are in some other way coupled, for example by invoking each other, adding a dependency on additional objects becomes a nightmare. I guess nobody worried much about it, but has anyone seriously thought about why https://github.com/diffblue/cbmc/blob/13b5e2b7b304b3a7d4f18460c18141901088845b/src/solvers/strings/string_constraint.cpp#L21 is a `null_message_handler`? Make that a proper message handler required a patch of several hundred lines, which I eventually abandoned. Really, that part of the code base is an example of how this newly proposed statement should not be applied.
3) Endless lists of parameters are bound to cause trouble.

**Comment by owen-mc-diffblue** [comment]
@tautschnig Do you think it would be possible to start using non-anonymous namespaces?

**Comment by romainbrenguier** [comment]
> I certainly support the statement proposed to be added to the coding guidelines, but I'd ask people to think about the consequences.
> 1. We do not currently advise the use of namespaces, and thus non-member functions will pollute the global namespace, unless they can be made static (file-local).
> 2. When non-member functions are in some other way coupled, for example by invoking each other, adding a dependency on additional objects becomes a nightmare. I guess nobody worried much about it, but has anyone seriously thought about why 
     [cbmc/src/solvers/strings/string_constraint.cpp](https://github.com/diffblue/cbmc/blob/13b5e2b7b304b3a7d4f18460c18141901088845b/src/solvers/strings/string_constraint.cpp#L21)  Line 21 in  [13b5e2b] /diffblue/cbmc/commit/13b5e2b7b304b3a7d4f18460c18141901088845b)  null_message_handlert null_message_handler; 
     is a `null_message_handler`? Make that a proper message handler required a patch of several hundred lines, which I eventually abandoned. Really, that part of the code base is an example of how this newly proposed statement should not be applied.
> 3. Endless lists of parameters are bound to cause trouble.

To address point 2 and 3 you can always group arguments in structs or pass the object by reference.

**Comment by tautschnig** [comment]
> @tautschnig Do you think it would be possible to start using non-anonymous namespaces?

Maybe someone just has to set a precedent to show that namespaces can be used in a meaningful way and be an improvement.

**Comment by tautschnig** [comment]
> To address point 2 and 3 you can always group arguments in structs or pass the object by reference.

Yes, but people actually have to do this. Doing one (making functions non-members) without the other (being careful about coupling) is bad. I don't even want to think about the moment where I see a commit moving functions to become non-members, citing the coding standard as the reason for doing so, but not paying attention to those other aspects.

**Comment by martin-cs** [comment]
I worry that once you start grouping arguments into structs, requiring some stateful coupling between elements and separating the functions that work on them into their own namespaces ... at some point aren't you just coming full circle and re-inventing object orientation?

It seems the underlying concern is to do with coupling and interfacing.  This could definitely be done better.  Where the functionality can be implemented using stable and clean interfaces, it makes sense for it to be a separate function.  Where there it needs to access the representation of an object or requires consistency between members / calls, it makes sense for it to be a member function.  Between the two ... there seems to be a grey area ... I think I would rather trust the judgement of the developers than try to enforce a "one size fits all" solution.

**Comment by LAJW** [comment]
@martin-cs
> I worry that once you start grouping arguments into structs, requiring some stateful coupling between elements and separating the functions that work on them into their own namespaces ... at some point aren't you just coming full circle and re-inventing object orientation?

We're not against object orientation. Certainly, the struct-passing style works best when working with immutable data in functional style. Interestingly enough, most of CBMC (and test-gen) could be (and already is on the higher level) implemented this way. Which is good. But we keep seeing this pattern, where people use a class (defined only in .cpp) instead of structs to _implicitly_ pass (mostly unused) function arguments. Which is bad for the same reason global variables are bad.

> It seems the underlying concern is to do with coupling and interfacing (...) I think I would rather trust the judgement of the developers than try to enforce a "one size fits all" solution.

I agree the point we're trying to make is subtle and easy to miss without an example.

Example:

Let's say we're implementing a string that automatically computes its hash. The invariant is that hash and data have to match:

```c++
class String {
  std::string data;
  size_t hash = std::hash<std::string>()("");
public:
  // methods - length, insert, etc.
};
```
If we follow the proposed rule blindly, we're going to try to devise the minimal interface necessary to accomplish everything we want - begin/end, insert, remove and maybe size. When thinking about the invariant, we only have to worry about these 5 functions. All other operations - find, find last, find first of, find last of, partition, split, slice, truncate, etc. implemented as free functions on top of it maintain the invariant automatically without any thinking by definition. Also, (if you use namespaces) you can expand the interface afterwards by writing your own free functions (almost like extension methods in C#/F#).

If we don't follow it and just do what initially seems convenient - put all of these hundreds of methods into the function, the implementer has to think hard about the invariants. And it's not possible to expand the interface in a consistent fashion, so you end up with a seemingly random interface, where most of the functions are members, but some are free. Which one is which tells you nothing.

I believe applying this rule is as important as forcing everyone to use `const` - with const you don't have to read function bodies to know your argument is not modified. With this rule, you don't have to read function bodies to know no invariants are violated. The ability to do both is why I like C++ so much.

**Comment by tautschnig** [comment]
> I believe applying this rule is as important as forcing everyone to use `const` - with const you don't have to read function bodies to know your argument is not modified. With this rule, you don't have to read function bodies to know no invariants are violated.

Except the situation is not quite as black and white as with `const`.

1) One question is what is the _object_ the "invariants" of which you are concerned about. You can of course reduce a struct/class down to an empty object, at which all the invariants are trivial, because there is only a single one. If there are data members, and you only have getters/setters for all the members then the invariants are also trivial. Of course, having all functions as non-static members is bad as described, because it makes the invariants very difficult to ascertain.
2) For performance reasons it may be better to implement operations as members that do violate invariants during processing and only restore consistency at the end.

One example of a middle ground, not _blindly_ following this rule are nested classes. A number of invariants are maintained by an inner "implementation" class, and the outer class then wraps a nice API around that which also ensures its own set of invariants. Blindly following the proposed rule would mean that the outer class didn't exist, because its methods would necessarily be non-member functions as they do not use any member (quite possibly the outer class only has a single member that is of the type of the inner class).

**Comment by LAJW** [comment]
@tautschnig 
> 1. One question is what is the _object_ the "invariants" of which you are concerned about.

 - If all members have to have getters and setters, then this is not a class. It's a "record". I like to represent these as methodless structs to signify that.
 - single member - why have a class around it in the first place - sounds like we could generalize our code
> 2. For performance reasons it may be better to implement operations as members that do violate invariants during processing and only restore consistency at the end.

Performance argument could be used against `const` too and many other things. However performance of 99% of the code doesn't really matter. Assuming usage of the right algorithms and containers of course. This rule is about those 99%.

> One example of a middle ground, not _blindly_ following this rule are nested classes. A number of invariants are maintained by an inner "implementation" class, and the outer class then wraps a nice API around that which also ensures its own set of invariants. Blindly following the proposed rule would mean that the outer class didn't exist, because its methods would necessarily be non-member functions as they do not use any member (quite possibly the outer class only has a single member that is of the type of the inner class).

 - Inner classes have some unrelated problems in C++, so I'm just going to tackle "implementation classes"
 - If the outer class has multiple members _that have to kept be in sync_, by all means, leave it be. Even if they happen to be class instances.
 - If the outer class has only a single member and we're adding extra invariants...
IMO We shouldn't do that. (though perhaps I'm lacking imagination here). Single-member classes have their place. I'm not against wrappers around 3rd party APIs or using the PIMPL idiom. But if we have full control over a class, we should lock it down the first time around.

**Comment by martin-cs** [comment]
> We're not against object orientation.

Should I read any significance into the plural here?  Are you
representing the views of a group of people?

>  But we keep seeing this pattern, 
> where people use a class (defined
> only in .cpp) instead of structs to 
> _implicitly_ pass (mostly unused)
> arguments. Which is bad for the 
> same reason global variables are bad.

I may be mistaken but I think you are referring to the aftermath of the
last "let's make interfaces functions not classes".

> > It seems the underlying concern is to do with coupling and
> > interfacing (...) I think I would rather trust the judgement of the
> > developers than try to enforce a "one size fits all" solution.
> 
> I agree the point we're trying to make is subtle and easy to miss
> without an example.
<example removed>

To me this is an argument for coming up with a minimal, orthogonal
interface and that allows a strong object invariant.  This is a good
thing and I hope that reviews would check for this kind of thing.

What I don't get is the connection between a good design principle and
the proposed coding style.  The "avoid non-member functions" style is
neither a necessary nor a sufficient condition for good design.  There
are cases where using that style can help, there are cases where it can
hinder.  Rather than talk in abstract generality about which style is
'best' and then try to force that on everyone; I think we should trust
programmers to use their own judgement on how to design solutions to
specific problems.

**Comment by romainbrenguier** [comment]
> What I don't get is the connection between a good design principle and
the proposed coding style.  The "avoid non-member functions" style is
neither a necessary nor a sufficient condition for good design.  There
are cases where using that style can help, there are cases where it can
hinder.  Rather than talk in abstract generality about which style is
'best' and then try to force that on everyone; I think we should trust
programmers to use their own judgement on how to design solutions to
specific problems.

Sure, maybe we should reformulate so that it does not sound as a strict rule but a preference.
My goal with this rule was to have a way of coming to a decision in the case where the developer and the reviewer disagree.

**Comment by tautschnig** [comment]
> My goal with this rule was to have a way of coming to a decision in the case where the developer and the reviewer disagree.

The best way to solve such disagreement is to provide facts that speak in favour of a change. Examples of such facts include bugs fixed, code being removed, improved performance, or enabling a future change that would yield such improvements. There are also softer criteria such as maintainability, but, given their less measurable nature, they may require discussion (which is generally best done before embarking on such changes).

For new code, the author is trusted to use the most appropriate style as @martin-cs said. If it helps to put remarks in the coding guidelines then so be it.

Changes in style to existing code without undisputed evidence of improvement do not add customer value. They have high cost 1) because they invalidate patches (whether in pull requests or kept private) and 2) eat up developers' time who could instead work on changes that do have customer value.

**Comment by LAJW** [comment]
> Should I read any significance into the plural here?

In that case I meant me and @romainbrenguier (from my perspective) as we were talking about this offline. My personal preferences, I prefaced with IMO.

> I may be mistaken but I think you are referring to the aftermath of the last "let's make interfaces functions not classes".

Quite the contrary - this is what happens when we _start_ with a function and force-use classes to implement it:
 - `goto-analysis/taint_analysis.cpp` - the class was created 10 days after the file itself, the function was first.
 - `java_bytecode/object_factory.cpp` - header always contained only functions. Classes were added afterwards only in the .cpp file.
 - `goto-programs/goto-convert-class.h` - This might be my favorite. Class exists in the header, but that class has only constructors and no public methods (inheriting classes do the same). Constructors do all the work. I don't believe this is what object-oriented programming is about.

There are many more examples.

In all these cases, the author used a class to represent a function. We could re-write these classes with an explicit `struct` being passed around, and it would look nearly identical. But gives us a bit more power:

 - A member function that writes to one of its class's members and reads from every other one cannot be marked `const`. With free functions, we can create another struct that groups the `const` part together and pass the mutable member separately. This enables constness in more places.
 - If we only use 2/10 members of the struct, because we're already working with functions, we'd create another free function that only uses those two methods, and it wouldn't look out of place. Right now I have a problem where some people block my PRs telling me I should make it a member function. This wastes developer time because I have to make this exact argument over and over again.

For me "good" code is one which one can easily unit test. Classes without any public methods and lots of internal state/side effects are hard. "Doer" classes with the `doIt` or `operator()` are too - because we have to think about and handle the case where that `doIt` method is called twice. This isn't a problem with functions, because they don't store any state. That doesn't mean I think we should unit test everything. But we should at least have the ability to.

**Comment by tautschnig** [comment]
> * Right now I have a problem where some people block my PRs telling me I should make it a member function. This wastes developer time because I have to make this exact argument over and over again.

Problems involving people need to be solved with people, e.g., by sitting down and having a meeting. Solving them via text documents is not the way to go. Bring all of the people who are in disagreement into one room, with a concrete piece of code that is being contested, and work out why there is disagreement.

> For me "good" code is one which one can easily unit test. Classes without any public methods and lots of internal state/side effects are hard. "Doer" classes with the `doIt` or `operator()` are too - because we have to think about and handle the case where that `doIt` method is called twice. This isn't a problem with functions, because they don't store any state. That doesn't mean I think we should unit test everything. But we should at least have the ability to.

I do agree with pretty much everything that you said on this thread, and certainly with this one. I just don't think that putting a statement in coding guidelines has anything to do with this.

**Comment by romainbrenguier** [comment]
> Problems involving people need to be solved with people, e.g., by sitting down and having a meeting. Solving them via text documents is not the way to go. Bring all of the people who are in disagreement into one room, with a concrete piece of code that is being contested, and work out why there is disagreement.

Organizing a meeting every time I'm making a function static, and repeat the same arguments every time, doesn't seem to be a good use of our time. I suggested this change in the guidelines so that we can have that discussion once, and avoid having it reappear all the time.

**Comment by tautschnig** [comment]
> Organizing a meeting every time I'm making a function static, and repeat the same arguments every time, doesn't seem to be a good use of our time.

How many of those meetings have you held thus far? If you have tried this and it failed then I'll accept that my proposal is apparently not applicable. If you haven't tried it yet, then I'd suggest you do. I believe a single meeting will do.

**Comment by martin-cs** [comment]
On Wed, 2019-02-27 at 05:35 -0800, Michael Tautschnig wrote:
> > * Right now I have a problem where some people block my PRs telling
> > me I should make it a member function. This wastes developer time
> > because I have to make this exact argument over and over again.
> 
> Problems involving people need to be solved with people, e.g., by
> sitting down and having a meeting. Solving them via text documents is
> not the way to go. Bring all of the people who are in disagreement
> into one room, with a concrete piece of code that is being contested,
> and work out why there is disagreement.

Completely agree.

**Comment by LAJW** [comment]
> How many of those meetings have you held thus far?

3-ish and countless GitHub debates.

**Comment by NlightNFotis** [comment]
I do not understand this change. The point of object orientation, and types in that sense, is to group together state and functionality that affects that state, into logical units that make it easier to modify or add new state mutation functions.

Free functions have no indication about what kind of logical data they operate upon, aside from their type signature. You can argue that you can get that if you read the type signature, but then again, object orientation was invented as a layer above procedural programming for this particular reason.

> To me this is an argument for coming up with a minimal, orthogonal interface and that allows a strong object invariant. This is a good thing and I hope that reviews would check for this kind of thing.

Wholeheartedly agree with Martin on this one. In my opinion, if a method should provide guarantees about how it has transformed the state of the object at entry and at exit, then it should do it Hoare-logic style, with contracts.

**Comment by tautschnig** [comment]
It sounds like this should be a topic for after-work drinks. I'm out of this one, nothing technical to address here.

**Comment by romainbrenguier** [comment]
> I do not understand this change. The point of object orientation, and types in that sense, is to group together state and functionality that affects that state, into logical units that make it easier to modify or add new state mutation functions.

There are other ways of grouping functionality, like modules, files and namespace (but we don't use those).

> Free functions have no indication about what kind of logical data they operate upon

:dizzy_face:

**Comment by romainbrenguier** [comment]
I will close this PR since it seems the conclusion is this should really be decided on a case-by-case basis.

**Pull request closed without merging**
