### PR TITLE
Remove shadowing "options" from jdiff/goto_diff methods [blocks: #2310]

### PR DESCRIPTION
**Pull request by tautschnig**
As these inherit from language_uit, there is already an options member
available. Also do not make functions virtual unnecessarily, there is not
inheritance anywhere.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Review by chrisr-diffblue — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5243777d1c7ee0af57151bba3a0a251817193274).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96307609

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 717ed29388086fc1236f0dbd0ccce3d7d34ac650).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96870618

**Review by peterschrammel — COMMENTED** [review]
I'd prefer removing the inheritance from `language_uit`.

**Review by martin-cs — APPROVED** [review]
goto-analyzer changes seem fine.

**Comment by tautschnig** [comment]
@peterschrammel This should be done now, please take another look.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 35682c62e59600c7c6be7996c907cffa164d35c3).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97567687
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
I am surprised this trips up TG. @peterschrammel when reviewing, could you please also check what's going on on that side.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 2e00325784d92433c8b98145c7c57c08ac16450a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98030661

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 9e2cafa58c08abb687e03b27d76e977d7eadba42).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98123412

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 85d27e54c897fc4d96b1df27e95ac789b336d323).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98715502

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 85d27e54c897fc4d96b1df27e95ac789b336d323).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98715502

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: c83f8686771df6be3fc1e6ef4f9dcb26f36178e6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98930579
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: cb4352465698c6e8bc1002113951947d08251619).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99030561

**Pull request merged**
