### PR TITLE
Cover (and others) for reachable functions only

### PR DESCRIPTION
**Pull request by peterschrammel**
The default behaviour of CBMC for the options --show-goto-functions,
--show-properties and --cover is to consider all functions. This
is particularly annoying for --cover where coverage goals are
reported from functions that are not reachable from the entry point.
Also, --show-reachable-properties has been introduced in the past
to hide such properties.

We could change the default behaviour to slicing away everything
that is not reachable from the entry point. However, this would
require an extra option to be able to view functions and properties
that are not reachable.

This PR preserves the default behaviour and enables focussing
the output of --show-goto-functions --show-properties and --cover
on reachable functions using --reachable-functions.

The option --show-reachable-properties could be removed (including cbmc_parse_options.cpp:543-556).

### CODE REVIEW

**Comment by tautschnig** [comment]
Shouldn't it be `--used-functions` rather than "reachable"? Indeed only `--cover` would give some information about reachability.

**Comment by kroening** [comment]
I'd also prefer the terminology 'used'. The word 'reachable' really usually means 'a path exists'. Another option could be '--drop-unused-functions', which may be clearer.

**Comment by peterschrammel** [comment]
Agreed. What do we do with `--show-reachable-properties` then?

**Comment by tautschnig** [comment]
I'd say it should never have been there in the first place... I very much like your suggestion of getting rid of it.

**Comment by martin-cs** [comment]
On Thu, 2017-03-23 at 10:45 -0700, Michael Tautschnig wrote:
> I'd say it should never have been there in the first place... I very much like your suggestion of getting rid of it.

I have a vague feeling this was added as a customer request...  Maybe
@kroening can remember.

**Comment by tautschnig** [comment]
The commit message of 22df5471d doesn't answer the "why?" Just sayin'.

**Pull request merged**
