### PR TITLE
Use C++17

### PR DESCRIPTION
**Pull request by tautschnig**
Use C++17 now that it has become a build requirement.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by thomasspriggs** [comment]
I am in favour of moving to C++17. This will allow us to remove the library code which has been back ported C++11, which will reduce the maintenance needed. It would also support using `std::variant` without having to add a back port of it.

**Review by martin-cs — APPROVED** [review]
In principle... OK.  But:

1. Are there any currently supported linux distros that don't have `g++ --version >= 7.0`?  I don't think so but RedHat and derivatives do tend to ship surprisingly old versions of tools.
2. I am not seeing any changes to the CI set up.  Is that because all of the tested platforms are already using a suitable version?

**Comment by tautschnig** [comment]
> In principle... OK. But:
> 
>     1. Are there any currently supported linux distros that don't have `g++ --version >= 7.0`?  I don't think so but RedHat and derivatives do tend to ship surprisingly old versions of tools.
> 

According to https://access.redhat.com/solutions/19458, only RHEL 8 has a version of GCC new enough to build current CBMC (which requires GCC 5), but then that new-enough version is GCC 8, so we should be fine. But perhaps @TGWDB has an idea whether there might be any other users who might be unable to use a new-enough version of GCC.

>     2. I am not seeing any changes to the CI set up.  Is that because all of the tested platforms are already using a suitable version?

That's correct, no changes needed.

**Comment by tautschnig** [comment]
> I am in favour of moving to C++17. This will allow us to remove the library code which has been back ported C++11, which will reduce the maintenance needed. It would also support using `std::variant` without having to add a back port of it.

Feel free to create a PR against my branch so as to introduce the use of `std::variant`: I've now added a bunch of commits that make good use of C++17, mostly by removing code.

**Comment by TGWDB** [comment]
> According to https://access.redhat.com/solutions/19458, only RHEL 8 has a version of GCC new enough to build current CBMC (which requires GCC 5), but then that new-enough version is GCC 8, so we should be fine. But perhaps @TGWDB has an idea whether there might be any other users who might be unable to use a new-enough version of GCC.

I'm not aware of Linux users who might have issues, but we need to make sure MSVC builds work. I believe as long as we have support for MSVC 2019 (currently tested in CI) we are ok.

**Comment by esteffin** [comment]
As already agreed this now depends on #7989

**Comment by tautschnig** [comment]
Closing as all commits have been moved into PRs of their own (#8028, #8031, #8032, #8033, #8034).

**Pull request closed without merging**
