### PR TITLE
New language frontend API

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Comment by tautschnig** [comment]
A couple of comments:
1) Splitting out `goto_functiont` from `goto_functionst` should probably be a PR of its own as that can be merged more or less immediately. The remaining parts (the main purpose of this PR) will likely yield more discussion.
2) `class ansi_c_frontendt : public goto_frontendt` looks really good!
3) The actual API of a `goto_frontendt` feels very random. It's not particularly clear to me that these functions are essential ingredients of a language front-end.

**Comment by kroening** [comment]
Seaparate PR for d5ca15c.

Yes, discussion on the API is expected. The design goals are
1) keep it simple
2) enable current consumers of the data to remain at least very similar.

Two things are missing:
1) A means of looking up symbols
2) A way of post-processing symbols or functions. There is Chris' suggestion to accept a list of functors that do so; an alternative is that these return rvalues, and ownership is passed out.

**Comment by kroening** [comment]
Update: the consensus on the post-processing was to return rvalues; this separates storage from post-processing. A Chris-S-style front-end can be achieved on top, if desired.

**Comment by smowton** [comment]
The functor pattern is not particularly necessary, just so long as something like `lazy_goto_modelt` can be realised, with functions being converted and then post-processed on demand.

**Comment by kroening** [comment]
Ok, I'll add that as a layer.

**Comment by peterschrammel** [comment]
Another requirement that needs to be considered is the one of goto-diff where two programs (goto-binaries, or JARs in jdiff) are loaded, which results into two goto models (with their respective symbol tables).

**Comment by TGWDB** [comment]
Closing due to inactivity and work required for this to be suitable to merge. Please reopen if you believe this is erroneous.

**Pull request closed without merging**
