### PR TITLE
Make EXIT and SIGNAL patterns a requirement in test specifications

### PR DESCRIPTION
**Pull request by tautschnig**
This will make sure regression tests do not spuriously pass despite, e.g.,
failing an invariant.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: be59b3d358c404c2c42bff024b40628d4d1d90fc).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95529385

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d8db26be71026d1845fc1cd5ebb7d73b81688336).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95540565

**Comment by tautschnig** [comment]
@allredj @thk123 Heads-up: this might break TG tests, if those are also using test.pl. Please do a run and implement fixes similar to those in the first commit of this PR.

**Review by kroening — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Comment by allredj** [comment]
Will process this one shortly. Please don't merge in the mean time.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d6213f744076c1f5aefef66ddc8c976c5b5ba5ab).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96188312

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 874732e8004fc9557f54b263e7ee1f659ba89ddc).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96323714

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 0ed760b30a57ce1c0bbb2589b8fc182d4bcb2aa5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96757780
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 19aaa2659ea56ebd809136daf171f7ced0b0c1c8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98731462

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: cdf1659d12db31d5c61143d13047527484afec51).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99466991
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 94a3b75f272d9cb822361bf0d64b460b883fd22a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99537046

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 1178a56e64e18fca3e8582d48f6fda171e567357).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99774610

**Comment by romainbrenguier** [comment]
This breaks our tests. Not that there is something wrong with the changes but rather that we use the perl script in a wrong way. @thk123 can we come up with a plan for that?

**Comment by tautschnig** [comment]
@romainbrenguier Is it more than just making the changes that I've had to make in this repo as documented in the first commit?

**Comment by romainbrenguier** [comment]
> @romainbrenguier Is it more than just making the changes that I've had to make in this repo as documented in the first commit?

The error looks very different, so it seems a bit more complicated than that.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f721a3e99dbadb91dd10f41b77b48fbb26f525ad).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/101217387

**Comment by tautschnig** [comment]
The EXIT and SIGNAL patterns are now only required if `-e` is specified, thus TG is free to omit them. Will merge as soon as CI passes.

**Pull request merged**
