### PR TITLE
Revert symex renaming

### PR DESCRIPTION
**Pull request by tautschnig**
This is just a temporary measure to help TG get back on track. As soon as the problems in TG have been sorted out this PR should again be reverted to bring back the improvements in symex renaming.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]
patch(diff^-1, patch(diff, x)) == x, 
but CI(x, patch(diff, x)) != CI(patch(diff, x), patch(diff^-1, patch(diff, x))) ;)

**Comment by allredj** [comment]
TG update: https://github.com/diffblue/test-gen/pull/2878

**Comment by tautschnig** [comment]
> CI(x, patch(diff, x)) != CI(patch(diff, x), patch(diff^-1, patch(diff, x))) ;)

Because clang-format(diff) != clang-format(diff^-1)  ... ;-)

I'll add a clang-format patch, which should then equally be reverted.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 60ce9975e69cc388b88fdcd57dc2fbb89a98fff1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98632766
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — APPROVED** [review]
Still waiting for TG CI, but LGTM

**Comment by allredj** [comment]
TG bump is passing.

**Pull request merged**
