### PR TITLE
Public CPROVER documentation [TG-2181]

### PR DESCRIPTION
**Pull request by zemanlx**
I have added script that updates publicly accessible CPROVER documentation from every build of `develop` branch.

In a separate issue, I have created Google storage bucket and DNS record for cprover.diffblue.com to host this documentation.

The update should be accessible in 60 seconds after upload.

This work was requested by @peterschrammel 

---

Example of run from my fork
https://travis-ci.org/zemanlx/cbmc/jobs/355420511
updated http://cprover.diffblue.com

### CODE REVIEW

**Review by thk123 — APPROVED** [review]
:tada: whooo! How hard would it be to do something similar for the TG repo?

**Comment by tautschnig** [comment]
At least in this job here, this doesn't seem to be working - from the Travis log:
```
openssl aes-256-cbc -k ${gcloud_travis_cbmc_key} -in gcloud-travis-cbmc.json.enc -out gcloud-travis-cbmc.json -d
unknown option 'gcloud-travis-cbmc.json.enc'
```
Is some additional set-up necessary that @zemanlx has already done in his fork?

**Comment by zemanlx** [comment]
@tautschnig Yes, I know. It was working for my fork but looks like that Travis in `diffblue/cbmc` is not handling environment variables as it should. That's a tricky part of this kind of changes, you do not know that it is working before you create a PR (that will spam a lot of people) and until it is merged to `develop`.

As soon as I get it working in this PR I will let you know.

**Comment by zemanlx** [comment]
Looks like that you have to believe me that it is working.

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

> Pull requests sent from forked repositories do not have access to encrypted variables or data.

https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions

**Comment by tautschnig** [comment]
> Looks like that you have to believe me that it is working.

I see no problem with that; I had just tried to inspect the logs to make sure no unencrypted keys become visible, which is where I noticed the problem.

**Review by tautschnig — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
