### PR TITLE
Remove memory_limit and substitute

### PR DESCRIPTION
**Pull request by tautschnig**
memory_limit is not portable and should thus likely be moved to a different repository (where portability is not of immediate concern). Any use of substitute should likely be replaced by STL or other, more efficient code. Do not merge until approved by test-gen team members.

### CODE REVIEW

**Review by peterschrammel — COMMENTED** [review]
Waiting for TG bump to pass CI

**Comment by peterschrammel** [comment]
@tautschnig, please rebase. The branch point is behind TG's submodule pointer.

I suggest to merge #2210 first, so that you don't have to rebase it twice.

**Comment by tautschnig** [comment]
@peterschrammel Rebase done.

**Review by peterschrammel — APPROVED** [review]
Looks ready to merge.

**Pull request merged**
