### PR TITLE
Add CSmith GitHub action

### PR DESCRIPTION
**Pull request by tautschnig**
Run 10 randomly generated CSmith tests as a GitHub action to perform an
integration test involving CBMC and goto-instrument --dump-c. Each test
is first compiled and run using GCC to obtain a checksum, which is then
included as an assertion for CBMC to verify.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by hannes-steffenhagen-diffblue** [comment]
This seems like a good idea but the script could use some more explanation for what is going on there.

**Comment by tautschnig** [comment]
> This seems like a good idea but the script could use some more explanation for what is going on there.

Indeed. I've added comments!

**Review by martin-cs — APPROVED** [review]
I /really/ like the concept but ... non-deterministic things make me nervous.  I would be happier if the `scripts/csmith.sh` took a random seed and `csmith.yml` set it to the hash of the diff or something similar that could be locally reproduced.

I'm also a little unsure about what you feel should happen if you find issues of this form.  Is it the job of the person who submitted the PR to fix them?  Raise issues?

**Comment by hannes-steffenhagen-diffblue** [comment]
@martin-cs I'd say failure for these is not PR raiser responsibility, but if something does come up we should definitely take note.

**Review by hannes-steffenhagen-diffblue — APPROVED** [review]
IMHO "cbmc matches csmith test behaviour" and "goto-cc --> dump-c should yield program with same behaviour" are two different tests and probably shouldn't be in the same script, but otherwise I think this is a good addition for finding potential problems hopefully before users run into them.

**Review by NlightNFotis — APPROVED** [review]
This is great!

**Comment by tautschnig** [comment]
> I /really/ like the concept but ... non-deterministic things make me nervous. I would be happier if the `scripts/csmith.sh` took a random seed and `csmith.yml` set it to the hash of the diff or something similar that could be locally reproduced.
> 

Very good point - I've now modified the script to:
1) Generate a seed (using `date +%s`) and print that seed.
2) Add the ability to re-run with a particular seed.

> I'm also a little unsure about what you feel should happen if you find issues of this form. Is it the job of the person who submitted the PR to fix them? Raise issues?

I've done multiple thousands of runs of CSmith in recent weeks, and am thus fairly confident that the likelihood of a PR tripping this up by a bug outside the changes introduced in said PR are fairly low. Thus I'd argue it is the job of the person who submitted the PR to get this back in working order.

**Comment by tautschnig** [comment]
> IMHO "cbmc matches csmith test behaviour" and "goto-cc --> dump-c should yield program with same behaviour" are two different tests and probably shouldn't be in the same script, but otherwise I think this is a good addition for finding potential problems hopefully before users run into them.

Yes, having two separate jobs might be nicer, but I'm a bit hesitant to have almost-the-same-script twice in the repository. So I'd for now stick with the current solution. If we find that we regularly only run into bugs in one or the other part then that'll provide an incentive to improve this.

**Comment by martin-cs** [comment]
@tautschnig : sounds great; let's do it!

**Pull request merged**
