### PR TITLE
Java frontend: only run cproverNondetInitialize after all fields are initialized

### PR DESCRIPTION
**Pull request by smowton**
Previously cproverNondetInitialize was accidentally run after every superclass initialisation, not just after the whole initialisation sequence is complete. For example, if we had
```
class A { int a; }
class B extends A { int b; }
```
and B has a `cproverNondetInitialize` method, then would get something like
```
nondetb.@A.@java.lang.Object = { @class_identifier = ... };
nondetb.cproverNondetInitialize();
nondetb.@A.a = NONDET(int);
nondetb.cproverNondetInitialize();
nondetb.b = NONDET(int);
nondetb.cproverNondetInitialize();
```

This is mostly harmless, but can cause a verification failure if the A or B contains an array member, as their data field will not have been initialised yet (this is demonstrated in a new test case).

This change should also have a positive side-effect: B.cproverNondetInitialize will now run in the case of a `class C extends B {}`, which it wouldn't before -- this is demonstrated in new test case NondetInit3.

### CODE REVIEW

**Comment by smowton** [comment]
@jeannielynnmoulton may also want to review this (can't tag you for some reason)

**Comment by jeannielynnmoulton** [comment]
@smowton It's because I am not in the club.

**Review by allredj — APPROVED** [review]
I don't really understand what `struct_tag` does, but if the commit does what it says it does, then it all looks good to me! I ran all the models-library test with no problems on this version.

**Comment by smowton** [comment]
`struct_tag` is the tag of the type we've just initialised, cf. `class_identifier` which is the tag of the type of the outermost object (so if we're currently initialising "Base" in the context of "Child", `struct_tag == "Base"` and `class_identifier == "Child"`

**Review by romainbrenguier — APPROVED** [review]

**Comment by jeannielynnmoulton** [comment]
When I ran the models-library tests locally with these changes, there was a loss of coverage:

```
Failed Step: Generate tests for "HashSetArgInteger.test" in "target/classes/HashSetArgInteger.class"
        Specification: /Users/jeanniemoulton/Documents/GitHub/test-gen/lib/models-library/model/modelTests/specs/java/util/HashSet.spec:25
        Error Message: java.lang.AssertionError: Lines 7 12 are not covered by a generated test
```

It's not clear that this is related to this change or not, but should be investigated. (Will do after I finish up some other sprint work)

**Comment by allredj** [comment]
OK, it seems a submodule update on test-gen is necessary to be sure that fix does not introduce any regression.

**Comment by smowton** [comment]
@jeannielynnmoulton @allredj created bump https://github.com/diffblue/test-gen/pull/1427, which looks good as the cause of the lost coverage appears to have been https://github.com/diffblue/models-library/commit/5b79203c8bc49ced2fa44cbe82927036b2351ca1#diff-46a468b3a84239013a2624698c40daaf

**Review by mgudemann — APPROVED** [review]
LGTM

**Pull request merged**
