### PR TITLE
allow binary arithmetic of a vector type and a scalar type

### PR DESCRIPTION
**Pull request by kroening**
This is required for regression/ansi-c/MMX2 to pass on newer versions of
clang.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
Could we please have a test that exercises this in CI right now? Arguably CI has been passing so maybe we're testing this on someone's box, but that's not reliable.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 97335e54882863f0a736ba0bdcc213fa600d8f26).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86507292

**Comment by kroening** [comment]
@tautschnig Added to an existing test.

**Review by tautschnig — APPROVED** [review]
Thank you for adding to the test!

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: bc7fa6be17b75092a99286ec12b32fa2d3b3c6dd).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86583856

**Pull request merged**
