### PR TITLE
Create CMBC Version 5.48.0 for Release

### PR DESCRIPTION
**Pull request by TGWDB**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by chrisr-diffblue — APPROVED** [review]

**Comment by tautschnig** [comment]
@TGWDB I think this needs a full rebase rather than a merge?

**Comment by TGWDB** [comment]
> @TGWDB I think this needs a full rebase rather than a merge?

I did a full rebase, I'm not sure why this is not showing clearly here.

**Comment by tautschnig** [comment]
> > @TGWDB I think this needs a full rebase rather than a merge?
> 
> I did a full rebase, I'm not sure why this is not showing clearly here.

https://github.com/TGWDB/cbmc/commits/20220106-cbmc-version-5.48.0 also suggests that this isn't a clean rebase. I'd expect the sequence
```
git fetch <upstream>
git branch --set-upstream-to=<upstream>/develop
git rebase
```
to produce a clean result?

**Comment by TGWDB** [comment]
> > > @TGWDB I think this needs a full rebase rather than a merge?
> > 
> > 
> > I did a full rebase, I'm not sure why this is not showing clearly here.
> 
> https://github.com/TGWDB/cbmc/commits/20220106-cbmc-version-5.48.0 also suggests that this isn't a clean rebase. I'd expect the sequence
> 
> ```
> git fetch <upstream>
> git branch --set-upstream-to=<upstream>/develop
> git rebase
> ```
> 
> to produce a clean result?

Results as below:
```
tgw@DB0907:~/github/playground-cbmc$ git fetch upstream
tgw@DB0907:~/github/playground-cbmc$ git branch --set-upstream-to=upstream/develop
Branch '20220106-cbmc-version-5.48.0' set up to track remote branch 'develop' from 'upstream'.
tgw@DB0907:~/github/playground-cbmc$ git rebase
First, rewinding head to replay your work on top of it...
Applying: Version 5.48.0
Applying: Version 5.48.0
Using index info to reconstruct a base tree...
M       src/config.inc
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
tgw@DB0907:~/github/playground-cbmc$
```

I'm starting a new fresh PR since this one seems to have issues.

**Comment by tautschnig** [comment]
> Results as below:
> 
> ```
> tgw@DB0907:~/github/playground-cbmc$ git fetch upstream
> tgw@DB0907:~/github/playground-cbmc$ git branch --set-upstream-to=upstream/develop
> Branch '20220106-cbmc-version-5.48.0' set up to track remote branch 'develop' from 'upstream'.
> tgw@DB0907:~/github/playground-cbmc$ git rebase
> First, rewinding head to replay your work on top of it...
> Applying: Version 5.48.0
> Applying: Version 5.48.0
> Using index info to reconstruct a base tree...
> M       src/config.inc
> Falling back to patching base and 3-way merge...
> No changes -- Patch already applied.
> tgw@DB0907:~/github/playground-cbmc$
> ```
> 
> I'm starting a new fresh PR since this one seems to have issues.

The above looks good to me: your branch had two instances of the "Version 5.48.0" commit, and the second one got skipped when rebasing. That leaves you with just one such commit, which is what we'd have hoped for?

**Pull request closed without merging**
