### PR TITLE
Improves type checking for __CPROVER_assigns clauses

### PR DESCRIPTION
**Pull request by feliperodri**
Assigns clauses should only accept symbols, dereferences and struct members.

Signed-off-by: Felipe R. Monteiro <felisous@amazon.com>

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by feliperodri** [comment]
cc. @aalok-thakkar

**Review by chrisr-diffblue — APPROVED** [review]
Looks reasonable to me. One small request might be to tweak the PR title just to make it clear that the assigns clause is the _CPROVER_assigns - just makes skimmng through commit histories a bit simpler :-)

**Comment by kroening** [comment]
What about array members?

**Comment by thomasspriggs** [comment]
I have some minor comments on code style. I have pushed 3 commits which explain and alter the style to this branch - [https://github.com/thomasspriggs/cbmc/commits/tas/assigns-clause-type-checking](https://github.com/thomasspriggs/cbmc/commits/tas/assigns-clause-type-checking)
These comments should be considered to be suggestions for improvement, not anything which needs to be addressed before this PR is merged.

**Comment by feliperodri** [comment]
> What about array members?

Assigns clause do not properly work for array members, so we're gonna fix and add this support with more regression tests on a separate PR.

**Comment by feliperodri** [comment]
> I have some minor comments on code style. I have pushed 3 commits which explain and alter the style to this branch - https://github.com/thomasspriggs/cbmc/commits/tas/assigns-clause-type-checking
> These comments should be considered to be suggestions for improvement, not anything which needs to be addressed before this PR is merged.

Thanks, Thomas! I adopted your second suggestion.

**Pull request merged**
