### PR TITLE
Change doxygen download URL for Travis

### PR DESCRIPTION
**Pull request by danpoe**
The previous download URL doesn't work anymore

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- n/a Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by thk123 — APPROVED** [review]

**Review by NlightNFotis — APPROVED** [review]
Thanks Dan!

**Comment by hannes-steffenhagen-diffblue** [comment]
We had some concerns about this maybe breaking the doxygen checks on travis, let's wait and see if those work before merging.

**Comment by thk123** [comment]
I'm happy if it works - though should we switch back (and update the version), that way we're using the latest version

**Comment by danpoe** [comment]
@hannes-steffenhagen-diffblue This is the same version as we had previously, so all the checks should still pass.

@thk123 Just wanted to get this in quickly so merges on develop aren't blocked. We can later see about switching to the latest version of doxygen. The newest version is also available via the source forge link so we'd just need to change DOXYGEN_VERSION in the travis.yml file.

**Pull request merged**
