### PR TITLE
Remove badges from JBMC readme

### PR DESCRIPTION
**Pull request by yumibagge**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- n/a Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d01983a1b1861735a80714b0df3cb39dc804b09a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/118976766

**Comment by tautschnig** [comment]
Why just the JBMC readme?

**Comment by yumibagge** [comment]
> Why just the JBMC readme?

Are there any other readme.md that I should add this badge? CBMC readme.md already has it.

**Comment by tautschnig** [comment]
> Are there any other readme.md that I should add this badge? CBMC readme.md already has it.

Ah, I wasn't aware it already was in the CBMC README. That actually begs the question: why add it to README files in any subfolders at all?

**Comment by yumibagge** [comment]
> Ah, I wasn't aware it already was in the CBMC README. That actually begs the question: why add it to README files in any subfolders at all?

I will have to redirect the question to @peterschrammel as he wanted me to add this badge for JBMC ...

**Comment by peterschrammel** [comment]
Good question. We might better remove all the badges from the jbmc readme then.

**Comment by yumibagge** [comment]
> Good question. We might better remove all the badges from the jbmc readme then.

Shall I then adopt this PR to remove all badges from JBMC README.md?

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: a7f7d37648b2c55d1cfd9babc0da2a5664c7221a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119056250

**Review by owen-mc-diffblue — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
