### PR TITLE
remove symbol_typet [blocks: #4056]

### PR DESCRIPTION
**Pull request by kroening**
The type is not created anymore.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by smowton** [comment]
CI failures are genuine (residual uses in `cpp_typecheck_constructor.cpp` and Doxy references in README)

**Comment by tautschnig** [comment]
I have added two commits that fix remaining uses of `symbol_typet`. They are bug fixes, but we either don't have tests exercising those code paths or those code paths are actually unreachable. In the interest of moving on to the PRs that this one (transitively) blocks I hope it's acceptable to people that we don't actually spend time on adding tests for such code right now. (We should be doing CMake builds with coverage analysis enabled...)

**Review by tautschnig — APPROVED** [review]
Approving of the overall goal. Two of the commits are mine, so I shouldn't be the one to rely on for approvals anyway...

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 44858f246471bc928e1b096a74dea8295391649f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102589932
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by smowton — APPROVED** [review]

**Review by allredj — APPROVED** [review]

**Comment by allredj** [comment]
https://github.com/diffblue/test-gen/pull/3101 removes some stale references to `symbol_typet`. No need to wait for it though.

**Review by chrisr-diffblue — APPROVED** [review]

**Pull request merged**
