### PR TITLE
Replace requires with c_requires

### LINKED ISSUE #7656: Warning about requires keyword in C++20
With c++20 "requires" was added to the list of keywords (https://en.cppreference.com/w/cpp/keyword). This might lead to problems down the line when using g++20 as there is a function named `requires()` in `util/c_types.h`.

### PR DESCRIPTION
**Pull request by TGWDB**
Fixes #7656 

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by feliperodri — APPROVED** [review]

**Review by tautschnig — CHANGES_REQUESTED** [review]
While this will make the change slightly larger than strictly necessary: can we please have consistent naming for all code contract components? If we use `c_requires`, then we should also have `c_ensures`.

**Comment by remi-delmas-3000** [comment]
there's also assigns->c_assigns, frees->c_frees

**Review by feliperodri — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]
I would appreciate some squashing of commits.

**Comment by feliperodri** [comment]
@TGWDB there is a JBMC test failure (`218 - jbmc-CORE (Failed)`). Apart from it, it looks ready to merge.

**Pull request merged**
