### PR TITLE
Add zsh support to auto-complete

### PR DESCRIPTION
**Pull request by allredj**
This required the replacement of calls to `_filedir` in the script.

### CODE REVIEW

**Comment by smowton** [comment]
@allredj fraid I know nothing of `zsh`, know anyone that does?

**Comment by tautschnig** [comment]
I'll poke @karkhaz for input. Is there any chance this could be re-targeted to master together with the commit that previously introduced bash auto-completion?

**Comment by allredj** [comment]
@tautschnig Thanks! Yes sure I can set up a PR on master once this is reviewed.

**Comment by karkhaz** [comment]
@allredj thanks for this work!

Something isn't working on my end. If I type `cbmc --m<TAB>` then I get `cbmc --main-class` as expected. But then hitting `<TAB` again immediately afterward, zsh prints the following error:

    _cbmc_autocomplete:39: command not found: _filedir

it seems that the `_filedir` function in `cbmc.sh.template` is actually a bash builtin, and zsh doesn't use it even after loading `bashcompinit`. I wonder if this is just on my end (maybe something else in my .zshrc is making it break)?

**Comment by allredj** [comment]
Thanks @karkhaz. Indeed `_filedir` is part of a bash library and cannot be used by zsh. That is why I have replaced these calls in the script by calls to `compgen`. Most likely your script is not up to date. DId you run `extract-switches.sh`?

**Comment by karkhaz** [comment]
Yes, you're right. The branch had merge conflicts that I didn't notice. Thanks, this works---LGTM!

**Comment by allredj** [comment]
@karkhaz Thanks for your input!
@thk123 Could you be the senior developer for this one?

**Pull request merged**
