### PR TITLE
replace_symbolt with bindings

### PR DESCRIPTION
**Pull request by kroening**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
Thank you!! Would it make sense to explicitly document this behaviour in `replace_symbol.h`?

**Comment by tautschnig** [comment]
I believe the failing tests just document that we aren't really using bindings the way they are supposed to work, but instead introduce symbols for quantified expressions in the front-end.

**Comment by kroening** [comment]
The failures focus on the contracts code, which I don't think I can fix.

May I suggest merging the variant in #6807 to unblock.

**Comment by tautschnig** [comment]
> The failures focus on the contracts code, which I don't think I can fix.
> 
> May I suggest merging the variant in #6807 to unblock.

I'll create a patch for `add_quantified_variable` in the contracts code that will remove the use of `replace_symbol` in that context.

**Comment by tautschnig** [comment]
> I'll create a patch for `add_quantified_variable` in the contracts code that will remove the use of `replace_symbol` in that context.

Done in #6828.

**Comment by kroening** [comment]
> Done in #6828.

Many thanks -- note my comment there. It may be possible to simplify that code further.

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
