### PR TITLE
Remove redundant lines in ID_dynamic_object branch in value_set_dereferencet

### PR DESCRIPTION
**Pull request by owen-mc-diffblue**
This branch is not taken any more, at least in symex. The code in it
doesn't make much sense, which makes me think it isn't taken at all.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
This reminds me of f1ff824d00fb4d9994af7aedd7bd609f1ee98247 from #2646 (and #3769, where the actual merge of that work is being prepared). I don't feel sufficiently comfortable removing this at the moment (given the mess that f1ff824d00fb tries to clean up). It's probably ok to be removed, and it's perfectly possible that `ID_dynamic_object` expressions aren't generated at all. But I'm not really sure...

**Comment by tautschnig** [comment]
Actually the regression tests suggest that this isn't dead code at all:
```
rw_range_sett: address_of `dynamic_object' not handled
```

**Comment by owen-mc-diffblue** [comment]
Thanks for pointing that commit out to me, @tautschnig . I hope it can be merged soon, as it seems to fix some bugs in the slicer.

Indeed, this code does turn out to be used. I've updated my commit to just remove the lines from it that seem to have no effect at all. If that doesn't pass CI, or someone points out an effect that they have, then I will close this PR.

**Review by tautschnig — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d57e21bc8ba1313ed1b5707d31616d80a0350736).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102634292

**Review by smowton — APPROVED** [review]

**Pull request merged**
