### PR TITLE
Bugfix/overflow test

### PR DESCRIPTION
**Pull request by owen-jones-diffblue**
This fixes a test that isn't really doing anything.

### CODE REVIEW

**Comment by owen-jones-diffblue** [comment]
I have changed the commit message

**Comment by tautschnig** [comment]
@owen-jones-diffblue Would you mind rebasing to get a green light on all tests?

**Comment by owen-jones-diffblue** [comment]
Done

**Comment by kroening** [comment]
Do we know where that test came from?

**Comment by owen-jones-diffblue** [comment]
git blame points to commit 2e773cfc6d1a40fac6fc0854e8e2eed9760de304 by Michael Tautschnig. Here is the commit message:

**Comment by tautschnig** [comment]
Yes, more precisely this was: https://groups.google.com/d/msg/cprover-support/szOIuSPJ3s8/8BgoaEYbBwAJ

**Comment by tautschnig** [comment]
It may be worth noting that the change is in line with what the comment in the original file said:
```
Requires in[i] < 2^126
```

**Pull request merged**
