### PR TITLE
Skip unreachable instructions

### PR DESCRIPTION
**Pull request by peterschrammel**
Commit no. 8 from https://github.com/diffblue/cbmc/pull/363

### CODE REVIEW

**Comment by tautschnig** [comment]
@peterschrammel Since presumably you can't approve/disapprove of your own pull request, even though the commit is mine: do let me know your comments so that I can add them :)

**Comment by peterschrammel** [comment]
@tautschnig, please approve :)

**Comment by kroening** [comment]
@thk123 can you please add a test for this?

**Comment by tautschnig** [comment]
For what it's worth, the SV-COMP benchmark that got me to implement this had code of the following kind:
```
for(int i=0; i<12345678; ++i)
{
  int x=0;
  if(x>0)
  {
    (void)0; // necessarily unreachable
  }
}
```
I'm not sure how to assess (non-)regression in our current test framework for such cases, but at least test coverage of the newly introduced code would be recorded with a test such as the above.

Any thoughts on actually testing for regressions?

**Comment by martin-cs** [comment]
> Any thoughts on actually testing for regressions?

Put an assert(0) in the unreachable places (and make sure they are
inside of a loop), run the regression with --prune-unreachable-stuff
--unwind 0 and --unwinding-assertions.  If the prune removes it then it
should be UNSAT, if it doesn't will get SAT.

Should this functionality be part of goto-analyze, as in:

$ goto-analyze --simplify out.goto --domain-you-use-to-do-reachability

**Comment by peterschrammel** [comment]
@tautschnig, can you please dig up the example where this makes a difference?
Your example above does not show any difference w.r.t. current master.

**Comment by tautschnig** [comment]
My apologies, my example was missing some bit to make sure goto program conversion does not optimise out the loop body. With the following example:
```
int main()
{
  for(int i=0; i<10000; ++i)
  {
    int x=0;
    if(x>0)
    {
ERROR: (void)0; // necessarily unreachable
    }
  }
}
```
I see about 2 seconds time saving with the patch applied on my laptop.

The example from SV-COMP might have been https://github.com/sosy-lab/sv-benchmarks/blob/master/c/array-examples/standard_init1_true-unreach-call_ground.c - the pattern really should be `void __VERIFIER_assert(int cond) { if(!(cond)) { ERROR: __VERIFIER_error(); } }` - which also matches what a C library `assert` would expand to, i.e., `if(!(cond)) { some_body(); }`. For all cases where constant propagation can figure out that this branch is not going to be taken, the patch should help improve performance. Obviously that matters the most when this is happening inside a loop.

**Pull request merged**
