### PR TITLE
xml_expr binary fix

### PR DESCRIPTION
**Pull request by kroening**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
We do need a test.

**Review by smowton — APPROVED** [review]

**Comment by tautschnig** [comment]
> We do need a test.

@kroening  Maybe just extend the unit test (unit/goto-programs/xml_expr.cpp)?

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 8c687a9b8c7960d5023f723a9897a07089c82a52).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99265740

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 10f8089d4f0f1a545a04c630e53f0ac14abe7ab1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99500489

**Pull request merged**
