### PR TITLE
Remove unnecessary uses of ns.follow in util/

### PR DESCRIPTION
**Pull request by tautschnig**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by smowton** [comment]
Am I wrong then in thinking a typedef manifests as a symbol type?

**Comment by tautschnig** [comment]
typedef names are stored in `ID_C_typedef`, but looking at the failing CI run it seems I haven't considered what Java might be doing...

**Comment by kroening** [comment]
BTW, the need to use type_eq() should go away -- simply equality should work.

**Comment by tautschnig** [comment]
Thanks to the work by @kroening @smowton @thk123 in #3822 I do expect CI to now pass on this one. Reviews would be appreciated.

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d48e62b512475b4bb577de8b77c46ce6b266e1a8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98329813

**Pull request merged**
