### PR TITLE
[DOC-127]doc/cleanup-cprover-compilation-and-development

### PR DESCRIPTION
**Pull request by yumibagge**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by owen-mc-diffblue — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
I'm not sure why the Travis build has been cancelled? I have refrained from restarting it as presumably that was done intentionally. Either way, the CI failure is spurious, it just takes a restart or rebase.

**Comment by yumibagge** [comment]
I believe @owen-jones-diffblue cancelled CI so to not waste time on Travis ...

**Comment by owen-mc-diffblue** [comment]
Yes, I cancelled them, as this only changes documentation, and I thought there might be updates which would make it run again. It's worth having a passing run before we merge, not least so I can click the merge button, so I've restarted the cancelled jobs.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 01dd28c2b9d6cd78cc75e9303b86b3578f1fcc25).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/91218254
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Pull request merged**
