### PR TITLE
added a test for the precision of the value sets on unions

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by tautschnig — COMMENTED** [review]
Please include a comment on what is going wrong here right now.

**Review by tautschnig — APPROVED** [review]
I have added the comment I had asked for.

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 34187d8e97ee3a820a4522f0a981c53c449f856d).
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 9638dbb38c9ef244ae17ed54e42a6423628f67da).
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Pull request merged**
