### PR TITLE
Add Fotis and Thomas Spriggs to the codeowners for `/src/cbmc/`

### PR DESCRIPTION
**Pull request by NlightNFotis**
This folder contains files that manage the interface of the `cbmc` binary
(CLI option parsing, language init, etc).

Adding two long time CBMC contributors there should allow the
team to help contribute in reducing the review backlog for already
existing code owners, now and in the future, and also contribute in
maintaining a high code quality standard for that module going forward.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
Approving on the condition that you also fix the following warning raised by GitHub:
```
Unknown owner on line 74: make sure the team @diffblue/devops exists and has write access to the repository

/scripts/ @diffblue/devops
```

**Comment by NlightNFotis** [comment]
@tautschnig Very happy to do that - it was already in my plans, but planned to raise that as a separate PR.

I'm happy to add the commit here though.

**Review by TGWDB — APPROVED** [review]

**Comment by NlightNFotis** [comment]
@kroening @peterschrammel @chris-ryder Hi everyone.

I'm pinging you here to raise awareness for this PR - I won't merge this until it gets approval from every code owner (so that we know that people have seen this and are happy with the change, or that they are given a chance to raise any concerns)

**Comment by NlightNFotis** [comment]
@kroening @peterschrammel @chris-ryder Hello again.

May I ask one more time for a review of this PR adding code owners?

I understand that last time I wrote that this won't be merged without reviews, but if there appears to be no interest for a review of this, we will go ahead and merge it, and take corrective action later (in case of disagreements that may come after the merging of this).

**Pull request merged**
