### PR TITLE
[TG-1358] Correct handling of two byte offsets

### PR DESCRIPTION
**Pull request by thk123**
Found this while investigating #1795 as I think it is only wrong when the sign bit of the jump is 1 so needs to be a jump of at least 255. That said, I of course need to produce a simple repro and probably a unit test. 

Todo:

- tests :white_check_mark: 

I will write a unit test that more precisely checks this works.

### CODE REVIEW

**Review by smowton — APPROVED** [review]
Nice find!

**Comment by thk123** [comment]
Added test (note also fixed the `nop` statement not being converted into a `code_skipt` to make my test work)

**Review by peterschrammel — APPROVED** [review]

**Comment by tautschnig** [comment]
@thk123 Is there any reason _not_ to merge this?

**Comment by thk123** [comment]
Only my wanting to write a unit test that precisely checks the boundary conditions, which i am aiming to get to this week.

**Pull request merged**
