### PR TITLE
Test running framework

### PR DESCRIPTION
**Pull request by danpoe**
Framework to run given analysis passes on a given set of files (specified in an input file) and gather the results in a csv file. It can be used for e.g. running a number of CPROVER analyses on a set of goto binaries and collect all the results.

### CODE REVIEW

**Comment by hannes-steffenhagen-diffblue** [comment]
Can you write a slightly more detailed commit message, ideally a short description of what this is for?

Also, a lot of the python files don't export any functions/variables but still have the `if __name__ == '__main__':` line; this shouldn't be necessary if the module isn't intended to be used as a library.

**Comment by tautschnig** [comment]
How about using Benchexec?

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 138bfe1da8664ad7e4a1c7a41d622b0416022120).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79879714
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 9f7ef7f50fbe3f83eeb86ffc6d0fe81ab36f29ee).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79881219

**Pull request closed without merging**
