### PR TITLE
Tag another test that fails if you don't have z3 on your path

### PR DESCRIPTION
**Pull request by martin-cs**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by martin-cs** [comment]
@db-ci-cprover please could one of the CI images not have z3 on the path so that we can catch this kind of issue before it is merged?

**Review by SaswatPadhi — COMMENTED** [review]
The Makefiles in `regression/contracts` do not respect backend tags (see https://github.com/diffblue/cbmc/issues/5986#issuecomment-845529645), so I left this as TODO.

I don't think just adding the tags would leads to these tests being ignored; we also need to update the Make and CMake files.

**Comment by martin-cs** [comment]
At the moment you can't cleanly run the regression tests without z3.  I don't quite know why the CI doesn't flag this up.  Presumably there is some common set-up which includes adding z3?  I think we should either fix this or add z3 as a dependency.  My preference is fix.

**Comment by SaswatPadhi** [comment]
>  I think we should either fix this or add z3 as a dependency. My preference is fix.

+1. I think we should fix this.
1. The Make and CMake scripts should correctly enforce the tags
2. May be for one platform, say linux?, we could have two separate images: one with Z3 and one without Z3?

**Comment by martin-cs** [comment]
Sounds great.  I can try to do 1. but we will need @db-ci-cprover to do 2.

**Comment by TGWDB** [comment]
Note that #6213 has merged a CI job that specifically does some regression tests with `z3`.

**Comment by martin-cs** [comment]
Fixed by a different route.

**Pull request closed without merging**
