### PR TITLE
Clean up references to unused frontends

### PR DESCRIPTION
**Pull request by peterschrammel**
@kroening, are there users of SpecC and PHP? In which repositories are these frontends actually?

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
I believe those lived in an access-restricted part of the CVS tree, but alas I have never seen them and thus cannot comment on their status. Ok from my side, over to @kroening.

**Review by kroening — APPROVED** [review]

**Comment by kroening** [comment]
These are all languages that are on the decline; it's unlikely that we will resurrect any of them.

**Review by martin-cs — APPROVED** [review]
Am not opposed to this on my part.  If Daniel / whoever is in charge of hw-bmc is OK with the loss of SpecC and Diffblue are happy with the loss of PHP (I think it was on a road-map at one point?) then go for it.

**Review by chrisr-diffblue — APPROVED** [review]
I'm not in a position to assess the assertion that these front-ends are unlikely to be used, but from a pure code cleanup point of view, the changes look fine to me.

**Pull request merged**
