### PR TITLE
Silence warnings resulting from catch.hpp [blocks: #2310, #3425]

### PR DESCRIPTION
**Pull request by tautschnig**
This is factored out from #3425 in an attempt to get at least this bit approved and merged.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 606ffdfd29682e4fd55312a5bac35b1d78ab700d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98117729
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by kroening** [comment]
Would there be merit in upstreaming these changes to catch.hpp?

**Review by kroening — APPROVED** [review]

**Comment by thk123** [comment]
This will need a manual TG bump - will create.

**Comment by tautschnig** [comment]
> Would there be merit in upstreaming these changes to catch.hpp?

As in: fixing catch.hpp not to produce any warnings? Possibly so, but through the changes propose here we at least don't take any dependency on the proposals actually being picked up.

Half-related: I have a commit in the waiting to update catch.hpp to the most recent version, which will address the one local change we had made to catch.hpp earlier.

**Comment by tautschnig** [comment]
Thanks @thk123! Please just merge this PR when the corresponding TG change is ready.

**Comment by thk123** [comment]
@tautschnig done.

**Pull request merged**
