### PR TITLE
Do not handle float and double to string operations in the string solver

### PR DESCRIPTION
**Pull request by forejtv**
A follow-up from #4633, this PR is a shift towards handling more of the string operations in Java. All it does is to remove a couple of bindings from Java methods to string solver, so that the actual Java implementation is used.

There is an accompanying PR for java-models-library: https://github.com/diffblue/java-models-library/pull/23.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by thk123 — APPROVED** [review]
Less code is good if no tests start failing :)

**Review by martin-cs — APPROVED** [review]
Yeah... less axiom instantiation built in is generally a good thing.

**Comment by tautschnig** [comment]
@forejtv `cprover_string_concat_double_func` now needs to be removed from `irep_ids.def` as it is no longer used.

**Comment by forejtv** [comment]
This is now ready to go, I'll just wait for diffblue/java-models-library#23 to be approved so that we don't lose any existing functionality.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: af7bdaa1fca8063fe45e81e7d72ca6031cc9b7d5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/111782136

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
@forejtv I'll leave it to you to merge this so that you can make sure that the submodule pointer points to exactly the right commit.

**Pull request merged**
