### PR TITLE
Do not unnecessarily set ID_base_name

### PR DESCRIPTION
**Pull request by tautschnig**
The value was set, but never read.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by smowton** [comment]
@thk123 any usage in TG?

**Comment by tautschnig** [comment]
> @thk123 any usage in TG?

In case there is: `class_type.get_tag()` would yield the same value, and would thus be the change required if this were to be merged.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 93c0c65c908a7906f096f3dd9230827d862cbd64).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85561530

**Comment by thk123** [comment]
Nope - no usages of `ID_base_name` in TG :+1:

**Review by smowton — APPROVED** [review]

**Pull request merged**
