### PR TITLE
Float-point library implementation

### PR DESCRIPTION
**Pull request by tautschnig**
The collection of patches from #363 (with some squashes) mostly provided by Martin.

### CODE REVIEW

**Comment by tautschnig** [comment]
ansi-c/library/cprover.h is another file that doesn't really following coding conventions. Is it supposed to do so?

**Comment by martin-cs** [comment]
There are some more changes I'd like to make to this as various of these thing should become built-ins.  I'm hoping to get to this soon.

**Comment by tautschnig** [comment]
@martin-cs I'll dare assigning to you in this case.

**Comment by martin-cs** [comment]
Sure!

**Comment by tautschnig** [comment]
@martin-cs Any idea when you might get the chance to look into this?

**Comment by martin-cs** [comment]
On Thu, 2017-06-01 at 05:28 -0700, Michael Tautschnig wrote:
> @martin-cs Any idea when you might get the chance to look into this?

I am (privately) doing some work on this area so I hope soon.  Do you
have a particular deadline in mind?

**Comment by tautschnig** [comment]
> Do you have a particular deadline in mind?

I'd hope to get the sv-comp-2017 branch fully merged before the SV COMP'18 submission is due :-)

**Comment by martin-cs** [comment]
On Fri, 2017-06-09 at 03:28 -0700, Michael Tautschnig wrote:
> > Do you have a particular deadline in mind?
> 
> I'd hope to get the sv-comp-2017 branch fully merged before the SV COMP'18 submission is due :-)

Fair.  Date? :-)

**Comment by tautschnig** [comment]
Some time around September, I'd say. (But do note that this PR is not the only one left, I've got others factored out from #363 awaiting review/merge and a few others not even factored out yet - so the task is actually mostly on my plate.)

**Pull request merged**
