### PR TITLE
 JBMC: add property checks on a per-function basis

### PR DESCRIPTION
**Pull request by smowton**
A trivial switch from a whole-program to a per-function pass. Depends on #1738; only review the latest commit.

### CODE REVIEW

**Review by peterschrammel — COMMENTED** [review]
There are failing tests

**Comment by smowton** [comment]
@peterschrammel fixed

**Comment by smowton** [comment]
@peterschrammel @tautschnig similarly, Travis failure only on OSX for capacity reasons, please re-review.

**Comment by smowton** [comment]
Subsumed by #1740

**Pull request closed without merging**
