### PR TITLE
Use code_typet::parameters

### PR DESCRIPTION
**Pull request by tautschnig**
Avoid direct use of the implementation detail that parameters are stored under
the ID_parameters key.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 182fd111bf05a0c6a409ff22761790755071dd03).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93274263
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
Hmm, a TG failure here is unexpected. @allredj @peterschrammel @thk123 is some part of the infrastructure flakey?

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0b347132c3e17a3402982595818a1a523aeb370b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93278324

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 24d6df88d04747d01f29dd00f2221dd8af3cac2a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93296163

**Pull request merged**
