### PR TITLE
Small cleanup to remove use of assert() 

### PR DESCRIPTION
**Pull request by chrisr-diffblue**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 35df0b29c1f96f733ee31c18545b600470960095).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84834216

**Review by kroening — APPROVED** [review]

**Comment by kroening** [comment]
I suggest squashing the two commits.

**Comment by chrisr-diffblue** [comment]
Commits squashed, will merge once CI completes.

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: de0f7d2bfa1a9d13a0c700e21224c8e7ef536922).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85043987

**Pull request merged**
