### PR TITLE
Replace get_mutable by goto_programt API function

### PR DESCRIPTION
**Pull request by tautschnig**
Hacking a const iterator into a non-const one should be available at global scope instead of unwind-local.

### CODE REVIEW

**Comment by tautschnig** [comment]
@danpoe Could you please take a look at this one?

**Comment by danpoe** [comment]
I agree that it isn't good practice in general to retrieve an ``iterator`` from a ``const_iterator``.

In this particular case I think it's beneficial though:
- The function ``unwind()`` also has a non-const goto program as a parameter. Thus even with a ``const_iterator`` parameter the user cannot wrongly infer that the function does not change the goto program.
- The reason for using a ``const_iterator`` was that the function keeps a bunch of iterators to the same goto program, and previously there were several bugs where I accidentally modified the goto program through the wrong iterator. Having a ``const_iterator`` and obtaining an ``iterator`` when needed allows the compiler to catch some of those bugs.

If that sounds reasonable to you I'd like to keep the current version of the code.

**Comment by tautschnig** [comment]
I certainly agree that there is no surprise in that the program is being modified. Actually I spent some time trying to get rid of the non-const requirements for your code, and maybe I should just give that another go. There is a lot of code that shouldn't even be using non-const iterators.

May I leave this one open, though I'll re-title it RFC? I'll work on #364 to get a newer STL version installed.

**Comment by danpoe** [comment]
Sounds good. I agree, there's many places in the codebase where we could use ``const_iterators`` if the C++11 versions of functions like ``splice()``, etc. would be available.

**Comment by tautschnig** [comment]
Do we have confirmation that various versions of Visual Studio support those C++11 features? Given that 4.8 is the default compiler on Ubuntu 12.04 (which doesn't have it's EOL until April 2017) I'm wondering whether it is a good idea to go this far just yet? (Though COMPILING does say that GCC 4.9 or later is required...)

**Comment by tautschnig** [comment]
@danpoe: While I will be pushing the promised larger-scale work into the ranged-for PR (#333) as it has some major prerequisites, I've now just migrated your code into goto_program_template.h to ensure that it's not just the unwind code that can make use of such ideas. Travis updates are coming in #364 (currently testing/debugging).

**Comment by danpoe** [comment]
Looks good. Regarding Visual Studio, version 2015 (= v14.0) with cl.exe v19.00 does support those C++11 features but I don't know about the earlier 2013 version mentioned in COMPILING.

**Pull request merged**
