### PR TITLE
expr2c: Remove precedence parameter where unused [blocks: #2310]

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: a6c039ecb087c9de7eb08e4b4d4803ea7d316865).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77248977
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Comment by peterschrammel** [comment]
Rebased.

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: db2c7b7b8e2fdbff3d123cee559c419ba5b5d312).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78360124

**Review by peterschrammel — APPROVED** [review]
TG passes.

**Comment by peterschrammel** [comment]
@kroening, your review is required here.

**Comment by tautschnig** [comment]
@kroening ping?

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: b2e1eb939e24f07421033ca6aa22cbf12f687145).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87006179

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 34c156d84c9add1a1b7289cee88bc5ec982eec9e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/89862286

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 8c49bfac3627abc7fde2a8367825f98147f32bfc).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90848848

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3c8df0213dca9fdcdd32b9173ceb4ae26d14ffb0).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/91345742

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: b1f702a406c146483c0c5f2d0f8864bbdd6cdd3c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95252375

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: da9b374b653a84fcd5e35012007b3047bb97d993).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98026909

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3f6ff2eec86cf06cbfb26e7acc3b279a2e07feb8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102428172

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 9087c9e2ba93d7a6759f2d2301321823999125d6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103068724
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 75de8e371706fa78afa1106ee7c6efba40769f79).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/104499899
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 95ea6540262c5a0b43f789aab256a46f8c0a2f76).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/108801741
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by kroening — APPROVED** [review]

**Pull request merged**
