### PR TITLE
Cleanup error handling elf reader

### PR DESCRIPTION
**Pull request by chrisr-diffblue**

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: bd5d2f6337e56886918475312b40d9c79f38db94).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84832352

**Review by peterschrammel — APPROVED** [review]

**Review by kroening — CHANGES_REQUESTED** [review]
I am concerned that there will be a long list of different exceptions that are to be caught in the driver programs (and sometimes forgotten to be caught).

Furthermore, there are a lot of similar exception classes, basically containing a string with an error message.

These could be summarised in some base exception class, and then caught by catching the base class.

**Comment by tautschnig** [comment]
> These could be summarised in some base exception class, and then caught by catching the base class.

Can this be resolved by making `deserialization_exceptiont` inherit from some `invalid_input_exceptiont`?

**Comment by chrisr-diffblue** [comment]
@kroening - This PR has now been rebased which picks up #2996 (which has been merged into develop). I think that PR addresses your concern around the proliferation of exception classes and handlers for them. Would you mind taking another look at this PR?

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: f17ae975a29a2f6b42298964fb170bdf8efbb146).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85433227

**Comment by chrisr-diffblue** [comment]
@kroening Would you be able to re-review this PR to see if your blocking comment is still applicable or not? I think it's been addressed now.

**Review by kroening — APPROVED** [review]

**Pull request merged**
