### PR TITLE
Replace objectt with optional<mp_integer>

### PR DESCRIPTION
**Pull request by owen-mc-diffblue**
typedef optional<mp_integer> to offsett and use that instead of objectt.

### CODE REVIEW

**Comment by owen-mc-diffblue** [comment]
Please review @smowton and @tautschnig.

I am happy to do the same refactoring on the other versions (fi, fivr, fivrns) in this PR, once the approach is agreed.

**Comment by owen-mc-diffblue** [comment]
@peterschrammel could also review it.

**Review by tautschnig — APPROVED** [review]
Looks good to me. Indeed the other variants should be adapted in the same way. I do hope that, if anything, performance improves via those changes, but I have not done any evaluation (yet).

**Review by smowton — APPROVED** [review]

**Comment by smowton** [comment]
Consider providing `offset_is_zero` as a helper function, defined as `offset & !*offset`, since that's still a pretty confusing line of code to see without explanation.

**Comment by owen-mc-diffblue** [comment]
@smowton I don't actually see that code in the PR, or any code where that helper function would be useful. In one place it checks if an `offsett` is set, and also if a `mp_integer` representing an offset is non-zero (https://github.com/diffblue/cbmc/pull/1629/files#diff-0b14b3f17ac4ea221562800625976901R1010) and in another it checks if an `offsett` is set and whether it's equal to an `mp_integer` (https://github.com/diffblue/cbmc/pull/1629/files#diff-0b14b3f17ac4ea221562800625976901R90). I'm not sure either of these are candidates for helper functions.

**Comment by smowton** [comment]
Huh, I'd assumed that function would actually be used somewhere! In that case I guess don't bother.

**Comment by owen-mc-diffblue** [comment]
I see, it's used in some of the variants, e.g. value_set_fi.cpp. I'll make a helper function in those cases.

**Comment by martin-cs** [comment]
Probably pedantry but : why?  The commit message just describes what you are doing but not why you are doing it.  This can be useful in N months time when someone asks "why did we change that?".

**Comment by owen-mc-diffblue** [comment]
Good point. I'll update the commit message. The main reason is to remove the name `objectt`, which I've always found very unintuitive. It also removes code by using `optional` rather than rolling our own class to do the same thing.

**Comment by owen-mc-diffblue** [comment]
I've added commits for the other three variants. I updated the first commit to include the helper function `offset_is_zero()`, even though it isn't used, for consistency with the others. I've also formatted the commits with clang-format.

**Comment by tautschnig** [comment]
@owen-jones-diffblue As I merged your #1640 this one now requires a rebase I'm afraid.

**Comment by owen-mc-diffblue** [comment]
@tautschnig I have rebased and all checks have passed

**Pull request merged**
