### PR TITLE
Remove deprecated windows package building scripts.

### PR DESCRIPTION
**Pull request by NlightNFotis**
The scripts removed are from an early attempt to build
and package a CBMC distribution on windows, that has
now been deprecated since we delegate to CMake (CPack)
to build a windows installer.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by hannes-steffenhagen-diffblue — APPROVED** [review]

**Review by thomasspriggs — APPROVED** [review]
Should the `.github/workflows/debian` and `.github/workflows/macos15` directories go as well?

**Review by martin-cs — APPROVED** [review]
Seems reasonable but it would be good to have someone who is a windows user comment on this.  Were these scripts used for anything else apart from CI?

**Comment by NlightNFotis** [comment]
@martin-cs We have talked (offline) to the original contributor of these scripts, and unless I'm badly mistaken he agreed to us removing them.

Yes, also these scripts where only used on CI - we now have them substituted with the ones in `.github/workflows/release-packages.yaml`.

**Comment by NlightNFotis** [comment]
@thomasspriggs Maybe, but as a part of another PR 👍

**Comment by martin-cs** [comment]
@NlightNFotis Great!  Thanks.

**Comment by NlightNFotis** [comment]
Also, ignore the codecov project, the report seems to be spurious - this PR doesn't add or remove coverage - it's only removing CI config files.

**Pull request merged**
