### PR TITLE
move version.h to util/

### PR DESCRIPTION
**Pull request by kroening**
This speeds up 'make' on my laptop from 3.0s to 0.6s.
It is unclear whether the same can be done with cmake.

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
Several binaries require that version.h file to exist. One option that might help is to have some version.mk file that is selectively included from those directories that require it.

**Comment by smowton** [comment]
@tautschnig the version file is the same for each program that uses it, right? If so should we simply make it out of the `util` package?

**Comment by tautschnig** [comment]
Yes, the file is the same for anything built out of this source tree. My concern is the cross-directory build rule that `util/version.h` would require - or at least it seems to me that it would. Maybe all that we need is that the `all` target in `util` generates `version.h`.

**Comment by kroening** [comment]
Ok, let's go for util/version.h, made by all

**Review by tautschnig — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: b96c7ba85781e7ca732aeb05eb940b7bb05ee2a1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77996025

**Review by smowton — APPROVED** [review]
Confirmed this does as advertised in CMake world

**Pull request merged**
