### PR TITLE
Set string-max-length in indexOf test

### PR DESCRIPTION
**Pull request by romainbrenguier**
Without this, the solver sometimes ends up with a difficult instance for minisat.

### CODE REVIEW

**Comment by tautschnig** [comment]
I'm worried about "sometimes" - we use deterministic SAT solvers, thus the situation ought to be very stable? Also, when is it the case and when is it not the case (based on your observations)?

**Comment by romainbrenguier** [comment]
@tautschnig 
> I'm worried about "sometimes" - we use deterministic SAT solvers, thus the situation ought to be very stable? Also, when is it the case and when is it not the case (based on your observations)?

It depends on the build, in general the build on travis and appVeyor get different counter-examples from the SAT-solver (not sure this is because of minisat or because the input we give it is slightly different).
This can also vary from one commit to the other on the same system (even if the changes seem unrelated to the solvers).

**Comment by tautschnig** [comment]
Thanks a lot for the input. Would you mind putting those observations in the commit message? I'd classify them as matters of the input encoding: yes, a different formula (possibly only small differences) will result in varying behaviour, and surely there are differences whether running on Windows or Linux, for example. What I'd claim is that running the same benchmark on the same operating system with the same version of CBMC/JBMC will yield the same behaviour; your observations seem to be in line with that as the different behaviour has variations on at least one of those dimensions.

**Comment by romainbrenguier** [comment]
@tautschnig I updated the commit message

> What I'd claim is that running the same benchmark on the same operating system with the same version of CBMC/JBMC will yield the same behaviour; your observations seem to be in line with that as the different behaviour has variations on at least one of those dimensions.

Yes, from what I observed, successive runs of the same build (or builds from the same commit) always behaved the same.

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
