### PR TITLE
Check for memory leaks on exit and abort

### PR DESCRIPTION
**Pull request by peterschrammel**
This has become relevant in the SV-COMP MemCleanup category.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
Looks good as far as I can tell, but is failing CI.

**Comment by kroening** [comment]
There's SV-COMP and there's the real world. In the real-world, memory leaks at exit() don't matter, and most engineers won't fix.
If we need exit() memory leaks, I would have a separate categories for these.

**Comment by peterschrammel** [comment]
We could do a classification similar to Valgrind: http://valgrind.org/docs/manual/faq.html#faq.deflost
E.g. distinguishing 'definitely lost' and 'still reachable' would make sense.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 507d221ff43e4c26d98f9dc6b3d772193fdc4757).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92469216

**Comment by NlightNFotis** [comment]
Hi @peterschrammel, how should we proceed with this? It looks valuable but looks like it's going to need some work.

**Comment by peterschrammel** [comment]
This is part of the SV-COMP patchset and needs more work before it can go into `develop`. Please keep it open.

**Pull request merged**
