### PR TITLE
smt2: fix float conversions

### PR DESCRIPTION
**Pull request by kroening**
This needs both #3654 and #3655.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: bea03450b2e6e135b61ad24b61b6c5d71910f3d1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96021611

**Review by tautschnig — COMMENTED** [review]
Missing tests and commit messages?

**Comment by kroening** [comment]
@tautschnig I am still not entirely comfortable with stacks of PRs; thus, will add once #3654 is in.

**Comment by tautschnig** [comment]
> I am still not entirely comfortable with stacks of PRs; thus, will add once #3654 is in.
 
#3654 has now been merged :-)

**Comment by TGWDB** [comment]
Closing this PR as no longer being worked on. Also linking to #6134 since the work here may be of interest there.

If you believe this is erroneous, please reopen and note why.

**Pull request closed without merging**
