### PR TITLE
Minor cleanup of some SMT2 files

### PR DESCRIPTION
**Pull request by SaswatPadhi**
This is a minor cleanup PR.

There were 3 SMT2 files that were:
1. being rejected by CVC4 without the `--incremental` cmdline flag
2. leading to errors in Z3 because `ALL_SUPPORTED` logic was not understood

In this PR, I:
1. added `incremental` option in the SMT2 files, which is required for using `push` and `pop` commands in CVC4.
2. replaced `ALL_SUPPORTED` logic (which is CVC4-specific) with `ALL` (which is part of the SMTLIB 2.5+ standard).

The updated SMT2 files have been tested with both solvers and they emit no warnings or errors.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- NA ~~Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.~~
- NA ~~The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/~~
- NA ~~Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).~~
- NA ~~My commit message includes data points confirming performance improvements (if claimed).~~
- [x] My PR is restricted to a single feature or bugfix.
- NA ~~White-space or formatting changes outside the feature-related changed lines are in commits of their own.~~

### CODE REVIEW

**Review by martin-cs — COMMENTED** [review]
The `incremental` part; definitely.  The `set-logic`, well ... neither are actually standard nor the minimal logic in question so... unsure?

**Comment by SaswatPadhi** [comment]
But this doc [<http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.5-r2015-06-28.pdf>] says (on page 11) that `ALL` is now  a standard logic since SMTLIB 2.5:

> There is now a predefined argument, `ALL`, for the `set-logic` command which refers to the most general logic supported by the solver executing the command.

**Review by martin-cs — APPROVED** [review]
Thanks @SaswatPadhi I had missed it's addition to SMT-LIB 2.5.  I'd prefer that the logics were minimal but `ALL` is definitely better than `ALL_SUPPORTED`.

**Comment by SaswatPadhi** [comment]
Thanks for approving the changes @martin-cs.

I tried restricting the logic -- these files work with the `BVS` logic in CVC4, but Z3 doesn't recognize `BVS` and rejects these files.

**Pull request merged**
