### PR TITLE
Use improved reporting for equality-without-matching-types

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Comment by martin-cs** [comment]
I remember this being a problem and I remember someone saying "we should do something about this" but I don't recall the root cause.

I don't really object to the code but I am concerned about what this says about the invariants and what is a correctly structured expression.  I am under the impression that all exprts should be correctly typed and thus if anything (including symex) creates an equality of a mixed type, then it is wrong and we can't trust anything that happens after.  This patch would seem to suggest otherwise...

Can you explain a bit about why this is desireable?

**Comment by tautschnig** [comment]
This is really just a crutch. The fix is, as you say, to properly check for type consistency during symbolic execution and never feed inconsistent expressions to the back-end. Indeed I'd rather see us revert any of the work that has introduced elaborate exception handling, and I'd rather see this sooner than later...

**Comment by peterschrammel** [comment]
As said elsewhere, all 'catch'es that do not provide operational recovery should be removed. All catch&exit logic should be moved to parse_optionst::main().

**Review by peterschrammel — APPROVED** [review]

**Comment by martin-cs** [comment]
@tautschnig if this is a crutch and in light of what @peterschrammel has said about recovery -- do we need this?  Really isn't this an invariant?

**Comment by tautschnig** [comment]
@martin-cs It really depends on when #1880 gets resolved. I've done the small bit of work for this PR because once again I had run into the problem and thus needed a debugging tool. Should I have spent time towards resolving #1880? Possibly...

**Comment by tautschnig** [comment]
I'm actually merging this now, a revert should be fairly cheap. Fully agreed that this should be an invariant, but at the point where it currently fires there isn't sufficient diagnostic information as the problem is _not_ currently tested for/caught earlier. #1880 will eventually come to the rescue.

**Pull request merged**
