### PR TITLE
Partial expression simplification

### PR DESCRIPTION
**Pull request by thk123**
Depends on variable sensitivity domain: #708 
Fixes part of diffblue/cbmc-toyota#132

When calling `ai_simplify`, previously if we couldn't simplify the whole expression we gave up. Now we 
recurse over the sub-elements to get a partially simplified expression. E.g. if we have an array whose value is top, but the index `i` is known to be 1 then `arr[i]` will simplify to:

```C
arr[1]
```

Real diff: https://github.com/diffblue/cbmc/pull/1020/commits/de2f979940b311be8ca4c419529054c6adf5d113

### CODE REVIEW

**Comment by martin-cs** [comment]
Looks good to me.  The only nit is to make sure to update the call to ai_simplify to the new signature.

**Comment by martin-cs** [comment]
Let's see if the merge issues go away once the rebase is done.  Other than that I am happy with this change.

**Comment by hannes-steffenhagen-diffblue** [comment]
Closing as it's unlike @thk123 is going to pick this up again. Also I believe a version of this was eventually implemented regardless.

**Comment by martin-cs** [comment]
Just to close the loop, VSD did get merged and @jezhiggins is currently working on this bit of code, hopefully for a final version.

**Pull request closed without merging**
