### PR TITLE
Move and cleanup declarations of C compiler intrinsics

### PR DESCRIPTION
**Pull request by tautschnig**
Please review commit-by-commit: the main added value is a new script that fetches Clang's declarations. The remaining commits are cleanup to facilitate easier updates of these intrinsics in future.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by NlightNFotis — COMMENTED** [review]
Sorry, question here because I cannot put it into a comment on the code (doesn't seem appropriate).

This appears to be adding a python script to print the compiler intrinsics from clang. It also mentions (on one of the commit messages) that this is supposed to substitute for an older script, but I don't see the older one being deleted anywhere.

Is this a mistake, or are both supposed to be used? Or is my understanding of the situation wrong?

**Comment by tautschnig** [comment]
> Sorry, question here because I cannot put it into a comment on the code (doesn't seem appropriate).
> 
> This appears to be adding a python script to print the compiler intrinsics from clang. It also mentions (on one of the commit messages) that this is supposed to substitute for an older script, but I don't see the older one being deleted anywhere.
> 
> Is this a mistake, or are both supposed to be used? Or is my understanding of the situation wrong?

My apologies, I'll try to clarify the commit message: it's not really a substitute as the existing (bash) script fetches declarations from GCC's repository, while the new Python script fetches Clang's declarations. These declarations overlap to a great extent, but aren't completely the same. That said, however, the GCC script is rather brittle. Perhaps removing that script actually is the right thing to do. For now I'll just amend the commit message, but we might consider removing the bash script.

**Review by TGWDB — APPROVED** [review]
I'm approving with the following caveats:

1. Adding a new script seems philosophically dangerous, now we have multiple places to gather the data we need
2. I don't think any of this is (well?) tested...
3. While it looks ok to me, I'm not really an expect in the compiler intrinsics area

**Comment by tautschnig** [comment]
> I'm approving with the following caveats:
> 
>     1. Adding a new script seems philosophically dangerous, now we have multiple places to gather the data we need
> 
>     2. I don't think any of this is (well?) tested...
> 
>     3. While it looks ok to me, I'm not really an expect in the compiler intrinsics area

Points taken. Maybe we can one day try to come up with a better story for compiler intrinsics. At the moment, this certainly is just a best-effort and not very organised activity.

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
