### PR TITLE
Use dstringt::starts_with

### PR DESCRIPTION
**Pull request by kroening**
- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
This will break `-DUSE_STD_STRING` until we switch to c++20. Perhaps we should just document that `USE_STD_STRING` requires switching to that newer standard?

**Comment by kroening** [comment]
> This will break `-DUSE_STD_STRING` until we switch to c++20. Perhaps we should just document that `USE_STD_STRING` requires switching to that newer standard?

I'd like to propose to get rid of it.

**Comment by tautschnig** [comment]
> > This will break `-DUSE_STD_STRING` until we switch to c++20. Perhaps we should just document that `USE_STD_STRING` requires switching to that newer standard?
> 
> I'd like to propose to get rid of it.

https://github.com/diffblue/cbmc/pull/8154, which I'd propose to merge first, and then rebase this one on top.

**Review by martin-cs — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]
With #8154 merged this one should be good to go after a rebase.

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
