### PR TITLE
Set BUILD_ENV via make variable instead of patching via sed

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Comment by chrisr-diffblue** [comment]
Is setting `BUILD_ENV` even needed here? If I'm reading `src/config.inc` and `src/common` properly, then by default `BUILD_ENV` should be set to MSVC anyway (assuming that `uname` returns something that `src/common` recognises...)

I confess that I don't know what `uname` returns for a Win64 system so it may be some additional patching is required to `src/common`

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: e00c6ee8bf109be28fc02ac294b8153393184e99).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/76947100

**Comment by kroening** [comment]
On Windows, there is a choice of two build systems: You can build with a MingW g++, or with Visual Studio. AUTO selects the MingW path right now, but practically we deliver binaries built with Visual Studio.

Perhaps the default should simply change to Visual Studio.

**Comment by tautschnig** [comment]
> Perhaps the default should simply change to Visual Studio.

As far as I am aware there still is a customer using MinGW? I'd say this switch is something we could do for a 6.0 release, but we need to take note of it in the release notes. Also, I'd rather do this in a separate pull request. This PR really just changes our CI scripts, it has no customer impact.

**Comment by chrisr-diffblue** [comment]
Re customers using WinGW - yes, there are customers out there using it (I've just returned from visiting one of them...)

**Review by chrisr-diffblue — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Pull request merged**
