### PR TITLE
Java frontend cleanup

### PR DESCRIPTION
**Pull request by kroening**
Cleanup with the goal of simplifying interfaces.

### CODE REVIEW

**Comment by smowton** [comment]
So this just removes the classloader limit feature?

**Comment by kroening** [comment]
More coming!

**Comment by smowton** [comment]
OK please assign me (cf. request review) when ready

**Comment by NlightNFotis** [comment]
I am closing this PR as it appears to be in a very stale state compared to the branch it aims to merge to.

If you feel like this has been in err, feel free to reopen the PR, rebase on current `develop`, and continue the effort to get it merged

**Pull request closed without merging**
