### PR TITLE
[TG-9219] Add new option --ignore-manifest-main-class

### PR DESCRIPTION
**Pull request by antlechner**
If the option is specified, any main class that may be specified in the manifest file of a JAR will be ignored in the class loading stage.
This is useful when we want to e.g. load all classes in a JAR file, some of which may not be referenced from the specified main class.

- [x] Each commit message has a non-empty body, explaining why the change was made. (except for regression test commit)
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Review by romainbrenguier — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f3c9735a4fe2df21a34ae85c4003d2a4d1f561ec).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125212217

**Comment by antlechner** [comment]
I generalised the regression test as requested by @segun3d, to use two different packages in the jar file.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: cbe9391c6c9012cc3ea523a57d2219230ca91e41).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125261944

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: a49fd3d842fb9f233385e76b3df16e3e66447900).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125275386

**Comment by peterschrammel** [comment]
@antlechner, the failing regression test should be fixed by rebasing.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 974f6a0cd9d73dc5f230d3c7a3e7de9ccbefe7f5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125499169

**Comment by antlechner** [comment]
More tests added as requested by @segun3d (one with --main-class, one with --function, one with both, and one without --ignore...).

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 7fabc9d69efa443d1f93564032477f4508555295).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125790120

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 54ee1a97078041a7b9e16f4e480be98767608b8a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/125924156
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by yumibagge — APPROVED** [review]
QA review [Passed]

https://diffblue.atlassian.net/browse/TG-9219?focusedCommentId=24275&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24275

Added regression tests looks well covered. Many thanks :slightly_smiling_face:

**Pull request merged**
