### PR TITLE
Mark CBMC version 5.62.0

### PR DESCRIPTION
**Pull request by NlightNFotis**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
Can you please hold back as I'd like to have a regression fix included that I'm about to PR.

**Comment by tautschnig** [comment]
> Can you please hold back as I'd like to have a regression fix included that I'm about to PR.

That PR is #7020.

**Comment by NlightNFotis** [comment]
@tautschnig, Yep, happy to wait - feel free to unblock this when you're ready.

**Review by tautschnig — APPROVED** [review]
#7020 is now merged, if you could please rebase then I'd be happy for this release to proceed.

**Comment by thomasspriggs** [comment]
> #7020 is now merged, if you could please rebase then I'd be happy for this release to proceed.

I don't think we even need to rebase. If I remember correctly we normally tag the merge commit as the release, which will include any other changes merged to develop.

**Review by thomasspriggs — APPROVED** [review]

**Comment by NlightNFotis** [comment]
Yeah, I don't think we need to rebase (as there are no conflicts in the files edited), but I have issued a re-run of the failed jobs (given that they are required).

**Pull request merged**
