### PR TITLE
Silence spurious/information-only Visual Studio warnings [blocks: #2310]

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Comment by smowton** [comment]
If you're going to disable this everywhere why not just disable the warning globally with a command-line switch?

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 40e39280aad4212ca554624cd745b11f26bd9568).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78358511

**Comment by tautschnig** [comment]
> If you're going to disable this everywhere why not just disable the warning globally with a command-line switch?

We could also go that route, but disabling the warnings where issued has the following advantages I'd say:
1) It makes very explicit where a compiler is raising warnings.
2) Compilers usually have a good reason to warn, and each warning raised should make you think twice about a particular bit of code.

**Comment by smowton** [comment]
In general I agree, but these aren't warnings, like you say they're information flagging up a behaviour change since an obsolete version of the compiler (VC++7.1 was released in 2003).

**Review by peterschrammel — APPROVED** [review]
Hopefully, we can soon revert this commit by eliminating these catch-all from the code base.

**Review by martin-cs — COMMENTED** [review]
You I'm listed as a code owner for this but as I don't have a windows machine and haven't used one in years ... I'm a little bit stumped.  The added code is kinda ugly and I don't see how this can be maintained / sustained / checked for.  Does the recent change to which VS versions we support obsolete this?

**Comment by tautschnig** [comment]
I'll add this to my list of "warning-fixes to be re-evaluated" once the other fixes have been merged.

**Comment by tautschnig** [comment]
Closing as the Visual-Studio-7.1-related warning is now globally disabled in #2310.

**Pull request closed without merging**
