### PR TITLE
Move Travis jobs using clang 6.0 to clang 7

### PR DESCRIPTION
**Pull request by tautschnig**
More recent versions of Clang provide additional warnings that we may benefit
from when run in CI.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by kroening — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f51a3d4496055e67f0b61f3aabf604581a032a7a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/89532192

**Comment by thk123** [comment]
Will make a bump moving TG to the same version of clang (and a reminder that I never got my move to clang-6 merge!)

**Comment by tautschnig** [comment]
@thk123 Clang-6: #2876?

**Comment by tautschnig** [comment]
@peterschrammel @thk123 @forejtv Could you please take a look at this one? #3301 should really not be happening.

**Review by thk123 — APPROVED** [review]
I haven't yet got my TG clang-6 to work yet, but that isn't really a reason not to move to 7 here anyway.

**Pull request merged**
