### PR TITLE
Scripted parallel property checking using CBMC

### PR DESCRIPTION
**Pull request by tautschnig**
Adds a (Python) script to check all properties contained in a given GOTO
binary individually, but in parallel. This can yield a somewhat
different user experience in that some of the results become available
early on while other properties are still being checked for, as opposed
to the all-or-nothing experience when doing all properties at once.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by NlightNFotis** [comment]
Can we get a bit of documentation on this? Like, what is it and how do I use it?

I'm asking because the `scripts/` folder has ended up with a great number of things that are only useful to their authors, so maybe it's a good idea to start requiring docs so that they become more widely useful.

**Comment by jimgrundy** [comment]
Agree with fotis. At the very least can we get a descriptive header comment in the file explaining what it is an how to use it.

**Comment by tautschnig** [comment]
@NlightNFotis @jimgrundy I have now added documentation at the top of the file, and am also including this in the `--help` output. All feedback on how to improve this documentation would be appreciated!

**Review by NlightNFotis — APPROVED** [review]
Thank you. That already looks great!

On a separate note, the functionality this implements looks like a great fit for internal functionality. Is this a stand-in for that, or do we plan to rely on this script to provide this functionality?

**Comment by tautschnig** [comment]
> On a separate note, the functionality this implements looks like a great fit for internal functionality. Is this a stand-in for that, or do we plan to rely on this script to provide this functionality?

Building that into the tool (and thereby reducing the overhead) is on the agenda :-)

**Pull request merged**
