### PR TITLE
Split goto_check

### PR DESCRIPTION
**Pull request by kroening**
goto_check inserts assertions that check for suspect bugs in both C/C++ and
Java programs.  The criteria differ vastly given that Java has basically no
instances of undefined behavior.

This PR splits the file, separating it into a checker for C/C++ and one
for Java.  The long-term plan is to move these checkers into the directory
of the corresponding language frontend.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- n/a My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
I'm fine with that, but I note that we have several other PRs in flight that also affect this code. We need to co-ordinate at least with:
- #6491
- #6471 
- #6416 
- #6399

**Review by peterschrammel — APPROVED** [review]
Looks like a reasonable intermediate step.

**Comment by kroening** [comment]
> I'm fine with that, but I note that we have several other PRs in flight that also affect this code. We need to co-ordinate at least with:
> 
> * #6491
> * #6471
> * #6416
> * #6399

These all affect the checks for C, and should rebase easily since this PR renames goto_check.cpp to goto_check_c.cpp.

**Comment by tautschnig** [comment]
> These all affect the checks for C, and should rebase easily since this PR renames goto_check.cpp to goto_check_c.cpp.

I'll try that on mine, but the mix of file renaming and clang-formatting could still spell trouble.

**Comment by tautschnig** [comment]
> > These all affect the checks for C, and should rebase easily since this PR renames goto_check.cpp to goto_check_c.cpp.
> 
> I'll try that on mine, but the mix of file renaming and clang-formatting could still spell trouble.

Add the renaming of the class into the mix. So, no, unfortunately it's not exactly fun. I've taken care of #6491, and will work with @remi-delmas-3000 on #6471.

**Pull request merged**
