### PR TITLE
Install symtab2gb and add it to CPack installers

### PR DESCRIPTION
**Pull request by hannes-steffenhagen-diffblue**
It was previously omitted from the list of installed targets by accident.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]
Please add "Fixes: #5623" to the commit message.

**Review by martin-cs — APPROVED** [review]
Yes, please!

**Review by NlightNFotis — APPROVED** [review]
Nice.

**Review by thomasspriggs — APPROVED** [review]
I have checked locally that this builds the package ok on my Ubuntu machine and that the generated packaged contains the `symtab2gb` binary.

**Pull request merged**
