### PR TITLE
Add basic jsr / ret implementation. Fixes #280

### LINKED ISSUE #280: Java front-end: jsr / ret support is missing
Specifically seen in `edu/emory/mathcs/backport/java/util/concurrent/ConcurrentHashMap.class`, `jsr` is a simple lightweight call-subroutine opcode (simply pushes a return address) and `ret` is the corresponding return, performing call/return within a compiled function. They are deprecated, but Java 5 compilers generate them and library JARs built to that standard are evidently still around.

https://github.com/smowton/cbmc/commit/fc186b4efcae8b47e547e1ca8dcf8382a75ddc69 provides a preliminary implementation.

### PR DESCRIPTION
**Pull request by smowton**
jsr is a simple lightweight call-subroutine opcode (simply pushes a return address) and ret is the corresponding return, performing call/return within a compiled function. They are deprecated, but Java 5 compilers generate them and library JARs built to that standard are evidently still around.

This implementation has a significant shortcoming: it considers the possibility of ret'ing to any jsr-site. This could be improved if we use basic dataflow analysis to determine which jsr targets can reach which ret instructions.

### CODE REVIEW

**Comment by smowton** [comment]
Pushed a basic test, which just looks for `jsr` being recognised at all. Verifying behaviour based on it is tricky as I can't readily synthesise jsr instructions without either installing a very old Java compiler or learning to write raw bytecode.

**Comment by smowton** [comment]
Also pushed style fixes.

**Comment by mgudemann** [comment]
I created a small class file using `jsr/ret` in the function `f`:
```
  public void f();
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=4, args_size=1
         0: goto          6
         3: astore_0      
         4: ret           0
         6: jsr           13
         9: jsr           3
        12: return        
        13: astore_3      
        14: ret           3
```
There's no assertion, but we could use coverage analysis in the regression test. It just jumps around in the code, no conditional or anything.
[test_jsr_ret.zip](https://github.com/diffblue/cbmc/files/697682/test_jsr_ret.zip)

**Comment by smowton** [comment]
Added Matthias' suggested test.

**Pull request merged**
