### PR TITLE
Avoid signed/unsigned casts and conversion in goto_inline

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Comment by kroening** [comment]
I would use goto_programt::nil_target here.

**Review by smowton — COMMENTED** [review]
`optionalt<unsigned>`?

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 02b9802fd469eeaea22e558223db7b64b241f564).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77224124
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Comment by tautschnig** [comment]
I have now implemented what @kroening suggested.

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: c0eaab593addd1d67477af2207e036696d398408).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78544392
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 01483478959ec0dfbeb05494d55e30c575360905).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/78549294
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

**Comment by tautschnig** [comment]
@allredj @peterschrammel @thk123 Any insights why TG might be failing on this one? It's certainly unexpected.

**Pull request merged**
