### PR TITLE
SV-COMP Wrapper

### PR DESCRIPTION
**Pull request by peterschrammel**
Adds the CBMC SV-COMP wrapper script and a Makefile to build the submission package

### CODE REVIEW

**Comment by rjmunro** [comment]
I think this should possibly go in a separate repository, and include CBMC as a dependency somehow.

**Comment by tautschnig** [comment]
@peterschrammel Would it be appropriate to have a diffblue/sv-comp repository? If so, could you please create one (as I can't). Otherwise, if you think this should just go in the CBMC repository I'm happy to approve this PR.

**Comment by peterschrammel** [comment]
I'm indifferent whether this should go into a separate public (?) repository or not.

**Comment by tautschnig** [comment]
What I am aiming for is to have sufficient information in one single place for any person with a bit of compute power at their hands to run those experiments; and ideally that would then be usable both for CBMC and 2ls, and maybe even other tools from the family.

**Comment by peterschrammel** [comment]
Ok. Let's make a public sv-comp repo then. 
The script won't be exactly the same for cbmc and 2ls because some of the command line arguments will differ, but anyways. The main goal for now is to have this in a place where we can track changes.

**Comment by tautschnig** [comment]
Ok, I'll seek to provide the extra automation to make the script work for both tools. But once we track changes all that is easy anyway.

**Comment by peterschrammel** [comment]
Here now: https://github.com/diffblue/cprover-sv-comp
Closing.

**Pull request closed without merging**
