### PR TITLE
Use new Doxygen script in Travis CI

### PR DESCRIPTION
**Pull request by johnnonweiler**
~The first commit here is from #3250 and the second is new.~  This changes `.travis.yml` to use the new script introduced by #3250, and removes the old `travis_doxygen.sh` script and associated part of
`run_diff.sh`.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by johnnonweiler** [comment]
This should not be merged until the current problem with duplicate .md files is fixed.

**Comment by johnnonweiler** [comment]
@thk123 It seems to be a very simple one line change to `.travis.yml` to use the new script.  This PR (hopefully) tests that, and makes the future switch a simple case of pressing 'Merge'.

**Comment by johnnonweiler** [comment]
~I'm investigating the CI results from this PR.  (The warnings related to `assumptions.md` were expected, but I don't know why there are other problems which I didn't see locally.)~
Warnings related to `assumptions.md` in the CI results are the expected issue due to duplicate .md files.

**Comment by johnnonweiler** [comment]
~#3281~ #3295 should fix the remaining remaining (`assumptions.md`) warnings.

**Review by owen-mc-diffblue — APPROVED** [review]

**Comment by johnnonweiler** [comment]
I've rebased and added a commit to update `expected_doxygen_warnings.txt`, with the new warnings which have been added (and the two which have been fixed 😃) since last week.

**Review by owen-mc-diffblue — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:warning:
Diffblue compatibility check is currently unavailable.
Please create manual bump.
(cbmc commit: a655ef95bbdf2366600a357cb1a91425bf0a5487).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90754733

**Pull request merged**
