### PR TITLE
Rewrite __CPROVER_assume(exists ...)

### PR DESCRIPTION
**Pull request by tautschnig**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 839a51b65a50a7b75067cd8643af8645123c0f19).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99030574

**Comment by kroening** [comment]
The terminology here doesn't work entirely -- the VCC is the entire thing, i.e., the formula that says that all the constraints and assumptions imply the assertion.

I'd make that parameter `vcc` an enum with choices `ASSERTION` and `ASSUMPTION`.

**Comment by tautschnig** [comment]
> The terminology here doesn't work entirely -- the VCC is the entire thing, i.e., the formula that says that all the constraints and assumptions imply the assertion.

Good point - I've now gone for a much more direct solution, it wasn't actually necessary to pass any additional parameter.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 54f29cd9b5b5e03d056b0694839d8d52a479132c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/101231595

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: e83d856ae83ba588368db25dbdf7380ae34e2b85).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102435494

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: cebdb0dff9eb910f134e6e766beb9c4826419494).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102863763

**Review by smowton — APPROVED** [review]

**Pull request merged**
