### PR TITLE
Fix signatures for methods in java.lang.Character

### PR DESCRIPTION
**Pull request by antlechner**

### CODE REVIEW

**Comment by antlechner** [comment]
Suggested reviewers:
@romainbrenguier 
@reuk

**Comment by antlechner** [comment]
Also, I'm not sure if it's intentional that
```java.lang.Character.hashCode:()I```
is included but
```java.lang.Character.hashCode:(C)I```
is not?

**Comment by antlechner** [comment]
More fixes are needed for this file, see:
https://diffblue.atlassian.net/browse/TG-775

**Review by romainbrenguier — APPROVED** [review]

**Comment by romainbrenguier** [comment]
> Also, I'm not sure if it's intentional that
> java.lang.Character.hashCode:()I
> is included but
> java.lang.Character.hashCode:(C)I
> is not?

Looking at how it is implemented, I would say it should have been the opposite:
the primitive type can be converted directly to an int (like it done now), but for the `Character` object we should first access its `value` field (which is not done).

**Pull request merged**
