### PR TITLE
set mode of gcc_builtin_va_arg symbol; partially addresses issue #2663

### PR DESCRIPTION
**Pull request by kroening**

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Review by tautschnig — CHANGES_REQUESTED** [review]
This feels like a deja vu of #2624. It's not exactly the same, but can we now please have a test?

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 737c8c38072d44f3ae6ce4c1c6a43deac147c739).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85620651

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 9815749e63c2b16c01d0ad96bda86a070206c506).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/94084746

**Comment by tautschnig** [comment]
Closing in favour of #3767, which includes tests.

**Pull request closed without merging**
