### PR TITLE
Remove preprocessing of CProverString.insert for non-String arguments

### PR DESCRIPTION
**Pull request by romainbrenguier**
We replace the preprocessing of CProverString.insert for characters, booleans etc. and provide models that use String.valueOf and the String version of CProverString.insert instead.
This is too reduce the number of builtin functions the solver has too handle, making it simpler and easier too debug and test, and less likely to have bugs, without reducing its expressive power: we can still get the same behavior as before by combining two function calls.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Review by danpoe — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0d71098b7ddf2af713b2de66d0d63be8e1b597b7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/123717057

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: ea21ccaf197de60e97883f1e5780ee1213406a98).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/123947553
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Comment by romainbrenguier** [comment]
the corresponding test-gen pull request passed CI https://github.com/diffblue/test-gen/pull/3806

**Comment by romainbrenguier** [comment]
java-models-library update now pointing to master

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 24027737a5f85b94c28fc2c24471b472652844be).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/124071536

**Pull request merged**
