### PR TITLE
[TG-1404] Bugfix incomplete coverage in virtual method dispatch

### PR DESCRIPTION
**Pull request by romainbrenguier**
Before this PR block with an assume false was generated.
This was leading to report of incomplete coverage.
Instead of this we generate assumption that the class identifier are
different from the non-loaded type all in the same block.

### CODE REVIEW

**Comment by smowton** [comment]
Could you give an example of what's happening? This sounds like it should amount to the same assumption -- i.e. that we cannot possibly get to this virtual callsite.

**Comment by romainbrenguier** [comment]
@smowton 
> Could you give an example of what's happening? 

Yes I will try to add some regression tests to this PR

> This sounds like it should amount to the same assumption -- i.e. that we cannot possibly get to this virtual callsite.

Yes the assumptions are the same. The difference is we don't generate extra blocks for this unreachable callsites. This makes a difference in the reported coverage with `--cover location`.

**Review by smowton — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Comment by romainbrenguier** [comment]
@mgudemann This PR and https://github.com/diffblue/cbmc/pull/1731 have some conflicts, so I'm not sure which one should be merged first ?
I have a version of this branch rebased on @mgudemann 's PR https://github.com/romainbrenguier/cbmc/tree/bugfix/all_resolved_calls1931_coverage_dispatch1404

**Comment by mgudemann** [comment]
@romainbrenguier is this relevant or was it obsoleted by #1830

**Comment by romainbrenguier** [comment]
@mgudemann https://github.com/diffblue/cbmc/pull/1830 fixes the bug whose effect we were trying to minimize here so the other PR is more relevant. However this change could still be made, it can remove a few instruction from the goto-programs. I just don't know if it's worth it.

**Comment by romainbrenguier** [comment]
The main coverage issue is fixed, and this changes are no longer necessary so I'm closing this PR.

**Pull request closed without merging**
