### PR TITLE
added ACSL lambda expressions

### PR DESCRIPTION
**Pull request by kroening**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [X] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: d6cde87718698a42a843036c17822036794a4acd).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95932130
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by tautschnig — CHANGES_REQUESTED** [review]
This needs a test, a commit message, and is failing TG checks (for an unknown reason).

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: eb0752836e4bf15104b923f4bc56b1f87613034c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99124052
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 459df93752c049cf990f70707bba0da7e0dd711b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99565332
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by kroening** [comment]
Now with test, and it's now a `binding_exprt`.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: ad5067f17c38bbbf678cbce4e4bca9ae5751b1f3).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/122356557

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: a81eb11b3d2e75a7f2ea2ec53a7a4945c76d447d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/122685580
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 07ad3b93294527752f4576b20dfc9cacfdde913b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/123383611

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: cc460f2264182a2bf67799e83fdc9cd384765d02).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/127696328

**Review by tautschnig — APPROVED** [review]
This needs a rebase, but otherwise looks good now.

**Pull request merged**
