### PR TITLE
Symex improvements

### PR DESCRIPTION
**Pull request by tautschnig**
Major performance improvement (taking one of my examples from 13s to 0.3s) when dealing with larger static arrays via  c6a92a8; the other patches are mostly cleanup and some improvements to output. Finally a new option to perform time-limited search (aa3a00d).

### CODE REVIEW

**Comment by DanielNeville** [comment]
Hi Michael, thanks for this - greatly appreciated.  Which examples have you been testing this on?

**Comment by tautschnig** [comment]
@DanielNeville Apologies for the late response. I can't share the code this being run on I'm afraid - but I'd be happy to give any code (that can be shared) a try and debug&profile further.

**Comment by forejtv** [comment]
@tautschnig can you rebase, please?

**Comment by tautschnig** [comment]
Rebase done.

**Comment by kroening** [comment]
My concern about this is that we can no longer have limit "0", e.g., "no interleaving".

**Comment by tautschnig** [comment]
The defaults for limits are now set to -1, and 0 has become a valid limit.

**Comment by kroening** [comment]
Ah, now produces warnings because of signed/unsigned comparisons.

The is_set idiom may have its advantages.

**Pull request merged**
