### PR TITLE
Always update initialized Java arrays in place

### PR DESCRIPTION
**Pull request by allredj**
This is not a change in behaviour, array initialization actually never happened with anything else but the
update_in_placet::NO_UPDATE_IN_PLACE.

Assert that we always have update_in_placet::NO_UPDATE_IN_PLACE and
simplify the code accordingly.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 45ab6df55138ccd7ca0a1642c6603ccf2febeb3b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97227351
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by smowton** [comment]
Do we care about stub-side-effects these days? If we do, then I'd say we should make MUST_UPDATE_IN_PLACE do its job properly and potentially rewrite the array cells!

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 2d47b493a74fa3833598a71939be7abc68c02bda).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97259768

**Comment by allredj** [comment]
Keeping this code at the moment, as it may become useful again when we go back to implementing side-effects of stubs. Also, I no longer need to modify this part of the code, so no need to clean up for now.

**Pull request closed without merging**
