### PR TITLE
[Don't merge] Goto trace refactor

### PR DESCRIPTION
**Pull request by reuk**
We remove the `goto_trace_stept::typet` enum, replacing it with a set of discrete concrete types representing the different kinds of goto instruction. This improves type safety, and in the future could allow us to place stronger constraints on the types of values each instruction is allowed to hold. For example, at the moment some data members of `goto_trace_stept` are only used by some kinds of instruction. By splitting instructions into several different types, only `trace_inputt` and `trace_outputt` would need to hold
```
   irep_idt format_string, io_id;
   io_argst io_args;
   bool formatted;
```
and only `trace_function_callt` and `trace_function_returnt` will need to hold
```
   // for function call/return
   irep_idt identifier;
```

### CODE REVIEW

**Review by tautschnig — CHANGES_REQUESTED** [review]
Let me try to be constructive:
1. https://dev.to/bosepchuk/optimal-pull-request-size-600
2. The linter speaks for itself.
3. https://chris.beams.io/posts/git-commit/ (I dislike repeating myself, FWIW).
~4. Introducing new APIs that do not include comments (see 3 concerning the corresponding commit message, which could have been a fallback option) is a no-go.~

While I do get the overarching topic of this PR, for the reasons laid out in 1 you should not mix up different bits of work. Specifically, this PR has at least 3 steps: a) the use of `unique_ptr`; b) moving from enums to distinct types; c) the use of a visitor. I'm not saying that any of this is wrong, but together this resulted in 32 commits that represent how this historically evolved rather than separate topics and ~+2,726 −1,628~+2,779 −1,628 changes.

2 and ~4~ above are blockers. I'll dismiss this blocker once those are addressed and then maybe someone else is willing to thoroughly review this.

~Causing an ICE with Visual Studio is also a blocker, of interesting sorts...~

Addendum: I get the idea of type safety, but I'm a bit surprised that this required more than a 1000 extra lines of code. Nothing blocking, but still curious.

**Comment by LAJW** [comment]
@tautschnig The longer we let it fester, the larger eventual PR size will be. I just wonder whether that PR would be acceptable without visitors? That would definitely make it much shorter.

**Comment by tautschnig** [comment]
> @tautschnig The longer we let it fester, the larger eventual PR size will be.

You might agree that that's one of the key points of the first link that I provided? You are setting a monster task for reviewers. If you provide reviewable chunks, you are set up to have quick turnarounds, and thus "longer" and "larger" wouldn't happen.

> I just wonder whether that PR would be acceptable without visitors? That would definitely make it much shorter.

That's a question I'd prefer not to answer. To me, visitors enable a much cleaner design, but the incurred code churn when visitors aren't used from the start speaks against them. This is a design change, not a functional one; visitors have better performance (and type safety) than switch/if-else, but a) this is not on a hot path and b) there is some overhead that might outweigh the performance gains. To me, I don't see any aspect of sufficient weight to tip the scales either direction. Thus please solicit further opinions.

**Review by peterschrammel — CHANGES_REQUESTED** [review]
@reuk, whereas I agree with the aims of this PR, such a massive API change breaks at least 5 tools that build upon the CBMC codebase. You have to make these changes in small steps that allow you keeping the old API unchanged in parallel and deprecate it after a certain time to allow the other codebases to transition smoothly.

**Pull request closed without merging**
