### PR TITLE
Refactor/ait visit edge

### PR DESCRIPTION
**Pull request by martin-cs**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Comment by smowton** [comment]
@owen-jones-diffblue I recall you refactored `ait` (or possibly `static_analysist`) in our branch to unify the calls to `transform` in the function-call and generic-instruction paths? If so, this is how it's being done upstream and we should mirror it in due course.

**Comment by martin-cs** [comment]
@owen-jones-diffblue : I plan lots more changes in this area.  If you let me know about your diffs then I can try to minimise the resultant breakage.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: e4a01fdff1a3ed0edf4f72bd8d8f7ac759c977ae).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105440777
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: aa0671850faa4c595ac3f9d18cd3e4b8d2ad57e5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105483566

**Review by peterschrammel — APPROVED** [review]

**Comment by owen-mc-diffblue** [comment]
@smowton Good memory. I just looked it up and it turns out it was in `static_analysist`.

**Comment by martin-cs** [comment]
@owen-jones-diffblue and @smowton : If someone had a plan to migrate over the one use of `static_analysist` to `ait` and finally remove it in the next month or so, how much would that ruin your day?

**Comment by smowton** [comment]
@martin-cs I'd been meaning to finish https://github.com/diffblue/cbmc/pull/2131 for ages

**Comment by owen-mc-diffblue** [comment]
@martin-cs That would be great.

**Comment by martin-cs** [comment]
On Tue, 2019-03-26 at 14:19 +0000, Chris Smowton wrote:
> @martin-cs I'd been meaning to finish https://github.com/diffblue/cbm
> c/pull/2131 for ages

Good to know I'm not the only one with "I've been meaning to finish"
patches :-)

I'm in the process of changing how ait stores domains so we can have
not only context/history sensitive analysis but also location
insensitive analysis and your domain pruning analysis.  Once that is
done and Chris's team have sorted out some technicalities around
function pointer removal, I think we will be good to remove both other
AI frameworks and also do AI powered function pointer removal.  How
about we resurrect #2131 as part of that?

**Pull request merged**
