### PR TITLE
Modest show_loop_ids cleanup

### PR DESCRIPTION
**Pull request by kroening**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 9a9a80c066c3e9c6ca3fb96ad916ab1e54e3a642).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87407180

**Review by smowton — COMMENTED** [review]
Seems pointless to unpublish the single-function variant (useful as a debugging aid? Might reasonably be used out of tree, and no extra effort for us to maintain?); cleanup is fine

**Comment by kroening** [comment]
@smowton Could pass identifier instead of removing?

**Comment by smowton** [comment]
Yes {irep_idt name, const goto_programt &program} is fine

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: cc1c44cb583c8694d59e9d48ff6241b31aac1a36).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87759276

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
