### PR TITLE
goto-gcc hybrid binaries on OS X

### PR DESCRIPTION
**Pull request by tautschnig**
Depends on #3702, #3866, only the last three commits are specifically for this feature. They finally provide a test for the code touched in #3702.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 48629e2b62fe89f61819ea73f38f1e2418845b4f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98026294

**Review by chrisr-diffblue — APPROVED** [review]
I'm not an expert on Mach-O (only read the lowlevelbits.org summary, plus some background knowledge of other object formats, such as ELF, COFF, etc). Mach-O parsing functionality looks OK to me. I might question the user experience a bit though. For instance, what happens if a user on, say, a linux host attempts to analyse Mach-O object files? As far as I can tell they'll get told that the files are not goto-programs - where in reality the situation is that reading Mach-O object files is only supported on __APPLE__ platforms. It would be a nicer if there was an explicit message to that affect.

**Review by smowton — APPROVED** [review]
On grounds the @chrisr-diffblue knows his onions, happy to proxy approve :)

**Comment by tautschnig** [comment]
Rebase done, I'll try to implement @chrisr-diffblue's suggestion as soon as possible.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: aeeccd1b8250e21e5deb7e56e1cf91cb5cc48dd3).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98143634

**Comment by tautschnig** [comment]
@chrisr-diffblue @smowton @kroening I have added a commit that should enable detection, and yield a warning if we are on a platform where we cannot fully parse the file. Should be ready for (re-)review.

**Comment by chrisr-diffblue** [comment]
LGTM - thanks for the improved user experience.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 82489a3b34dd59aa17278ef5f8e837eaa897e676).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98354493
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
I'm rather surprised that TG fails for this one.

**Comment by tautschnig** [comment]
Or maybe not, 82489a3 includes a necessary addition of a message handler.

**Review by peterschrammel — APPROVED** [review]

**Comment by allredj** [comment]
TG update: https://github.com/diffblue/test-gen/pull/2857

**Comment by allredj** [comment]
@tautschnig TG bump passed

**Comment by tautschnig** [comment]
Thanks @allredj! Now just needs a review from @kroening.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 3c18576ce65d402fa48d4f0f486dee92b353d23f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98713564
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: adc6af13863e72a8a0bd598563e1cbf051020b55).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100295745
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 7893de0e070f8751d520164a62f86923e791e83d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102433712
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: d16fdcb10cd5609bd76d94ae48ab2d4c87b86ebd).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103556283
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by allredj — COMMENTED** [review]
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 76600d0d0fc1942e7afb6544fb03de0881cb88de).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/104510954
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

**Review by kroening — APPROVED** [review]

**Pull request merged**
