### PR TITLE
Answer yes to all question of 7z

### PR DESCRIPTION
**Pull request by romainbrenguier**
This prevents appveyor from being stuck when extracting win_flex_bison

### CODE REVIEW

**Comment by romainbrenguier** [comment]
Actually PR https://github.com/diffblue/cbmc/pull/1658 may be a better solution to the appveyor problem.

**Comment by romainbrenguier** [comment]
> Actually PR #1658 may be a better solution to the appveyor problem.

No it is actually the same...

**Comment by romainbrenguier** [comment]
PR #1658 which does the same thing is now merged

**Comment by tautschnig** [comment]
> No it is actually the same...

Indeed my initial attempt was different (trying to do cleanup), but that just got me more weird Powershell errors. Lazy as I am, I went with the force :)

**Pull request closed without merging**
