### PR TITLE
 Replace Object.getClass preprocessing by a CProver.classIdentifier method

### PR DESCRIPTION
**Pull request by romainbrenguier**
This simplifies the preprocessing and leave it to the model to handle
the complexity, which is less error-prone.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [na] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by romainbrenguier** [comment]
There is a test for getClass in `jbmc/regression/jbmc-strings/ClassName` but I will add others for the new `CProver.classIdentifier`.

**Comment by romainbrenguier** [comment]
> There is a test for getClass in jbmc/regression/jbmc-strings/ClassName but I will add others for the new CProver.classIdentifier.

Test added

**Review by smowton — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d4079e6aebf3604b1e7d5b3505a0edebd98f072b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/107932717

**Review by allredj — APPROVED** [review]
Looks good!

**Comment by allredj** [comment]
java-models-library PR needs to be merged first, then the pointer updated, then this can go in.

**Comment by romainbrenguier** [comment]
java-models-library update now pointing to master

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d84171268396c8b86dffef1ab6fbf10a7fc9f0a9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/107948360

**Pull request merged**
