### PR TITLE
goto-model validation: Validate constant_exprt

### LINKED ISSUE #6759: CBMC accepts `-<hex>` constants at the irep level, but does the wrong thing with them
CBMC should either error, or accept.

### PR DESCRIPTION
**Pull request by tautschnig**
We silently accept, and sometimes handle correctly, bitvector constants
that are encoded as -[absolute value] instead of two's complement. The
simplifier, however, will not handle this ambiguity as equalities over
constants are evaluated by comparing the value strings. Therefore, use
goto-model validation to ensure we do not process bitvector constants
that don't use two's complement encoding.

Fixes: #6759

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
While at it, we should also check that there are no leading zeros.

**Comment by kroening** [comment]
Oh, and we need to stick to either 'A'-'F' or 'a'-'f', but shouldn't allow both.

**Comment by tautschnig** [comment]
> While at it, we should also check that there are no leading zeros.

Done!

**Comment by tautschnig** [comment]
> Oh, and we need to stick to either 'A'-'F' or 'a'-'f', but shouldn't allow both.

Oh, that would indeed just cause the same sort of trouble. Check is now more constrained.

**Review by kroening — APPROVED** [review]

**Pull request merged**
