### PR TITLE
source location of the generated 'default' label

### PR DESCRIPTION
**Pull request by kroening**
source location of the generated 'default' label of switch statements is now the end of the switch body instead of the swtich statement

In addition, a mild bit of cleanup is performed.

### CODE REVIEW

**Comment by kroening** [comment]
Indeed, it's not great that the location of the switch(...) is lost; I have added a 'LOCATION' node, as a separate commit.

**Comment by tautschnig** [comment]
> Indeed, it's not great that the location of the switch(...) is lost; I have added a 'LOCATION' node, as a separate commit.

I'm surprised this is necessary: all the GOTO instructions that branch to the individual cases should have the location of `switch(...)`, unless I'm mistaken?

**Comment by kroening** [comment]
No, they get the location of the 'case X:' label.

**Comment by tautschnig** [comment]
Ok, will await completion of the CI tests. If the coverage report still fails, then the regression test pattern check should be changed as part of the commit.

**Pull request merged**
