### PR TITLE
Include order fix

### PR DESCRIPTION
**Pull request by reuk**
Header files should include everything that they need in order to compile cleanly. The simplest way to ensure that this is the case is to have each source file include its corresponding header file first, before declaring anything else.

This patch moves includes in source files so that the corresponding header file is always included first. In some cases, this broke the build because the header files weren't standalone. In these cases, the header files have been updated to properly reflect their dependencies.

### CODE REVIEW

**Comment by kroening** [comment]
Needs a rebase, but otherwise ready to go

**Comment by peterschrammel** [comment]
@kroening, looks ready to go.

**Comment by kroening** [comment]
Apologies, another rebase is needed.

**Comment by reuk** [comment]
Rebased.

**Pull request merged**
