### PR TITLE
Zero-initialize Class literals before calling initializer function

### PR DESCRIPTION
**Pull request by smowton**
This (a) sets the class-identifier to "java.lang.Class," which wasn't being done before,
and (b) allows the class initializer to assume fields are nulled before entry, as for a normal
constructor.

This is a fixup to https://github.com/diffblue/cbmc/pull/2237

### CODE REVIEW

**Comment by smowton** [comment]
Test-gen bump: https://github.com/diffblue/test-gen/pull/1907

**Review by thk123 — COMMENTED** [review]
Don't see anything wrong but don't really understand the connection between the test and the change

**Comment by smowton** [comment]
Previously the @class_identifier field was left unset, which meant `assert Integer.class instanceof Class` for example would not pass.

**Comment by thk123** [comment]
OK thanks - lgtm pending CI of course

**Review by mgudemann — APPROVED** [review]

**Pull request merged**
