### PR TITLE
Some extra tests for do_function_call_symbol

### PR DESCRIPTION
**Pull request by hannes-steffenhagen-diffblue**
These tests demonstrate that 'error' conditions in builtin_functions.cpp can currently be reached; This will be useful for improving the frontend to catch them earlier.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
> Each commit message has a non-empty body, explaining why the change was made.

Would you mind adding such an explanation, likely more or less copying what was discussed on the other PR? Later on it will be really hard to figure out why those tests were added given just the current commit message. Thanks!

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: a8b4291c132ab8f5d7027fa11578aad374054f28).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86319649

**Review by tautschnig — APPROVED** [review]
Thank you!!!

**Review by allredj — COMMENTED** [review]
This PR failed Diffblue compatibility checks (cbmc commit: 5c9bcd178ecd3ca373a37411ab31a6be0af60288).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86328246
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 64c5d8677ecf25196ed99dece574c84df29b0166).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86329764

**Pull request merged**
