### PR TITLE
Replace uses of deprecated index_exprt constructors

### PR DESCRIPTION
**Pull request by tautschnig**
- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by kroening** [comment]
I would probably hold the second commit for a bit longer. The commit that deprecated that constructor is from Sep 21 2018, and I would give it perhaps a minimum of 6 months.

**Review by kroening — APPROVED** [review]

**Comment by tautschnig** [comment]
@kroening Done, this PR now just has the first commit.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5af02b30aac90b3222e7ef070e20a294f07f6173).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97070479

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: fcf93d70624b575c9fda7a31af3b4ee0b2b3dd6e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97075928

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 088b35ff166edf4041a16027895f57aed83019b8).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/97113006

**Pull request merged**
