### PR TITLE
Fix SMT2 parse bug

### PR DESCRIPTION
**Pull request by pkesseli**
`bv_typet` is not supported by `numeric_cast_v`, so this always fails.
`parse_literal` creates a simple literal, hence we use an `unsignedbv`
instead.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: c5df3ea77e2b1bd954ede4672e0c30e66c2b7e81).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86520447

**Review by tautschnig — COMMENTED** [review]
Do all uses of `bv_typet` or `ID_bv` warrant some further scrutiny? Would anyone be able to to shed some light what the value of `bv_typet` actually is (@kroening maybe?) - there are more uses of this, even in the same file, and it's not clear to me that fixing just this one instance is the right thing to do.

**Comment by pkesseli** [comment]
I don't think direct use of `bv_typet` is deprecated in general? Although it occurs rarely in the CBMC codebase. What's definitely unsupported is explicitly calling `numeric_cast_v` with a `bv_typet` expression. But so far as I can tell that only happens once, at least in this module.

**Comment by tautschnig** [comment]
I suppose representing arbitrary bitfields is a valid (the only valid) use case. There are more uses, e.g., to encode the width of a type. Those do not seem valid to me.

**Comment by pkesseli** [comment]
There are three more uses of `bv_typet` in this file. The first one on line 268 seems legitimate since they are just three components without own value, which get concatenated as strings:
```
      constant_exprt s1=parse_literal(src.get_sub()[1], bv_typet(1));
      constant_exprt s2=
        parse_literal(src.get_sub()[2], bv_typet(floatbv_type.get_e()));
      constant_exprt s3=
        parse_literal(src.get_sub()[3], bv_typet(floatbv_type.get_f()));
      // stitch the bits together
      std::string bits=id2string(s1.get_value())+
                       id2string(s2.get_value())+
                       id2string(s3.get_value());
```

The next one on 376 represents a flattened union, so probably reasonable as well, and the last one on 415 is a flattened struct, so same story.

**Comment by kroening** [comment]
bv_typet is a bit-vector without a numerical interpretation; this suits the SMT-LIB bit-vector theory well, as this assigns interpretation when using particular operators.

I'd add a special case in smt2_convt::parse_literal, since passing bv_typet() to from_integer() does not make a lot of sense.

**Review by tautschnig — CHANGES_REQUESTED** [review]
Upon a further look into the code: `parse_literal` explicitly handles the case `type.id()==ID_bv`, which is wrong by way of what the comment about `bv_typet` (no numerical interpretation) says. So maybe the proposed change is right, but it can only be part of further fixes.

**Comment by tautschnig** [comment]
A proper fix needs inspection of all the locations in `edit-list` for the following
```
$ git grep -w -n bv_typet > edit-list
$ git grep -w -n ID_bv >> edit-list
```
We have several, inconsistent definitions of "is a bitvector type" and in many cases don't make use of any of them. It's not just the SMT2 back-end that liberally treats a `bv_typet` as something that `from_integer` can sanely be applied to.

@pkesseli @kroening you seem to have some sort of test show-casing the problem, so could you please look into this?

**Comment by pkesseli** [comment]
I have a test case for this, but effectively any C use case run with SMT back-end should trigger it, as this code is necessary to parse pointers as bv literals from the output.

However, that's only with respect to the SMT output parser. As I go through all the other modules I'm sure more tests will be necessary to cover the effects of this purge. :-)

**Comment by pkesseli** [comment]
That's the "test case" by the way:

```
int main(void)
{
  __CPROVER_assert((__CPROVER_bool)0, "");
}
```

So yeah, the SMT back-end is out of commission for C programs. I assume we don't really have any proper SMT tests that could have detected this. Should I add `z3` to the CI specs and add this regression test?

**Comment by kroening** [comment]
@pkesseli No, Z3 is too heavy as a build dependency. We could have a few tests with a 'fake' solver, i.e., a script that delivers a recorded response.

**Comment by tautschnig** [comment]
We don't need to add z3 as a strict build dependency, but could still run it in Travis/CodeBuild? Adding `z3` as another package to be installed should do the trick.

**Comment by pkesseli** [comment]
What I'm creating now is a small `z3` dummy bash script with a map of pre-configured outputs per input file. The benefit of this is that it won't prevent any regular users from running the regression tests that I'm creating.

We can still replace this dummy by an actual `z3` executable at any point in the future if we wish.

**Comment by pkesseli** [comment]
Actually, scratch that. Managing a `PATH` in the regression tests for a fake `z3` becomes quite clumsy and the fake `z3` is not very scalable.

I'll create a separate directory `cbmc-smt` in `regression` which is not run by default, only on CI where I'll add `z3` to the `apt` packages.

**Comment by pkesseli** [comment]
@tautschnig Ready for re-review. Should I run clang-format on the whole `smt2_conv.cpp` file?

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 4119072dcadde9f3b3dc97599ba02043a7460fb5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87078203

**Comment by kroening** [comment]
I am still weary of pulling Z3 into CI: Our CI is already very slow and frail, and adding a dependency on an external server will only make that worse.

**Comment by kroening** [comment]
Another concern is that this PR introduces a command line option --no-data-types.
Model checking tools in particular should refrain from too many configuration options. The perception that model checkers are too hard to configure is something that has plagued model checkers since BDD times.

**Comment by kroening** [comment]
To move forward on this: an alternative to Z3 would be the built-in SMT2 solver! The binary gets created already.

**Comment by tautschnig** [comment]
I think @kroening has highlighted a number of issues, and I think those should result in separate PRs to discuss them properly. We have (at least):
1) A new command-line option.
2) Fixing `ID_bv`/`bv_typet` related problems.
3) Running SMT solvers in CI.
4) Doing regression tests _of_ the internal SMT solver.

**Comment by pkesseli** [comment]
Thanks for the quick responses! Just a few points:

1. "Running SMT solvers in CI" was introduced to have regression tests verifying the changes in "Fixing `ID_bv` / `bv_typet` related problems". I am happy to create three PRs and just have them refer to each other in the PR description if that's okay with you two.
2. `--no-data-types` was only introduced to explicitly force flattening of `struct` types in `z3` for the tests, since that's one case affected by the `bv_typet` changes that couldn't normally be tested with `z3`. This could be solved by using another SMT solver, but I just checked, our `smt2_solver` can't handle the four C regression tests yet. We can try to go for another third party solver, though `z3` seems by far the most CI-friendly choice. What do you two reckon?

**Comment by pkesseli** [comment]
Replaced by:
- https://github.com/diffblue/cbmc/pull/3119
- https://github.com/diffblue/cbmc/pull/3120
- https://github.com/diffblue/cbmc/pull/3121

**Pull request closed without merging**
