### PR TITLE
Fix is_goto_binary to pass extended Mach-O header to osx_fat_reader

### PR DESCRIPTION
**Pull request by smowton**
This resolves a mistake introduced in 5be1db8eb6a282aeda9c872406d8629af4768f77, which tried to differentiate Mach-O fat binaries from Java class files, but only changed one user to pass the required extended header.

We also extend the unit tests to verify GBFs are detected in both Mach-O and ELF containers.

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]

**Review by chrisr-diffblue — APPROVED** [review]
I'm not a code owner for these files, but have confirmed this is working on OSX for me, and the code change looks sensible.

**Comment by tautschnig** [comment]
@smowton In contrast to what @chrisr-diffblue said, Travis claims there is a problem on OSX?!

**Comment by chrisr-diffblue** [comment]
Ah, wondrous... I'll do a completely clean build locally again just to make sure it's all OK for me. For reference, I'm on OSX Mojave 10.14.5, Apple clang version 11.0.0.

**Comment by chrisr-diffblue** [comment]
Yes, I now get that build failure (unit test build failure) locally having done a completely clean build. The tools themselves do work as expected for me though - it's just the unit test build that failed:

```
cr@DB0285:~/tmp$ ~/Code/cbmc/build/release/bin/goto-gcc hello.c -o hello.gb
cr@DB0285:~/tmp$ ~/Code/cbmc/build/release/bin/cbmc hello.gb
CBMC version 5.12 (cbmc-5.11-3239-g91a93cc41) 64-bit x86_64 macos
Reading GOTO program from file
Reading: hello.gb
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
size of program expression: 55 steps
simple slicing removed 0 assignments
Generated 0 VCC(s), 0 remaining after simplification
VERIFICATION SUCCESSFUL
cr@DB0285:~/tmp$ chmod +x hello.gb
cr@DB0285:~/tmp$ ./hello.gb
Hello world
```

**Comment by chrisr-diffblue** [comment]
I think the use of `fat_macho_output_handler.str()` and `fat_macho_with_gbf_output_handler.str()` should be `fat_macho_output.str()` and `fat_macho_with_gbf_output.str()` respectively? But if so, I'm not sure how this managed to pass CI on the non OS X platforms?

**Comment by chrisr-diffblue** [comment]
Confirmed - if I make that change to those two lines, I can build fine locally and unit and regression tests pass.

**Comment by chrisr-diffblue** [comment]
Answering my own query - of course, it's because those lines are conditionally compiled, so don't get compiled on non OSX platforms...

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0aa279dfc493ed79cf9c6c2e7932be3e18f13562).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114735313

**Pull request merged**
