### PR TITLE
add __CPROVER_is_cstring(p) and __CPROVER_cstrlen(p)

### PR DESCRIPTION
**Pull request by kroening**
This adds two builtins to the C frontend, `__CPROVER_is_cstring(p)` and `__CPROVER_cstrlen(p)`, as shorter alternatives to `is_zero_string` and `zero_string_length`.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
> This adds two builtins to the C frontend, __CPROVER_is_cstring(p) and __CPROVER_cstrlen(p), as shorter alternatives to is_zero_string and zero_string_length.

Is that shorter name really enough of a benefit to warrant the churn? Also, unlike their "longer" counterparts, nothing is done to actually make string abstraction support them.

**Comment by kroening** [comment]
No plan to add them to the string abstraction; they are meant for the CHC encoder, and it's deliberate that the name is different to avoid any interation.

**Comment by tautschnig** [comment]
> No plan to add them to the string abstraction; they are meant for the CHC encoder, and it's deliberate that the name is different to avoid any interation.

But then the rationale provided in the commit message is confusing. And there isn't any kind of documentation, so it will be very hard for anyone to know when (not) to use them?!

**Comment by kroening** [comment]
Fixed the commit message.

**Review by tautschnig — APPROVED** [review]

**Comment by tautschnig** [comment]
Needs a rebase.

**Pull request merged**
