### PR TITLE
Set mode of if_exprt introduced in preprocessing

### PR DESCRIPTION
**Pull request by romainbrenguier**
A temporary variable is introduced later for this if_exprt and the mode
needs to be known for the variable, other an invariant may fail.

### CODE REVIEW

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — APPROVED** [review]

**Review by tautschnig — DISMISSED** [review]
The blocker for me is the absence of any regression test.

What I'd really like to see is revisit this setting of `ID_mode` on some subset of expressions. There ought to be sufficient contextual information available to avoid this. (For example the function within which the expression to be converted lives.)

Edit: `goto_convertt::make_temp_symbol` should take an additional `mode` argument instead of attempting to do `expr.get(ID_mode)` and so should `goto_convertt::remove_statement_expression` and `goto_convertt::clean_expr`. The other remaining use of `expr.get(ID_mode)` is the only safe one.

**Comment by peterschrammel** [comment]
@tautschnig, I agree with the above. However, since #2052 has been merged prematurely, this needs an urgent fix now.

**Comment by romainbrenguier** [comment]
@tautschnig I added a regression test for this fix

**Comment by tautschnig** [comment]
> [...] this needs an urgent fix now.

As always, feel free to just merge despite my disagreement ("requested changes"). But please do fix properly with moderate urgency.

**Pull request merged**
