### PR TITLE
Update CATCH to version 2.5.0

### PR DESCRIPTION
**Pull request by tautschnig**
Downloaded via
https://github.com/catchorg/Catch2/releases/download/v2.5.0/catch.hpp

Version 2 also addresses the only local change we ever had, which was adding
"const &" to the exception type.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 4f780a30715b01d50d662a0d924016b4936b90c4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98209867
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by kroening — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 02fe307b7ec520deaa16793ac568537341c403da).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98331058
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by tautschnig** [comment]
@allredj @peterschrammel @thk123 This seems to continue to trip up TG. I'm not actually sure why, though. Could you please take a look?

**Comment by allredj** [comment]
@tautschnig Looks like this one also needs a manual bump. Will look at this tomorrow.

**Comment by allredj** [comment]
TG update: https://github.com/diffblue/test-gen/pull/2861

**Comment by allredj** [comment]
@tautschnig 
TG bump passing. Can be merged.

**Comment by tautschnig** [comment]
Thanks a lot @allredj!!

**Pull request merged**
