### PR TITLE
goto-cc: show error line

### PR DESCRIPTION
**Pull request by kroening**
- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: 2e82952ee03b5c9f5462e5449c76ed4d8dd2ad9a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/89338570

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
Passed Diffblue compatibility checks (cbmc commit: eee690f1823d056d1dda772bc1caacab070d1926).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/89441743

**Review by smowton — APPROVED** [review]

**Review by tautschnig — APPROVED** [review]
Thanks for adding a test!

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3a1b47f7c4d86a39001b9f431c09a56089803bf4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/89501463

**Pull request merged**
