### PR TITLE
Revert "property_checkert interface"

### PR DESCRIPTION
**Pull request by tautschnig**
This reverts commit d88ffd43f9a694301f36a2ed16c10dc7d9ac1850.

Doing so might not actually be desirable, but the code is neither sufficiently documented nor actually used within the repository (though apparently be 2LS and Deltacheck). Input from @peterschrammel required.

### CODE REVIEW

**Review by peterschrammel — CHANGES_REQUESTED** [review]
This is actually be the base class that the various BMC/Symex variants that are currently packed into `bmct` should implement.

**Comment by tautschnig** [comment]
@kroening @peterschrammel Would you mind providing the high-level idea of how this is supposed to be used? Given the absence of documentation I'll try to reverse-engineer it from 2LS, but receiving brief guidance would be very much appreciated. The main question is: what is this interface supposed to separate, i.e., what is to be moved to the implementation of the interface and what invokes the interface's methods?

**Comment by peterschrammel** [comment]
The bigger idea is: As a user I want to run one or more property checkers (I can instantiate whatever implementations we have: BMC, path-based symex, incremental BMC, abstract interpretation, k-induction, IC3, ...) and report and fuse results from multiple runs (portfolio, heuristic selection of an appropriate checker or some other strategy).

**Comment by martin-cs** [comment]
@peterschrammel : that sounds like a good thing to do / want.  Is it worth opening an issue / creating some kind of plan for getting that implemented in the existing CPROVER tools?

**Comment by tautschnig** [comment]
@peterschrammel Given all your work, can this now actually be done (i.e., `property_checkert` be removed)?

**Comment by peterschrammel** [comment]
This still has to wait a bit until symex-driven lazy loading has been ported to goto-checker.

**Comment by tautschnig** [comment]
> This still has to wait a bit until symex-driven lazy loading has been ported to goto-checker.

Has that time already come now that #4541 is merged?

**Comment by tautschnig** [comment]
@peterschrammel ping?

**Review by peterschrammel — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c07449cb28ef3f08a4cfc83681ec30a47d7b4788).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/112029630

**Pull request merged**
